# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\animation_axis_limits_warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING


class Ui_animationPlotLimitsWarning(object):
    def setupUi(self, animationPlotLimitsWarning):
        animationPlotLimitsWarning.setObjectName("animationPlotLimitsWarning")
        animationPlotLimitsWarning.resize(400, 164)
        self.verticalLayout = QtWidgets.QVBoxLayout(animationPlotLimitsWarning)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(animationPlotLimitsWarning)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout.addItem(spacerItem)
        self.pbCalc = QtWidgets.QPushButton(animationPlotLimitsWarning)
        self.pbCalc.setObjectName("pbCalc")
        self.verticalLayout.addWidget(self.pbCalc)
        self.pbUseTV = QtWidgets.QPushButton(animationPlotLimitsWarning)
        self.pbUseTV.setObjectName("pbUseTV")
        self.verticalLayout.addWidget(self.pbUseTV)
        self.pbCancel = QtWidgets.QPushButton(animationPlotLimitsWarning)
        self.pbCancel.setObjectName("pbCancel")
        self.verticalLayout.addWidget(self.pbCancel)

        self.retranslateUi(animationPlotLimitsWarning)
        QtCore.QMetaObject.connectSlotsByName(animationPlotLimitsWarning)

    def retranslateUi(self, animationPlotLimitsWarning):
        _translate = QtCore.QCoreApplication.translate
        animationPlotLimitsWarning.setWindowTitle(_translate("animationPlotLimitsWarning", "Plot Axis Limits"))
        self.label.setText(_translate("animationPlotLimitsWarning", "<html><head/><body><p><span style=\" font-weight:600;\">Warning</span>: Axis limits have not been set for all <span style=\" font-weight:600;\">Cross Section / Long Profile</span> plots.<br/><br/>Please select an option below:</p></body></html>"))
        self.pbCalc.setText(_translate("animationPlotLimitsWarning", "Calculate Axis Limits (Can be slow)"))
        self.pbUseTV.setText(_translate("animationPlotLimitsWarning", "Use Current Limits in TUFLOW Viewer Cross Section / Long Plot Tab"))
        self.pbCancel.setText(_translate("animationPlotLimitsWarning", "Cancel and Go Set Limits Manually"))
