# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ArchBridgeEditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets


from ..compatibility_routines import QT_ALIGN_V_CENTER, QT_ABSTRACT_SPIN_BOX_UP_DOWN_ARROWS, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM, QT_ALIGN_LEADING


class Ui_archBridgeDialog(object):
    def setupUi(self, archBridgeDialog):
        archBridgeDialog.setObjectName("archBridgeDialog")
        archBridgeDialog.resize(662, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(archBridgeDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(archBridgeDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 642, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.InputData = QtWidgets.QWidget()
        self.InputData.setObjectName("InputData")
        self.gridLayout = QtWidgets.QGridLayout(self.InputData)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.InputData)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.cboNwkLayer = QtWidgets.QComboBox(self.InputData)
        self.cboNwkLayer.setObjectName("cboNwkLayer")
        self.verticalLayout_14.addWidget(self.cboNwkLayer)
        self.label_12 = QtWidgets.QLabel(self.InputData)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bridgeBySelection = QtWidgets.QToolButton(self.InputData)
        self.bridgeBySelection.setObjectName("bridgeBySelection")
        self.horizontalLayout_4.addWidget(self.bridgeBySelection)
        self.cboNwkFeature = QtWidgets.QComboBox(self.InputData)
        self.cboNwkFeature.setObjectName("cboNwkFeature")
        self.horizontalLayout_4.addWidget(self.cboNwkFeature)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_14, 0, 0, 1, 2)
        self.gbUseExisting = QtWidgets.QGroupBox(self.InputData)
        self.gbUseExisting.setCheckable(True)
        self.gbUseExisting.setChecked(False)
        self.gbUseExisting.setObjectName("gbUseExisting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbUseExisting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.gbUseExisting)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.xsLabel = QtWidgets.QLabel(self.gbUseExisting)
        self.xsLabel.setObjectName("xsLabel")
        self.verticalLayout_3.addWidget(self.xsLabel)
        self.lwXSFeature = QtWidgets.QListWidget(self.gbUseExisting)
        self.lwXSFeature.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lwXSFeature.setObjectName("lwXSFeature")
        self.verticalLayout_3.addWidget(self.lwXSFeature)
        self.label_2 = QtWidgets.QLabel(self.gbUseExisting)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.bgLabel = QtWidgets.QLabel(self.gbUseExisting)
        self.bgLabel.setObjectName("bgLabel")
        self.verticalLayout_3.addWidget(self.bgLabel)
        self.lwGBFeature = QtWidgets.QListWidget(self.gbUseExisting)
        self.lwGBFeature.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lwGBFeature.setObjectName("lwGBFeature")
        self.verticalLayout_3.addWidget(self.lwGBFeature)
        self.gridLayout.addWidget(self.gbUseExisting, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.InputData, "")
        self.GeneralData = QtWidgets.QWidget()
        self.GeneralData.setObjectName("GeneralData")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GeneralData)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gbDualBridge_2 = QtWidgets.QGroupBox(self.GeneralData)
        self.gbDualBridge_2.setCheckable(True)
        self.gbDualBridge_2.setChecked(False)
        self.gbDualBridge_2.setObjectName("gbDualBridge_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.gbDualBridge_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.gbDualBridge_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.sbBridgeWidth = QtWidgets.QDoubleSpinBox(self.gbDualBridge_2)
        self.sbBridgeWidth.setDecimals(3)
        self.sbBridgeWidth.setMaximum(99999.0)
        self.sbBridgeWidth.setObjectName("sbBridgeWidth")
        self.verticalLayout_19.addWidget(self.sbBridgeWidth)
        self.horizontalLayout_8.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.gbDualBridge_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_20.addWidget(self.label_16)
        self.sbDualDistance = QtWidgets.QDoubleSpinBox(self.gbDualBridge_2)
        self.sbDualDistance.setDecimals(3)
        self.sbDualDistance.setMaximum(99999.0)
        self.sbDualDistance.setObjectName("sbDualDistance")
        self.verticalLayout_20.addWidget(self.sbDualDistance)
        self.horizontalLayout_8.addLayout(self.verticalLayout_20)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.gridLayout_3.addWidget(self.gbDualBridge_2, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(382, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.GeneralData)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.sbCalibCoeff = QtWidgets.QDoubleSpinBox(self.GeneralData)
        self.sbCalibCoeff.setWrapping(False)
        self.sbCalibCoeff.setFrame(True)
        self.sbCalibCoeff.setButtonSymbols(QT_ABSTRACT_SPIN_BOX_UP_DOWN_ARROWS)
        self.sbCalibCoeff.setDecimals(3)
        self.sbCalibCoeff.setMaximum(99999.0)
        self.sbCalibCoeff.setProperty("value", 1.0)
        self.sbCalibCoeff.setObjectName("sbCalibCoeff")
        self.verticalLayout_16.addWidget(self.sbCalibCoeff)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.GeneralData)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.sbSkewAngle = QtWidgets.QDoubleSpinBox(self.GeneralData)
        self.sbSkewAngle.setDecimals(3)
        self.sbSkewAngle.setMaximum(99999.0)
        self.sbSkewAngle.setObjectName("sbSkewAngle")
        self.verticalLayout_17.addWidget(self.sbSkewAngle)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.gridLayout_3.addItem(spacerItem3, 3, 0, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.GeneralData)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_21.addWidget(self.label_17)
        self.leComment = QtWidgets.QLineEdit(self.GeneralData)
        self.leComment.setObjectName("leComment")
        self.verticalLayout_21.addWidget(self.leComment)
        self.gridLayout_3.addLayout(self.verticalLayout_21, 2, 0, 1, 2)
        self.tabWidget.addTab(self.GeneralData, "")
        self.SectionData = QtWidgets.QWidget()
        self.SectionData.setObjectName("SectionData")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SectionData)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.SectionData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.btnAddChannelRow = QtWidgets.QToolButton(self.SectionData)
        self.btnAddChannelRow.setObjectName("btnAddChannelRow")
        self.horizontalLayout_5.addWidget(self.btnAddChannelRow)
        self.btnRemChannelRow = QtWidgets.QToolButton(self.SectionData)
        self.btnRemChannelRow.setObjectName("btnRemChannelRow")
        self.horizontalLayout_5.addWidget(self.btnRemChannelRow)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.twChannel = ChannelSectionTable(self.SectionData)
        self.twChannel.setObjectName("twChannel")
        self.twChannel.setColumnCount(3)
        self.twChannel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twChannel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twChannel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twChannel.setHorizontalHeaderItem(2, item)
        self.twChannel.horizontalHeader().setDefaultSectionSize(150)
        self.twChannel.verticalHeader().setDefaultSectionSize(20)
        self.twChannel.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_9.addWidget(self.twChannel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbPlot = QtWidgets.QPushButton(self.SectionData)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPlot.sizePolicy().hasHeightForWidth())
        self.pbPlot.setSizePolicy(sizePolicy)
        self.pbPlot.setMinimumSize(QtCore.QSize(75, 0))
        self.pbPlot.setAutoDefault(True)
        self.pbPlot.setFlat(False)
        self.pbPlot.setObjectName("pbPlot")
        self.verticalLayout_4.addWidget(self.pbPlot)
        self.pbImport = QtWidgets.QPushButton(self.SectionData)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbImport.sizePolicy().hasHeightForWidth())
        self.pbImport.setSizePolicy(sizePolicy)
        self.pbImport.setMinimumSize(QtCore.QSize(75, 0))
        self.pbImport.setObjectName("pbImport")
        self.verticalLayout_4.addWidget(self.pbImport)
        self.pbDem = QtWidgets.QPushButton(self.SectionData)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDem.sizePolicy().hasHeightForWidth())
        self.pbDem.setSizePolicy(sizePolicy)
        self.pbDem.setMinimumSize(QtCore.QSize(75, 0))
        self.pbDem.setObjectName("pbDem")
        self.verticalLayout_4.addWidget(self.pbDem)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.SectionData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.btnAddBridgeRow = QtWidgets.QToolButton(self.SectionData)
        self.btnAddBridgeRow.setObjectName("btnAddBridgeRow")
        self.horizontalLayout_6.addWidget(self.btnAddBridgeRow)
        self.btnRemBridgeRow = QtWidgets.QToolButton(self.SectionData)
        self.btnRemBridgeRow.setObjectName("btnRemBridgeRow")
        self.horizontalLayout_6.addWidget(self.btnRemBridgeRow)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.twBridge = BridgeSectionTable(self.SectionData)
        self.twBridge.setMinimumSize(QtCore.QSize(0, 0))
        self.twBridge.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.twBridge.setObjectName("twBridge")
        self.twBridge.setColumnCount(4)
        self.twBridge.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twBridge.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twBridge.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twBridge.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QT_ALIGN_LEADING|QT_ALIGN_V_CENTER)
        self.twBridge.setHorizontalHeaderItem(3, item)
        self.twBridge.horizontalHeader().setDefaultSectionSize(128)
        self.twBridge.verticalHeader().setDefaultSectionSize(20)
        self.twBridge.verticalHeader().setMinimumSectionSize(1)
        self.verticalLayout_10.addWidget(self.twBridge)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.SectionData, "")
        self.OrificeData = QtWidgets.QWidget()
        self.OrificeData.setObjectName("OrificeData")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.OrificeData)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbOrifice = QtWidgets.QCheckBox(self.OrificeData)
        self.cbOrifice.setObjectName("cbOrifice")
        self.gridLayout_2.addWidget(self.cbOrifice, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.OrificeData)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.sbLowerTransDist = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sbLowerTransDist.setDecimals(3)
        self.sbLowerTransDist.setMaximum(99999.0)
        self.sbLowerTransDist.setObjectName("sbLowerTransDist")
        self.verticalLayout_11.addWidget(self.sbLowerTransDist)
        self.verticalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.sbUpperTransDist = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sbUpperTransDist.setDecimals(3)
        self.sbUpperTransDist.setMaximum(99999.0)
        self.sbUpperTransDist.setObjectName("sbUpperTransDist")
        self.verticalLayout_12.addWidget(self.sbUpperTransDist)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.sbOrificeCoeff = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sbOrificeCoeff.setDecimals(3)
        self.sbOrificeCoeff.setMaximum(99999.0)
        self.sbOrificeCoeff.setProperty("value", 1.0)
        self.sbOrificeCoeff.setObjectName("sbOrificeCoeff")
        self.verticalLayout_13.addWidget(self.sbOrificeCoeff)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.OrificeData, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem7)
        self.pbOk = QtWidgets.QPushButton(archBridgeDialog)
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout.addWidget(self.pbOk)
        self.pbCancel = QtWidgets.QPushButton(archBridgeDialog)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(archBridgeDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(archBridgeDialog)

    def retranslateUi(self, archBridgeDialog):
        _translate = QtCore.QCoreApplication.translate
        archBridgeDialog.setWindowTitle(_translate("archBridgeDialog", "Arch Bridge"))
        self.label_11.setText(_translate("archBridgeDialog", "1D Network Layer:"))
        self.label_12.setText(_translate("archBridgeDialog", "1D Network Bridge Feature"))
        self.bridgeBySelection.setToolTip(_translate("archBridgeDialog", "Use Selection"))
        self.bridgeBySelection.setText(_translate("archBridgeDialog", "..."))
        self.gbUseExisting.setTitle(_translate("archBridgeDialog", "Use Existing Bridge Layer"))
        self.label.setText(_translate("archBridgeDialog", "1D Cross Section (1d_xs)"))
        self.xsLabel.setText(_translate("archBridgeDialog", "- Select Which Cross Section To Use"))
        self.label_2.setText(_translate("archBridgeDialog", "1D Bridge (1d_bg)"))
        self.bgLabel.setText(_translate("archBridgeDialog", "- Select Which Bridge Section To Use"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputData), _translate("archBridgeDialog", "Input Data"))
        self.gbDualBridge_2.setTitle(_translate("archBridgeDialog", "Dual Bridge"))
        self.label_15.setText(_translate("archBridgeDialog", "Bridge Width:"))
        self.label_16.setText(_translate("archBridgeDialog", "Dual Distance:"))
        self.label_13.setText(_translate("archBridgeDialog", "Calibration Coefficient:"))
        self.label_14.setText(_translate("archBridgeDialog", "Skew Angle:"))
        self.label_17.setText(_translate("archBridgeDialog", "Comment:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GeneralData), _translate("archBridgeDialog", "General Data"))
        self.label_6.setText(_translate("archBridgeDialog", "Channel Section:"))
        self.btnAddChannelRow.setText(_translate("archBridgeDialog", "..."))
        self.btnRemChannelRow.setText(_translate("archBridgeDialog", "..."))
        item = self.twChannel.horizontalHeaderItem(0)
        item.setText(_translate("archBridgeDialog", "Chainage (m)"))
        item = self.twChannel.horizontalHeaderItem(1)
        item.setText(_translate("archBridgeDialog", "Elevation (m AHD)"))
        item = self.twChannel.horizontalHeaderItem(2)
        item.setText(_translate("archBridgeDialog", "Manning\'s n"))
        self.pbPlot.setText(_translate("archBridgeDialog", "Plot..."))
        self.pbImport.setText(_translate("archBridgeDialog", "Import..."))
        self.pbDem.setText(_translate("archBridgeDialog", "From DEM..."))
        self.label_7.setText(_translate("archBridgeDialog", "Openings:"))
        self.btnAddBridgeRow.setText(_translate("archBridgeDialog", "..."))
        self.btnRemBridgeRow.setText(_translate("archBridgeDialog", "..."))
        item = self.twBridge.horizontalHeaderItem(0)
        item.setText(_translate("archBridgeDialog", "Start (m)"))
        item = self.twBridge.horizontalHeaderItem(1)
        item.setText(_translate("archBridgeDialog", "Finish (m)"))
        item = self.twBridge.horizontalHeaderItem(2)
        item.setText(_translate("archBridgeDialog", "Springing Level (m RL)"))
        item = self.twBridge.horizontalHeaderItem(3)
        item.setText(_translate("archBridgeDialog", "Soffit Level (m RL)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SectionData), _translate("archBridgeDialog", "Section Data"))
        self.cbOrifice.setText(_translate("archBridgeDialog", "Model surcharged bridge as orifice flow"))
        self.groupBox_2.setTitle(_translate("archBridgeDialog", "Orifice parameters:"))
        self.label_8.setText(_translate("archBridgeDialog", "Lower transition distance (m):"))
        self.label_9.setText(_translate("archBridgeDialog", "Upper transition distance (m):"))
        self.label_10.setText(_translate("archBridgeDialog", "Orifice discharge coefficient:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OrificeData), _translate("archBridgeDialog", "Orifice Data"))
        self.pbOk.setText(_translate("archBridgeDialog", "OK"))
        self.pbCancel.setText(_translate("archBridgeDialog", "Cancel"))

from ..bridge_editor.BridgeEditorTable import BridgeSectionTable, ChannelSectionTable
