# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ArchBridgePlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING


class Ui_BridgePlot(object):
    def setupUi(self, BridgePlot):
        BridgePlot.setObjectName("BridgePlot")
        BridgePlot.resize(807, 621)
        self.gridLayout = QtWidgets.QGridLayout(BridgePlot)
        self.gridLayout.setObjectName("gridLayout")
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout.addLayout(self.plotLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem)
        self.pbClose = QtWidgets.QPushButton(BridgePlot)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout.addWidget(self.pbClose)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 20)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(BridgePlot)
        QtCore.QMetaObject.connectSlotsByName(BridgePlot)

    def retranslateUi(self, BridgePlot):
        _translate = QtCore.QCoreApplication.translate
        BridgePlot.setWindowTitle(_translate("BridgePlot", "Plot"))
        self.pbClose.setText(_translate("BridgePlot", "Close"))
