# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ellis.symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\arr_cc_scenarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING


class Ui_ARRCCDialog(object):
    def setupUi(self, ARRCCDialog):
        ARRCCDialog.setObjectName("ARRCCDialog")
        ARRCCDialog.resize(567, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(ARRCCDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QToolButton(ARRCCDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnRem = QtWidgets.QToolButton(ARRCCDialog)
        self.btnRem.setObjectName("btnRem")
        self.horizontalLayout.addWidget(self.btnRem)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = ArrClimateChangeScenTable(ARRCCDialog)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(True)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.table)
        self.label = QtWidgets.QLabel(ARRCCDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbClose = QtWidgets.QPushButton(ARRCCDialog)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout_2.addWidget(self.pbClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ARRCCDialog)
        QtCore.QMetaObject.connectSlotsByName(ARRCCDialog)

    def retranslateUi(self, ARRCCDialog):
        _translate = QtCore.QCoreApplication.translate
        ARRCCDialog.setWindowTitle(_translate("ARRCCDialog", "Climate Change Scenarios"))
        self.btnAdd.setText(_translate("ARRCCDialog", "..."))
        self.btnRem.setText(_translate("ARRCCDialog", "..."))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("ARRCCDialog", "Time Horizon"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("ARRCCDialog", "SSP"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("ARRCCDialog", "Baseline Change"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("ARRCCDialog", "Temp Change*"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("ARRCCDialog", "Scen Name"))
        self.label.setText(_translate("ARRCCDialog", "*Temp Change: set to -1 to use temperature change from datahub. Values of zero or above will override datahub values and are assumed to be the change from pre-industrial period"))
        self.pbClose.setText(_translate("ARRCCDialog", "Close"))
from tuflow.ARR2016.arr_cc_table import ArrClimateChangeScenTable
