# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\BridgeEditorImportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets


from ..compatibility_routines import QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING


class Ui_bridgeEditorImportDialog(object):
    def setupUi(self, bridgeEditorImportDialog):
        bridgeEditorImportDialog.setObjectName("bridgeEditorImportDialog")
        bridgeEditorImportDialog.resize(432, 566)
        self.gridLayout_2 = QtWidgets.QGridLayout(bridgeEditorImportDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sbLines2Discard = QtWidgets.QSpinBox(bridgeEditorImportDialog)
        self.sbLines2Discard.setProperty("value", 1)
        self.sbLines2Discard.setObjectName("sbLines2Discard")
        self.gridLayout.addWidget(self.sbLines2Discard, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 3)
        self.previewTable = QtWidgets.QTableWidget(bridgeEditorImportDialog)
        self.previewTable.setObjectName("previewTable")
        self.previewTable.setColumnCount(0)
        self.previewTable.setRowCount(0)
        self.previewTable.horizontalHeader().setVisible(True)
        self.gridLayout.addWidget(self.previewTable, 14, 0, 1, 5)
        self.cboCol3 = QtWidgets.QComboBox(bridgeEditorImportDialog)
        self.cboCol3.setEditable(True)
        self.cboCol3.setObjectName("cboCol3")
        self.gridLayout.addWidget(self.cboCol3, 9, 3, 1, 2)
        self.cboCol2 = QtWidgets.QComboBox(bridgeEditorImportDialog)
        self.cboCol2.setEditable(True)
        self.cboCol2.setObjectName("cboCol2")
        self.gridLayout.addWidget(self.cboCol2, 8, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 5)
        self.btnBrowse = QtWidgets.QToolButton(bridgeEditorImportDialog)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.label_5 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 5)
        self.label_8 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 5)
        self.labelCol4 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.labelCol4.setObjectName("labelCol4")
        self.gridLayout.addWidget(self.labelCol4, 10, 0, 1, 3)
        self.inFile = QtWidgets.QLineEdit(bridgeEditorImportDialog)
        self.inFile.setObjectName("inFile")
        self.gridLayout.addWidget(self.inFile, 1, 1, 1, 4)
        self.grouBox = QtWidgets.QGroupBox(bridgeEditorImportDialog)
        self.grouBox.setMinimumSize(QtCore.QSize(0, 0))
        self.grouBox.setObjectName("grouBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grouBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbOther = QtWidgets.QRadioButton(self.grouBox)
        self.rbOther.setObjectName("rbOther")
        self.bgDelimiter = QtWidgets.QButtonGroup(bridgeEditorImportDialog)
        self.bgDelimiter.setObjectName("bgDelimiter")
        self.bgDelimiter.addButton(self.rbOther)
        self.gridLayout_3.addWidget(self.rbOther, 0, 3, 1, 1)
        self.rbTab = QtWidgets.QRadioButton(self.grouBox)
        self.rbTab.setObjectName("rbTab")
        self.bgDelimiter.addButton(self.rbTab)
        self.gridLayout_3.addWidget(self.rbTab, 0, 2, 1, 1)
        self.rbSpace = QtWidgets.QRadioButton(self.grouBox)
        self.rbSpace.setObjectName("rbSpace")
        self.bgDelimiter.addButton(self.rbSpace)
        self.gridLayout_3.addWidget(self.rbSpace, 0, 1, 1, 1)
        self.rbCSV = QtWidgets.QRadioButton(self.grouBox)
        self.rbCSV.setChecked(True)
        self.rbCSV.setObjectName("rbCSV")
        self.bgDelimiter.addButton(self.rbCSV)
        self.gridLayout_3.addWidget(self.rbCSV, 0, 0, 1, 1)
        self.delimiter = QtWidgets.QLineEdit(self.grouBox)
        self.delimiter.setObjectName("delimiter")
        self.gridLayout_3.addWidget(self.delimiter, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.grouBox, 2, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 3)
        self.labelCol2 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.labelCol2.setObjectName("labelCol2")
        self.gridLayout.addWidget(self.labelCol2, 8, 0, 1, 3)
        self.cboCol1 = QtWidgets.QComboBox(bridgeEditorImportDialog)
        self.cboCol1.setMinimumSize(QtCore.QSize(0, 0))
        self.cboCol1.setEditable(True)
        self.cboCol1.setObjectName("cboCol1")
        self.gridLayout.addWidget(self.cboCol1, 7, 3, 1, 2)
        self.labelCol3 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.labelCol3.setObjectName("labelCol3")
        self.gridLayout.addWidget(self.labelCol3, 9, 0, 1, 3)
        self.nullValue = QtWidgets.QLineEdit(bridgeEditorImportDialog)
        self.nullValue.setObjectName("nullValue")
        self.gridLayout.addWidget(self.nullValue, 11, 3, 1, 2)
        self.labelCol1 = QtWidgets.QLabel(bridgeEditorImportDialog)
        self.labelCol1.setObjectName("labelCol1")
        self.gridLayout.addWidget(self.labelCol1, 7, 0, 1, 3)
        self.cboCol4 = QtWidgets.QComboBox(bridgeEditorImportDialog)
        self.cboCol4.setEditable(True)
        self.cboCol4.setObjectName("cboCol4")
        self.gridLayout.addWidget(self.cboCol4, 10, 3, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem3)
        self.pbOk = QtWidgets.QPushButton(bridgeEditorImportDialog)
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout.addWidget(self.pbOk)
        self.pbCancel = QtWidgets.QPushButton(bridgeEditorImportDialog)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)

        self.retranslateUi(bridgeEditorImportDialog)
        QtCore.QMetaObject.connectSlotsByName(bridgeEditorImportDialog)

    def retranslateUi(self, bridgeEditorImportDialog):
        _translate = QtCore.QCoreApplication.translate
        bridgeEditorImportDialog.setWindowTitle(_translate("bridgeEditorImportDialog", "Import User Plot Data . . ."))
        self.label_6.setText(_translate("bridgeEditorImportDialog", "Number of Header Lines to Discard:"))
        self.btnBrowse.setText(_translate("bridgeEditorImportDialog", "..."))
        self.label.setText(_translate("bridgeEditorImportDialog", "Delimited File"))
        self.label_5.setText(_translate("bridgeEditorImportDialog", "Preview (first 10 rows):"))
        self.label_8.setText(_translate("bridgeEditorImportDialog", "Header Rows"))
        self.labelCol4.setText(_translate("bridgeEditorImportDialog", "Column 4"))
        self.grouBox.setTitle(_translate("bridgeEditorImportDialog", "Delimited Format"))
        self.rbOther.setText(_translate("bridgeEditorImportDialog", "Other:"))
        self.rbTab.setText(_translate("bridgeEditorImportDialog", "Tab"))
        self.rbSpace.setText(_translate("bridgeEditorImportDialog", "Space"))
        self.rbCSV.setText(_translate("bridgeEditorImportDialog", "CSV"))
        self.label_3.setText(_translate("bridgeEditorImportDialog", "Null Value (optional)"))
        self.labelCol2.setText(_translate("bridgeEditorImportDialog", "Column 2"))
        self.labelCol3.setText(_translate("bridgeEditorImportDialog", "Column 3"))
        self.labelCol1.setText(_translate("bridgeEditorImportDialog", "Column 1"))
        self.pbOk.setText(_translate("bridgeEditorImportDialog", "OK"))
        self.pbCancel.setText(_translate("bridgeEditorImportDialog", "Cancel"))

