# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\flowtrace_plot_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_FRAME_RAISED, QT_ABSTRACT_ITEM_VIEW_EXTENDED_SELECTION, QT_FRAME_STYLED_PANEL


class Ui_flowTracePlotWidget(object):
    def setupUi(self, flowTracePlotWidget):
        flowTracePlotWidget.setObjectName("flowTracePlotWidget")
        flowTracePlotWidget.resize(937, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(flowTracePlotWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.paths = QtWidgets.QListWidget(flowTracePlotWidget)
        self.paths.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paths.setSelectionMode(QT_ABSTRACT_ITEM_VIEW_EXTENDED_SELECTION)
        self.paths.setObjectName("paths")
        self.gridLayout.addWidget(self.paths, 2, 1, 1, 1)
        self.cbLabel = QtWidgets.QCheckBox(flowTracePlotWidget)
        self.cbLabel.setObjectName("cbLabel")
        self.gridLayout.addWidget(self.cbLabel, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbarFrame = QtWidgets.QFrame(flowTracePlotWidget)
        self.toolbarFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarFrame.setFrameShape(QT_FRAME_STYLED_PANEL)
        self.toolbarFrame.setFrameShadow(QT_FRAME_RAISED)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.horizontalLayout.addWidget(self.toolbarFrame)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.pbSelectPath = QtWidgets.QPushButton(flowTracePlotWidget)
        self.pbSelectPath.setObjectName("pbSelectPath")
        self.gridLayout.addWidget(self.pbSelectPath, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(flowTracePlotWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(flowTracePlotWidget)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.plotLayout = QtWidgets.QGridLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout.addLayout(self.plotLayout, 0, 0, 6, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(flowTracePlotWidget)
        QtCore.QMetaObject.connectSlotsByName(flowTracePlotWidget)

    def retranslateUi(self, flowTracePlotWidget):
        _translate = QtCore.QCoreApplication.translate
        flowTracePlotWidget.setWindowTitle(_translate("flowTracePlotWidget", "Flow Trace"))
        self.cbLabel.setText(_translate("flowTracePlotWidget", "Label Network"))
        self.pbSelectPath.setText(_translate("flowTracePlotWidget", "Select Path In Workspace"))
        self.label.setText(_translate("flowTracePlotWidget", "Paths"))
        self.label_2.setText(_translate("flowTracePlotWidget", "<html><head/><body><p><a href=\"https://wiki.tuflow.com/index.php?title=1D_Integrity_Tool_-_Flow_Trace_-_Long_Plot\"><span style=\" text-decoration: underline; color:#0000ff;\">Documentation</span></a></p></body></html>"))
