# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\flowtrace_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_FRAME_RAISED, QT_ABSTRACT_ITEM_VIEW_EXTENDED_SELECTION, QT_FRAME_STYLED_PANEL


class Ui_flowTracePlot(object):
    def setupUi(self, flowTracePlot):
        flowTracePlot.setObjectName("flowTracePlot")
        flowTracePlot.resize(963, 312)
        self.verticalLayout = QtWidgets.QVBoxLayout(flowTracePlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(flowTracePlot)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.paths = QtWidgets.QListWidget(flowTracePlot)
        self.paths.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paths.setSelectionMode(QT_ABSTRACT_ITEM_VIEW_EXTENDED_SELECTION)
        self.paths.setObjectName("paths")
        self.gridLayout.addWidget(self.paths, 1, 1, 1, 1)
        self.cbLabel = QtWidgets.QCheckBox(flowTracePlot)
        self.cbLabel.setObjectName("cbLabel")
        self.gridLayout.addWidget(self.cbLabel, 2, 1, 1, 1)
        self.pbSelectPath = QtWidgets.QPushButton(flowTracePlot)
        self.pbSelectPath.setObjectName("pbSelectPath")
        self.gridLayout.addWidget(self.pbSelectPath, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbarFrame = QtWidgets.QFrame(flowTracePlot)
        self.toolbarFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarFrame.setFrameShape(QT_FRAME_STYLED_PANEL)
        self.toolbarFrame.setFrameShadow(QT_FRAME_RAISED)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.horizontalLayout.addWidget(self.toolbarFrame)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.plotLayout = QtWidgets.QGridLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout.addLayout(self.plotLayout, 0, 0, 5, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(flowTracePlot)
        QtCore.QMetaObject.connectSlotsByName(flowTracePlot)

    def retranslateUi(self, flowTracePlot):
        _translate = QtCore.QCoreApplication.translate
        flowTracePlot.setWindowTitle(_translate("flowTracePlot", "Flow Trace"))
        self.label.setText(_translate("flowTracePlot", "Paths"))
        self.cbLabel.setText(_translate("flowTracePlot", "Label Network"))
        self.pbSelectPath.setText(_translate("flowTracePlot", "Select Path In Workspace"))
