# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ellis.symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\fv_bc_tide_nc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_BUTTON_BOX_CANCEL, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM, QT_BUTTON_BOX_OK, QT_HORIZONTAL


class Ui_ImportFVBCTideDlg(object):
    def setupUi(self, ImportFVBCTideDlg):
        ImportFVBCTideDlg.setObjectName("ImportFVBCTideDlg")
        ImportFVBCTideDlg.resize(557, 318)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ImportFVBCTideDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(ImportFVBCTideDlg)
        self.splitter.setOrientation(QT_HORIZONTAL)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNS = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.btnNS.setObjectName("btnNS")
        self.horizontalLayout.addWidget(self.btnNS)
        self.leNS = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leNS.setObjectName("leNS")
        self.horizontalLayout.addWidget(self.leNS)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnNC = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.btnNC.setObjectName("btnNC")
        self.horizontalLayout_2.addWidget(self.btnNC)
        self.leNC = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leNC.setObjectName("leNC")
        self.horizontalLayout_2.addWidget(self.leNC)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cbUseLocalTime = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbUseLocalTime.setObjectName("cbUseLocalTime")
        self.verticalLayout.addWidget(self.cbUseLocalTime)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolTip = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.toolTip.setObjectName("toolTip")
        self.verticalLayout_2.addWidget(self.toolTip)
        self.verticalLayout_3.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportFVBCTideDlg)
        self.buttonBox.setOrientation(QT_HORIZONTAL)
        self.buttonBox.setStandardButtons(QT_BUTTON_BOX_CANCEL|QT_BUTTON_BOX_OK)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(ImportFVBCTideDlg)
        self.buttonBox.accepted.connect(ImportFVBCTideDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportFVBCTideDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportFVBCTideDlg)

    def retranslateUi(self, ImportFVBCTideDlg):
        _translate = QtCore.QCoreApplication.translate
        ImportFVBCTideDlg.setWindowTitle(_translate("ImportFVBCTideDlg", "Import FV BC Tide"))
        self.label.setText(_translate("ImportFVBCTideDlg", "Node String GIS Layer"))
        self.btnNS.setText(_translate("ImportFVBCTideDlg", "..."))
        self.label_2.setText(_translate("ImportFVBCTideDlg", "NetCDF"))
        self.btnNC.setText(_translate("ImportFVBCTideDlg", "..."))
        self.cbUseLocalTime.setText(_translate("ImportFVBCTideDlg", "Use Local Time (if available)"))
        self.toolTip.setHtml(_translate("ImportFVBCTideDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Tool Tip</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Imports TUFLOW FV tide data from a NetCDF boundary input. The data is assumed to be in the format generated from TUFLOW FV &quot;Get Tide&quot; tool:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://fvwiki.tuflow.com/TUFLOW_FV_Get_Tide\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://fvwiki.tuflow.com/TUFLOW_FV_Get_Tide</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The tool requires 2 inputs, the NetCDF file containing the boundary data and the GIS node string showing the location of the boundary.</span></p></body></html>"))
