# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pavlina.monhartova\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\scs_dock.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets


from ..compatibility_routines import QT_SIZE_POLICY_PREFERRED, QT_ALIGN_V_CENTER, QT_ALIGN_TRAILING, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_FIXED, QT_ALIGN_RIGHT, QT_WHEEL_FOCUS, QT_SIZE_POLICY_MINIMUM


class Ui_scs(object):
    def setupUi(self, scs):
        scs.setObjectName("scs")
        scs.resize(465, 884)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.progressBarLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.progressBarLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBarLabel.setObjectName("progressBarLabel")
        self.horizontalLayout.addWidget(self.progressBarLabel)
        self.pbRun = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pbRun.setObjectName("pbRun")
        self.horizontalLayout.addWidget(self.pbRun)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 445, 811))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.cboLocation = QtWidgets.QComboBox(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLocation.sizePolicy().hasHeightForWidth())
        self.cboLocation.setSizePolicy(sizePolicy)
        self.cboLocation.setMinimumSize(QtCore.QSize(210, 0))
        self.cboLocation.setObjectName("cboLocation")
        self.cboLocation.addItem("")
        self.cboLocation.addItem("")
        self.horizontalLayout_8.addWidget(self.cboLocation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.groupBox_4 = QtWidgets.QGroupBox(self.mGroupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb010Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb010Year.setChecked(False)
        self.cb010Year.setObjectName("cb010Year")
        self.gridLayout_3.addWidget(self.cb010Year, 3, 0, 1, 1)
        self.cb100Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb100Year.setChecked(False)
        self.cb100Year.setObjectName("cb100Year")
        self.gridLayout_3.addWidget(self.cb100Year, 6, 0, 1, 1)
        self.cb050Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb050Year.setObjectName("cb050Year")
        self.gridLayout_3.addWidget(self.cb050Year, 5, 0, 1, 1)
        self.le010YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le010YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le010YearDepth.setText("")
        self.le010YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le010YearDepth.setObjectName("le010YearDepth")
        self.gridLayout_3.addWidget(self.le010YearDepth, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 1, 1, 1)
        self.le002YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le002YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le002YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le002YearDepth.setObjectName("le002YearDepth")
        self.gridLayout_3.addWidget(self.le002YearDepth, 1, 1, 1, 1)
        self.le005YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le005YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le005YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le005YearDepth.setObjectName("le005YearDepth")
        self.gridLayout_3.addWidget(self.le005YearDepth, 2, 1, 1, 1)
        self.cb002YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb002YearCC.setObjectName("cb002YearCC")
        self.gridLayout_3.addWidget(self.cb002YearCC, 1, 3, 1, 1)
        self.cb020Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb020Year.setObjectName("cb020Year")
        self.gridLayout_3.addWidget(self.cb020Year, 4, 0, 1, 1)
        self.cbSelectAllEvents = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbSelectAllEvents.setObjectName("cbSelectAllEvents")
        self.gridLayout_3.addWidget(self.cbSelectAllEvents, 0, 0, 1, 1)
        self.cb005Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb005Year.setObjectName("cb005Year")
        self.gridLayout_3.addWidget(self.cb005Year, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.le005YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le005YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le005YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le005YearDepthCC.setObjectName("le005YearDepthCC")
        self.gridLayout_3.addWidget(self.le005YearDepthCC, 2, 5, 1, 1)
        self.le050YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le050YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le050YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le050YearDepth.setObjectName("le050YearDepth")
        self.gridLayout_3.addWidget(self.le050YearDepth, 5, 1, 1, 1)
        self.cb020YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb020YearCC.setObjectName("cb020YearCC")
        self.gridLayout_3.addWidget(self.cb020YearCC, 4, 3, 1, 1)
        self.cb050YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb050YearCC.setObjectName("cb050YearCC")
        self.gridLayout_3.addWidget(self.cb050YearCC, 5, 3, 1, 1)
        self.le005YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le005YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le005YearRaiseCC.setText("")
        self.le005YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le005YearRaiseCC.setReadOnly(True)
        self.le005YearRaiseCC.setObjectName("le005YearRaiseCC")
        self.gridLayout_3.addWidget(self.le005YearRaiseCC, 2, 4, 1, 1)
        self.le010YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le010YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le010YearRaiseCC.setText("")
        self.le010YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le010YearRaiseCC.setReadOnly(True)
        self.le010YearRaiseCC.setObjectName("le010YearRaiseCC")
        self.gridLayout_3.addWidget(self.le010YearRaiseCC, 3, 4, 1, 1)
        self.cb010YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb010YearCC.setChecked(False)
        self.cb010YearCC.setObjectName("cb010YearCC")
        self.gridLayout_3.addWidget(self.cb010YearCC, 3, 3, 1, 1)
        self.le020YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le020YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le020YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le020YearDepth.setObjectName("le020YearDepth")
        self.gridLayout_3.addWidget(self.le020YearDepth, 4, 1, 1, 1)
        self.le020YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le020YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le020YearRaiseCC.setText("")
        self.le020YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le020YearRaiseCC.setReadOnly(True)
        self.le020YearRaiseCC.setObjectName("le020YearRaiseCC")
        self.gridLayout_3.addWidget(self.le020YearRaiseCC, 4, 4, 1, 1)
        self.cbSelectAllEventsCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbSelectAllEventsCC.setObjectName("cbSelectAllEventsCC")
        self.gridLayout_3.addWidget(self.cbSelectAllEventsCC, 0, 3, 1, 1)
        self.le002YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le002YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le002YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le002YearDepthCC.setObjectName("le002YearDepthCC")
        self.gridLayout_3.addWidget(self.le002YearDepthCC, 1, 5, 1, 1)
        self.cb002Year = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb002Year.setObjectName("cb002Year")
        self.gridLayout_3.addWidget(self.cb002Year, 1, 0, 1, 1)
        self.le002YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le002YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le002YearRaiseCC.setText("")
        self.le002YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le002YearRaiseCC.setReadOnly(True)
        self.le002YearRaiseCC.setClearButtonEnabled(False)
        self.le002YearRaiseCC.setObjectName("le002YearRaiseCC")
        self.gridLayout_3.addWidget(self.le002YearRaiseCC, 1, 4, 1, 1)
        self.cb100YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb100YearCC.setChecked(False)
        self.cb100YearCC.setObjectName("cb100YearCC")
        self.gridLayout_3.addWidget(self.cb100YearCC, 6, 3, 1, 1)
        self.le050YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le050YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le050YearRaiseCC.setText("")
        self.le050YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le050YearRaiseCC.setReadOnly(True)
        self.le050YearRaiseCC.setObjectName("le050YearRaiseCC")
        self.gridLayout_3.addWidget(self.le050YearRaiseCC, 5, 4, 1, 1)
        self.le100YearRaiseCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le100YearRaiseCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le100YearRaiseCC.setText("")
        self.le100YearRaiseCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le100YearRaiseCC.setReadOnly(True)
        self.le100YearRaiseCC.setObjectName("le100YearRaiseCC")
        self.gridLayout_3.addWidget(self.le100YearRaiseCC, 6, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 4, 1, 1)
        self.cb005YearCC = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb005YearCC.setObjectName("cb005YearCC")
        self.gridLayout_3.addWidget(self.cb005YearCC, 2, 3, 1, 1)
        self.le100YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le100YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le100YearDepthCC.setText("")
        self.le100YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le100YearDepthCC.setObjectName("le100YearDepthCC")
        self.gridLayout_3.addWidget(self.le100YearDepthCC, 6, 5, 1, 1)
        self.le020YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le020YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le020YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le020YearDepthCC.setObjectName("le020YearDepthCC")
        self.gridLayout_3.addWidget(self.le020YearDepthCC, 4, 5, 1, 1)
        self.le010YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le010YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le010YearDepthCC.setText("")
        self.le010YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le010YearDepthCC.setObjectName("le010YearDepthCC")
        self.gridLayout_3.addWidget(self.le010YearDepthCC, 3, 5, 1, 1)
        self.le050YearDepthCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.le050YearDepthCC.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le050YearDepthCC.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le050YearDepthCC.setObjectName("le050YearDepthCC")
        self.gridLayout_3.addWidget(self.le050YearDepthCC, 5, 5, 1, 1)
        self.le100YearDepth = QtWidgets.QLineEdit(self.groupBox_4)
        self.le100YearDepth.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le100YearDepth.setText("")
        self.le100YearDepth.setAlignment(QT_ALIGN_RIGHT|QT_ALIGN_TRAILING|QT_ALIGN_V_CENTER)
        self.le100YearDepth.setObjectName("le100YearDepth")
        self.gridLayout_3.addWidget(self.le100YearDepth, 6, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.mGroupBox)
        self.mGroupBox_3 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox_3.setObjectName("mGroupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mGroupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_38 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 1, 0, 1, 1)
        self.sbDecimals = QtWidgets.QSpinBox(self.mGroupBox_3)
        self.sbDecimals.setMinimumSize(QtCore.QSize(80, 18))
        self.sbDecimals.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sbDecimals.setMaximum(6)
        self.sbDecimals.setProperty("value", 3)
        self.sbDecimals.setObjectName("sbDecimals")
        self.gridLayout_9.addWidget(self.sbDecimals, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(59, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_9.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_9.addItem(spacerItem2, 2, 3, 1, 1)
        self.sbIntervalOut = QtWidgets.QSpinBox(self.mGroupBox_3)
        self.sbIntervalOut.setMinimumSize(QtCore.QSize(80, 0))
        self.sbIntervalOut.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sbIntervalOut.setMinimum(1)
        self.sbIntervalOut.setMaximum(10)
        self.sbIntervalOut.setObjectName("sbIntervalOut")
        self.gridLayout_9.addWidget(self.sbIntervalOut, 1, 2, 1, 1)
        self.sbIntervalIn = QtWidgets.QSpinBox(self.mGroupBox_3)
        self.sbIntervalIn.setMinimumSize(QtCore.QSize(80, 0))
        self.sbIntervalIn.setMinimum(1)
        self.sbIntervalIn.setMaximum(10)
        self.sbIntervalIn.setObjectName("sbIntervalIn")
        self.gridLayout_9.addWidget(self.sbIntervalIn, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_9)
        self.verticalLayout.addWidget(self.mGroupBox_3)
        self.gbManualApproach = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.gbManualApproach.setCheckable(True)
        self.gbManualApproach.setChecked(False)
        self.gbManualApproach.setCollapsed(True)
        self.gbManualApproach.setSaveCollapsedState(False)
        self.gbManualApproach.setSaveCheckedState(False)
        self.gbManualApproach.setObjectName("gbManualApproach")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbManualApproach)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.leAreaImp1Suf = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp1Suf.sizePolicy().hasHeightForWidth())
        self.leAreaImp1Suf.setSizePolicy(sizePolicy)
        self.leAreaImp1Suf.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaImp1Suf.setText("")
        self.leAreaImp1Suf.setObjectName("leAreaImp1Suf")
        self.gridLayout_5.addWidget(self.leAreaImp1Suf, 4, 5, 1, 1)
        self.cbAreaImp2 = QtWidgets.QCheckBox(self.gbManualApproach)
        self.cbAreaImp2.setChecked(False)
        self.cbAreaImp2.setObjectName("cbAreaImp2")
        self.gridLayout_5.addWidget(self.cbAreaImp2, 5, 0, 1, 1)
        self.leCatchId = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCatchId.sizePolicy().hasHeightForWidth())
        self.leCatchId.setSizePolicy(sizePolicy)
        self.leCatchId.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leCatchId.setText("")
        self.leCatchId.setObjectName("leCatchId")
        self.gridLayout_5.addWidget(self.leCatchId, 0, 2, 1, 1)
        self.leAreaPerSuf = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaPerSuf.sizePolicy().hasHeightForWidth())
        self.leAreaPerSuf.setSizePolicy(sizePolicy)
        self.leAreaPerSuf.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaPerSuf.setText("")
        self.leAreaPerSuf.setObjectName("leAreaPerSuf")
        self.gridLayout_5.addWidget(self.leAreaPerSuf, 3, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_5.addItem(spacerItem3, 3, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 5, 4, 1, 1)
        self.leCnPer = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCnPer.sizePolicy().hasHeightForWidth())
        self.leCnPer.setSizePolicy(sizePolicy)
        self.leCnPer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leCnPer.setText("")
        self.leCnPer.setObjectName("leCnPer")
        self.gridLayout_5.addWidget(self.leCnPer, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.leAreaImp2Suf = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp2Suf.sizePolicy().hasHeightForWidth())
        self.leAreaImp2Suf.setSizePolicy(sizePolicy)
        self.leAreaImp2Suf.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaImp2Suf.setText("")
        self.leAreaImp2Suf.setObjectName("leAreaImp2Suf")
        self.gridLayout_5.addWidget(self.leAreaImp2Suf, 5, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(16, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(145, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.leAreaImp1 = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp1.sizePolicy().hasHeightForWidth())
        self.leAreaImp1.setSizePolicy(sizePolicy)
        self.leAreaImp1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaImp1.setText("")
        self.leAreaImp1.setObjectName("leAreaImp1")
        self.gridLayout_5.addWidget(self.leAreaImp1, 4, 2, 1, 1)
        self.leAreaPer = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaPer.sizePolicy().hasHeightForWidth())
        self.leAreaPer.setSizePolicy(sizePolicy)
        self.leAreaPer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaPer.setText("")
        self.leAreaPer.setObjectName("leAreaPer")
        self.gridLayout_5.addWidget(self.leAreaPer, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 3, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 4, 4, 1, 1)
        self.leAreaImp2 = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp2.sizePolicy().hasHeightForWidth())
        self.leAreaImp2.setSizePolicy(sizePolicy)
        self.leAreaImp2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAreaImp2.setText("")
        self.leAreaImp2.setObjectName("leAreaImp2")
        self.gridLayout_5.addWidget(self.leAreaImp2, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 2, 0, 1, 1)
        self.leCnImp = QtWidgets.QLineEdit(self.gbManualApproach)
        self.leCnImp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leCnImp.setText("")
        self.leCnImp.setObjectName("leCnImp")
        self.gridLayout_5.addWidget(self.leCnImp, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.label_22 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.leTcImp = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTcImp.sizePolicy().hasHeightForWidth())
        self.leTcImp.setSizePolicy(sizePolicy)
        self.leTcImp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leTcImp.setText("")
        self.leTcImp.setObjectName("leTcImp")
        self.gridLayout_7.addWidget(self.leTcImp, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 3, 1, 1)
        self.rbTpManual = QtWidgets.QRadioButton(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbTpManual.sizePolicy().hasHeightForWidth())
        self.rbTpManual.setSizePolicy(sizePolicy)
        self.rbTpManual.setMinimumSize(QtCore.QSize(160, 0))
        self.rbTpManual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rbTpManual.setChecked(True)
        self.rbTpManual.setObjectName("rbTpManual")
        self.gridLayout_7.addWidget(self.rbTpManual, 0, 0, 1, 1)
        self.rbTcManual = QtWidgets.QRadioButton(self.gbManualApproach)
        self.rbTcManual.setMinimumSize(QtCore.QSize(160, 0))
        self.rbTcManual.setObjectName("rbTcManual")
        self.gridLayout_7.addWidget(self.rbTcManual, 1, 0, 1, 1)
        self.leTcPer = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTcPer.sizePolicy().hasHeightForWidth())
        self.leTcPer.setSizePolicy(sizePolicy)
        self.leTcPer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leTcPer.setText("")
        self.leTcPer.setObjectName("leTcPer")
        self.gridLayout_7.addWidget(self.leTcPer, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 1, 3, 1, 1)
        self.leTpImp = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTpImp.sizePolicy().hasHeightForWidth())
        self.leTpImp.setSizePolicy(sizePolicy)
        self.leTpImp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leTpImp.setText("")
        self.leTpImp.setObjectName("leTpImp")
        self.gridLayout_7.addWidget(self.leTpImp, 0, 4, 1, 1)
        self.leTpPer = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTpPer.sizePolicy().hasHeightForWidth())
        self.leTpPer.setSizePolicy(sizePolicy)
        self.leTpPer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leTpPer.setText("")
        self.leTpPer.setObjectName("leTpPer")
        self.gridLayout_7.addWidget(self.leTpPer, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_7.addItem(spacerItem5, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rbTpTcCalcsManual = QtWidgets.QRadioButton(self.gbManualApproach)
        self.rbTpTcCalcsManual.setObjectName("rbTpTcCalcsManual")
        self.horizontalLayout_3.addWidget(self.rbTpTcCalcsManual)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 1, 1)
        self.leCImp = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCImp.sizePolicy().hasHeightForWidth())
        self.leCImp.setSizePolicy(sizePolicy)
        self.leCImp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leCImp.setText("")
        self.leCImp.setObjectName("leCImp")
        self.gridLayout_4.addWidget(self.leCImp, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(140, 0))
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 1, 1, 1)
        self.leLength = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leLength.sizePolicy().hasHeightForWidth())
        self.leLength.setSizePolicy(sizePolicy)
        self.leLength.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leLength.setText("")
        self.leLength.setObjectName("leLength")
        self.gridLayout_4.addWidget(self.leLength, 1, 2, 1, 1)
        self.leCPer = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCPer.sizePolicy().hasHeightForWidth())
        self.leCPer.setSizePolicy(sizePolicy)
        self.leCPer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leCPer.setText("")
        self.leCPer.setObjectName("leCPer")
        self.gridLayout_4.addWidget(self.leCPer, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 0, 4, 1, 1)
        self.leSlope = QtWidgets.QLineEdit(self.gbManualApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSlope.sizePolicy().hasHeightForWidth())
        self.leSlope.setSizePolicy(sizePolicy)
        self.leSlope.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leSlope.setText("")
        self.leSlope.setObjectName("leSlope")
        self.gridLayout_4.addWidget(self.leSlope, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbManualApproach)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.gbManualApproach)
        self.gbGisApproach = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.gbGisApproach.setEnabled(True)
        self.gbGisApproach.setCheckable(True)
        self.gbGisApproach.setChecked(False)
        self.gbGisApproach.setCollapsed(True)
        self.gbGisApproach.setSaveCollapsedState(False)
        self.gbGisApproach.setSaveCheckedState(False)
        self.gbGisApproach.setObjectName("gbGisApproach")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbGisApproach)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.cboIdField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboIdField.sizePolicy().hasHeightForWidth())
        self.cboIdField.setSizePolicy(sizePolicy)
        self.cboIdField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboIdField.setObjectName("cboIdField")
        self.gridLayout_6.addWidget(self.cboIdField, 1, 1, 1, 1)
        self.cboInputPolygons = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInputPolygons.sizePolicy().hasHeightForWidth())
        self.cboInputPolygons.setSizePolicy(sizePolicy)
        self.cboInputPolygons.setMinimumSize(QtCore.QSize(182, 0))
        self.cboInputPolygons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cboInputPolygons.setObjectName("cboInputPolygons")
        self.gridLayout_6.addWidget(self.cboInputPolygons, 0, 1, 1, 1)
        self.cboCnPerField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCnPerField.sizePolicy().hasHeightForWidth())
        self.cboCnPerField.setSizePolicy(sizePolicy)
        self.cboCnPerField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboCnPerField.setObjectName("cboCnPerField")
        self.gridLayout_6.addWidget(self.cboCnPerField, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.cboCnImpField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCnImpField.sizePolicy().hasHeightForWidth())
        self.cboCnImpField.setSizePolicy(sizePolicy)
        self.cboCnImpField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboCnImpField.setObjectName("cboCnImpField")
        self.gridLayout_6.addWidget(self.cboCnImpField, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cboAreaPerCCField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaPerCCField.sizePolicy().hasHeightForWidth())
        self.cboAreaPerCCField.setSizePolicy(sizePolicy)
        self.cboAreaPerCCField.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaPerCCField.setObjectName("cboAreaPerCCField")
        self.gridLayout_2.addWidget(self.cboAreaPerCCField, 5, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 6, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 7, 0, 1, 1)
        self.cbAreaImp2Gis = QtWidgets.QCheckBox(self.gbGisApproach)
        self.cbAreaImp2Gis.setChecked(False)
        self.cbAreaImp2Gis.setObjectName("cbAreaImp2Gis")
        self.gridLayout_2.addWidget(self.cbAreaImp2Gis, 8, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 5, 0, 1, 1)
        self.cboAreaImp2CCField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaImp2CCField.sizePolicy().hasHeightForWidth())
        self.cboAreaImp2CCField.setSizePolicy(sizePolicy)
        self.cboAreaImp2CCField.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaImp2CCField.setFocusPolicy(QT_WHEEL_FOCUS)
        self.cboAreaImp2CCField.setObjectName("cboAreaImp2CCField")
        self.gridLayout_2.addWidget(self.cboAreaImp2CCField, 9, 1, 1, 1)
        self.cboAreaPerField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaPerField.sizePolicy().hasHeightForWidth())
        self.cboAreaPerField.setSizePolicy(sizePolicy)
        self.cboAreaPerField.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaPerField.setObjectName("cboAreaPerField")
        self.gridLayout_2.addWidget(self.cboAreaPerField, 4, 1, 1, 1)
        self.leAreaPerSufGis = QtWidgets.QLineEdit(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaPerSufGis.sizePolicy().hasHeightForWidth())
        self.leAreaPerSufGis.setSizePolicy(sizePolicy)
        self.leAreaPerSufGis.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leAreaPerSufGis.setText("")
        self.leAreaPerSufGis.setObjectName("leAreaPerSufGis")
        self.gridLayout_2.addWidget(self.leAreaPerSufGis, 4, 3, 1, 1)
        self.cboAreaImp1Field = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaImp1Field.sizePolicy().hasHeightForWidth())
        self.cboAreaImp1Field.setSizePolicy(sizePolicy)
        self.cboAreaImp1Field.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaImp1Field.setObjectName("cboAreaImp1Field")
        self.gridLayout_2.addWidget(self.cboAreaImp1Field, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.cboAreaImp1CCField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaImp1CCField.sizePolicy().hasHeightForWidth())
        self.cboAreaImp1CCField.setSizePolicy(sizePolicy)
        self.cboAreaImp1CCField.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaImp1CCField.setObjectName("cboAreaImp1CCField")
        self.gridLayout_2.addWidget(self.cboAreaImp1CCField, 7, 1, 1, 1)
        self.cboAreaImp2Field = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAreaImp2Field.sizePolicy().hasHeightForWidth())
        self.cboAreaImp2Field.setSizePolicy(sizePolicy)
        self.cboAreaImp2Field.setMinimumSize(QtCore.QSize(70, 0))
        self.cboAreaImp2Field.setObjectName("cboAreaImp2Field")
        self.gridLayout_2.addWidget(self.cboAreaImp2Field, 8, 1, 1, 1)
        self.leAreaImp1SufGis = QtWidgets.QLineEdit(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp1SufGis.sizePolicy().hasHeightForWidth())
        self.leAreaImp1SufGis.setSizePolicy(sizePolicy)
        self.leAreaImp1SufGis.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leAreaImp1SufGis.setText("")
        self.leAreaImp1SufGis.setObjectName("leAreaImp1SufGis")
        self.gridLayout_2.addWidget(self.leAreaImp1SufGis, 6, 3, 1, 1)
        self.leAreaImp2SufGis = QtWidgets.QLineEdit(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAreaImp2SufGis.sizePolicy().hasHeightForWidth())
        self.leAreaImp2SufGis.setSizePolicy(sizePolicy)
        self.leAreaImp2SufGis.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leAreaImp2SufGis.setText("")
        self.leAreaImp2SufGis.setObjectName("leAreaImp2SufGis")
        self.gridLayout_2.addWidget(self.leAreaImp2SufGis, 8, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 6, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 8, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 9, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.label_23 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 6, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.rbTpTcGis = QtWidgets.QRadioButton(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbTpTcGis.sizePolicy().hasHeightForWidth())
        self.rbTpTcGis.setSizePolicy(sizePolicy)
        self.rbTpTcGis.setMaximumSize(QtCore.QSize(55, 16777215))
        self.rbTpTcGis.setChecked(True)
        self.rbTpTcGis.setObjectName("rbTpTcGis")
        self.buttonGroup = QtWidgets.QButtonGroup(scs)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbTpTcGis)
        self.horizontalLayout_6.addWidget(self.rbTpTcGis)
        self.cbTpCheck = QtWidgets.QCheckBox(self.gbGisApproach)
        self.cbTpCheck.setMaximumSize(QtCore.QSize(47, 16777215))
        self.cbTpCheck.setChecked(False)
        self.cbTpCheck.setObjectName("cbTpCheck")
        self.horizontalLayout_6.addWidget(self.cbTpCheck)
        spacerItem9 = QtWidgets.QSpacerItem(3, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.cbTcCheck = QtWidgets.QCheckBox(self.gbGisApproach)
        self.cbTcCheck.setObjectName("cbTcCheck")
        self.horizontalLayout_6.addWidget(self.cbTcCheck)
        self.cboTpTcField = QtWidgets.QComboBox(self.gbGisApproach)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboTpTcField.sizePolicy().hasHeightForWidth())
        self.cboTpTcField.setSizePolicy(sizePolicy)
        self.cboTpTcField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboTpTcField.setObjectName("cboTpTcField")
        self.horizontalLayout_6.addWidget(self.cboTpTcField)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.rbTpTcCalcsGis = QtWidgets.QRadioButton(self.gbGisApproach)
        self.rbTpTcCalcsGis.setEnabled(False)
        self.rbTpTcCalcsGis.setObjectName("rbTpTcCalcsGis")
        self.buttonGroup.addButton(self.rbTpTcCalcsGis)
        self.horizontalLayout_2.addWidget(self.rbTpTcCalcsGis)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_8.addItem(spacerItem12, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_24.setEnabled(False)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.label_7 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.label_28 = QtWidgets.QLabel(self.gbGisApproach)
        self.label_28.setEnabled(False)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 4, 1, 1, 1)
        self.cboInputPolylines = QtWidgets.QComboBox(self.gbGisApproach)
        self.cboInputPolylines.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInputPolylines.sizePolicy().hasHeightForWidth())
        self.cboInputPolylines.setSizePolicy(sizePolicy)
        self.cboInputPolylines.setMinimumSize(QtCore.QSize(182, 0))
        self.cboInputPolylines.setObjectName("cboInputPolylines")
        self.gridLayout_8.addWidget(self.cboInputPolylines, 4, 2, 1, 1)
        self.cboSlopeField = QtWidgets.QComboBox(self.gbGisApproach)
        self.cboSlopeField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSlopeField.sizePolicy().hasHeightForWidth())
        self.cboSlopeField.setSizePolicy(sizePolicy)
        self.cboSlopeField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboSlopeField.setObjectName("cboSlopeField")
        self.gridLayout_8.addWidget(self.cboSlopeField, 2, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_8.addItem(spacerItem15, 3, 0, 1, 1)
        self.rbDemStreamline = QtWidgets.QRadioButton(self.gbGisApproach)
        self.rbDemStreamline.setEnabled(False)
        self.rbDemStreamline.setObjectName("rbDemStreamline")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(scs)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbDemStreamline)
        self.gridLayout_8.addWidget(self.rbDemStreamline, 3, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_MINIMUM)
        self.gridLayout_8.addItem(spacerItem16, 1, 0, 1, 1)
        self.cboLengthField = QtWidgets.QComboBox(self.gbGisApproach)
        self.cboLengthField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLengthField.sizePolicy().hasHeightForWidth())
        self.cboLengthField.setSizePolicy(sizePolicy)
        self.cboLengthField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboLengthField.setObjectName("cboLengthField")
        self.gridLayout_8.addWidget(self.cboLengthField, 1, 2, 1, 1)
        self.cboInputDem = QtWidgets.QComboBox(self.gbGisApproach)
        self.cboInputDem.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInputDem.sizePolicy().hasHeightForWidth())
        self.cboInputDem.setSizePolicy(sizePolicy)
        self.cboInputDem.setMinimumSize(QtCore.QSize(182, 0))
        self.cboInputDem.setObjectName("cboInputDem")
        self.gridLayout_8.addWidget(self.cboInputDem, 3, 2, 1, 1)
        self.rbLengthSlope = QtWidgets.QRadioButton(self.gbGisApproach)
        self.rbLengthSlope.setEnabled(False)
        self.rbLengthSlope.setChecked(True)
        self.rbLengthSlope.setObjectName("rbLengthSlope")
        self.buttonGroup_2.addButton(self.rbLengthSlope)
        self.gridLayout_8.addWidget(self.rbLengthSlope, 1, 1, 1, 1)
        self.cboCField = QtWidgets.QComboBox(self.gbGisApproach)
        self.cboCField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_FIXED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCField.sizePolicy().hasHeightForWidth())
        self.cboCField.setSizePolicy(sizePolicy)
        self.cboCField.setMinimumSize(QtCore.QSize(182, 0))
        self.cboCField.setObjectName("cboCField")
        self.gridLayout_8.addWidget(self.cboCField, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.verticalLayout.addWidget(self.gbGisApproach)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.leOutput = QtWidgets.QLineEdit(self.mGroupBox_2)
        self.leOutput.setText("")
        self.leOutput.setObjectName("leOutput")
        self.horizontalLayout_7.addWidget(self.leOutput)
        self.btnOutput = QtWidgets.QToolButton(self.mGroupBox_2)
        self.btnOutput.setObjectName("btnOutput")
        self.horizontalLayout_7.addWidget(self.btnOutput)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.mGroupBox_2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout.addItem(spacerItem18)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        scs.setWidget(self.dockWidgetContents)

        self.retranslateUi(scs)
        QtCore.QMetaObject.connectSlotsByName(scs)
        scs.setTabOrder(self.scrollArea, self.mGroupBox)
        scs.setTabOrder(self.mGroupBox, self.cbSelectAllEvents)
        scs.setTabOrder(self.cbSelectAllEvents, self.cb002Year)
        scs.setTabOrder(self.cb002Year, self.le002YearDepth)
        scs.setTabOrder(self.le002YearDepth, self.cb005Year)
        scs.setTabOrder(self.cb005Year, self.le005YearDepth)
        scs.setTabOrder(self.le005YearDepth, self.cb010Year)
        scs.setTabOrder(self.cb010Year, self.le010YearDepth)
        scs.setTabOrder(self.le010YearDepth, self.cb020Year)
        scs.setTabOrder(self.cb020Year, self.le020YearDepth)
        scs.setTabOrder(self.le020YearDepth, self.cb050Year)
        scs.setTabOrder(self.cb050Year, self.le050YearDepth)
        scs.setTabOrder(self.le050YearDepth, self.cb100Year)
        scs.setTabOrder(self.cb100Year, self.le100YearDepth)
        scs.setTabOrder(self.le100YearDepth, self.cbSelectAllEventsCC)
        scs.setTabOrder(self.cbSelectAllEventsCC, self.cb002YearCC)
        scs.setTabOrder(self.cb002YearCC, self.le002YearRaiseCC)
        scs.setTabOrder(self.le002YearRaiseCC, self.le002YearDepthCC)
        scs.setTabOrder(self.le002YearDepthCC, self.cb005YearCC)
        scs.setTabOrder(self.cb005YearCC, self.le005YearRaiseCC)
        scs.setTabOrder(self.le005YearRaiseCC, self.le005YearDepthCC)
        scs.setTabOrder(self.le005YearDepthCC, self.cb010YearCC)
        scs.setTabOrder(self.cb010YearCC, self.le010YearRaiseCC)
        scs.setTabOrder(self.le010YearRaiseCC, self.le010YearDepthCC)
        scs.setTabOrder(self.le010YearDepthCC, self.cb020YearCC)
        scs.setTabOrder(self.cb020YearCC, self.le020YearRaiseCC)
        scs.setTabOrder(self.le020YearRaiseCC, self.le020YearDepthCC)
        scs.setTabOrder(self.le020YearDepthCC, self.cb050YearCC)
        scs.setTabOrder(self.cb050YearCC, self.le050YearRaiseCC)
        scs.setTabOrder(self.le050YearRaiseCC, self.le050YearDepthCC)
        scs.setTabOrder(self.le050YearDepthCC, self.cb100YearCC)
        scs.setTabOrder(self.cb100YearCC, self.le100YearRaiseCC)
        scs.setTabOrder(self.le100YearRaiseCC, self.le100YearDepthCC)
        scs.setTabOrder(self.le100YearDepthCC, self.rbTpManual)
        scs.setTabOrder(self.rbTpManual, self.rbTpTcGis)
        scs.setTabOrder(self.rbTpTcGis, self.mGroupBox_2)
        scs.setTabOrder(self.mGroupBox_2, self.leOutput)
        scs.setTabOrder(self.leOutput, self.btnOutput)
        scs.setTabOrder(self.btnOutput, self.pbRun)

    def retranslateUi(self, scs):
        _translate = QtCore.QCoreApplication.translate
        scs.setWindowTitle(_translate("scs", "   SCS Curve Number Method (beta)"))
        self.progressBarLabel.setText(_translate("scs", "Ready"))
        self.pbRun.setText(_translate("scs", "Run"))
        self.mGroupBox.setTitle(_translate("scs", "Rainfall"))
        self.label.setText(_translate("scs", "Catchment Location"))
        self.cboLocation.setItemText(0, _translate("scs", "-Select catchment location-"))
        self.cboLocation.setItemText(1, _translate("scs", "Auckland Region (TP108)"))
        self.groupBox_4.setTitle(_translate("scs", "Event Selection and Design Rainfall Depth (mm)"))
        self.cb010Year.setText(_translate("scs", "10 year"))
        self.cb100Year.setText(_translate("scs", "100 year"))
        self.cb050Year.setText(_translate("scs", "50 year"))
        self.label_13.setText(_translate("scs", "Depth (mm)"))
        self.cb002YearCC.setText(_translate("scs", "2 year CC"))
        self.cb020Year.setText(_translate("scs", "20 year"))
        self.cbSelectAllEvents.setText(_translate("scs", "ALL"))
        self.cb005Year.setText(_translate("scs", "5 year"))
        self.cb020YearCC.setText(_translate("scs", "20 year CC"))
        self.cb050YearCC.setText(_translate("scs", "50 year CC"))
        self.cb010YearCC.setText(_translate("scs", "10 year CC"))
        self.cbSelectAllEventsCC.setText(_translate("scs", "ALL CC"))
        self.cb002Year.setText(_translate("scs", "2 year"))
        self.cb100YearCC.setText(_translate("scs", "100 year CC"))
        self.label_14.setText(_translate("scs", "Depth (mm)"))
        self.label_15.setText(_translate("scs", "Raise (%)"))
        self.cb005YearCC.setText(_translate("scs", "5 year CC"))
        self.mGroupBox_3.setTitle(_translate("scs", "Simulation Settings"))
        self.label_38.setText(_translate("scs", "Input Interval (min)"))
        self.label_40.setText(_translate("scs", "Decimal Spaces"))
        self.label_39.setText(_translate("scs", "Output Interval (min)"))
        self.gbManualApproach.setTitle(_translate("scs", "Manual Approach - Single Catchment"))
        self.cbAreaImp2.setText(_translate("scs", "Area - Impervious 2 (ha)"))
        self.label_16.setText(_translate("scs", "Curve Number Pervious"))
        self.label_19.setText(_translate("scs", "Suffix"))
        self.label_12.setText(_translate("scs", "<html><head/><body><p>Area - Pervious (ha)</p></body></html>"))
        self.label_10.setText(_translate("scs", "Catchment ID"))
        self.label_17.setText(_translate("scs", "Suffix"))
        self.label_18.setText(_translate("scs", "Suffix"))
        self.label_6.setText(_translate("scs", "Area - Impervious 1 (ha)"))
        self.label_35.setText(_translate("scs", "Curve Number Impervious"))
        self.label_22.setText(_translate("scs", "Time of Peak (Tp) and Time of Concentration (Tc)"))
        self.label_4.setText(_translate("scs", "Imp"))
        self.rbTpManual.setText(_translate("scs", "Tp (hr)                              Per"))
        self.rbTcManual.setText(_translate("scs", "Tc (hr)                              Per"))
        self.label_33.setText(_translate("scs", "Imp"))
        self.rbTpTcCalcsManual.setText(_translate("scs", "Calculate Tp / Tc from Catchment Parametes"))
        self.label_2.setText(_translate("scs", "Length (km)"))
        self.label_20.setText(_translate("scs", "Channelisation Factor      Per"))
        self.label_36.setText(_translate("scs", "Imp"))
        self.label_3.setText(_translate("scs", "Slope (m/m)"))
        self.gbGisApproach.setTitle(_translate("scs", "GIS Approach - Single Catchment or Multiple Subcatchments"))
        self.label_9.setText(_translate("scs", "Subcatchments - Polygons Layer"))
        self.label_25.setText(_translate("scs", "Curve Number Pervious Field"))
        self.label_26.setText(_translate("scs", "Subcatchment ID Field"))
        self.label_8.setText(_translate("scs", "Curve Number Impervious Field"))
        self.label_29.setText(_translate("scs", "Area - Impervious 1 Field (ha)"))
        self.label_31.setText(_translate("scs", "Area - Impervious 1 CC Field (ha)"))
        self.cbAreaImp2Gis.setText(_translate("scs", "Area - Impervious 2 Field (ha)"))
        self.label_27.setText(_translate("scs", "Area - Pervious Field (ha)"))
        self.label_30.setText(_translate("scs", "Area - Pervious CC Field (ha)"))
        self.label_5.setText(_translate("scs", "Suffix"))
        self.label_32.setText(_translate("scs", "Suffix"))
        self.label_34.setText(_translate("scs", "Suffix"))
        self.label_21.setText(_translate("scs", "      Area - Impervious 2 CC Field (ha)"))
        self.label_23.setText(_translate("scs", "Time of Peak (Tp) and Time of Concentration (Tc)"))
        self.rbTpTcGis.setText(_translate("scs", "Assign"))
        self.cbTpCheck.setText(_translate("scs", "Tp or"))
        self.cbTcCheck.setText(_translate("scs", "Tc Field"))
        self.rbTpTcCalcsGis.setText(_translate("scs", "Calculate Tp / Tc from Subcatchment Parametes"))
        self.label_24.setText(_translate("scs", "Channelisation Factor Field"))
        self.label_7.setText(_translate("scs", "Slope Field (m/m)"))
        self.label_28.setText(_translate("scs", "Streamline Layer"))
        self.rbDemStreamline.setText(_translate("scs", "DEM (asc, flt, txt)"))
        self.rbLengthSlope.setText(_translate("scs", "Length Field (km)"))
        self.mGroupBox_2.setTitle(_translate("scs", "Output"))
        self.label_11.setText(_translate("scs", "Output Location"))
        self.btnOutput.setText(_translate("scs", "..."))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
