# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SWMM_increment_gpkg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_SIZE_POLICY_PREFERRED, QT_SIZE_POLICY_MINIMUM_EXPANDING, QT_BUTTON_BOX_CANCEL, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_FIXED, QT_BUTTON_BOX_OK, QT_HORIZONTAL


class Ui_Increment_gpkg(object):
    def setupUi(self, Increment_gpkg):
        Increment_gpkg.setObjectName("Increment_gpkg")
        Increment_gpkg.resize(551, 150)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_MINIMUM_EXPANDING, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Increment_gpkg.sizePolicy().hasHeightForWidth())
        Increment_gpkg.setSizePolicy(sizePolicy)
        Increment_gpkg.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Increment_gpkg)
        self.gridLayout.setObjectName("gridLayout")
        self.cbxExistingOptions = QtWidgets.QComboBox(Increment_gpkg)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_FIXED)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxExistingOptions.sizePolicy().hasHeightForWidth())
        self.cbxExistingOptions.setSizePolicy(sizePolicy)
        self.cbxExistingOptions.setObjectName("cbxExistingOptions")
        self.gridLayout.addWidget(self.cbxExistingOptions, 1, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Increment_gpkg)
        self.buttonBox.setOrientation(QT_HORIZONTAL)
        self.buttonBox.setStandardButtons(QT_BUTTON_BOX_CANCEL|QT_BUTTON_BOX_OK)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Increment_gpkg)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_PREFERRED, QT_SIZE_POLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edtOutputFile = QtWidgets.QLineEdit(self.groupBox)
        self.edtOutputFile.setObjectName("edtOutputFile")
        self.gridLayout_2.addWidget(self.edtOutputFile, 0, 1, 1, 1)
        self.btnBrowse = QtWidgets.QToolButton(self.groupBox)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout_2.addWidget(self.btnBrowse, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        self.static_2 = QtWidgets.QLabel(Increment_gpkg)
        self.static_2.setObjectName("static_2")
        self.gridLayout.addWidget(self.static_2, 1, 0, 1, 1)

        self.retranslateUi(Increment_gpkg)
        self.buttonBox.accepted.connect(Increment_gpkg.accept)
        self.buttonBox.rejected.connect(Increment_gpkg.reject)
        QtCore.QMetaObject.connectSlotsByName(Increment_gpkg)

    def retranslateUi(self, Increment_gpkg):
        _translate = QtCore.QCoreApplication.translate
        Increment_gpkg.setWindowTitle(_translate("Increment_gpkg", "Increment SWMM GeoPackage"))
        self.groupBox.setTitle(_translate("Increment_gpkg", "Output File"))
        self.btnBrowse.setText(_translate("Increment_gpkg", "..."))
        self.static_2.setText(_translate("Increment_gpkg", "Existing GeoPackage Layers"))
