# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_filter_sort_TUFLOW_layers.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FilterAndSortLayers(object):
    def setupUi(self, FilterAndSortLayers):
        FilterAndSortLayers.setObjectName("FilterAndSortLayers")
        FilterAndSortLayers.resize(653, 407)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FilterAndSortLayers)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FilterAndSortLayers)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(FilterAndSortLayers)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.rbDemOff = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbDemOff.setText("")
        self.rbDemOff.setObjectName("rbDemOff")
        self.bgDem = QtWidgets.QButtonGroup(FilterAndSortLayers)
        self.bgDem.setObjectName("bgDem")
        self.bgDem.addButton(self.rbDemOff)
        self.horizontalLayout_6.addWidget(self.rbDemOff)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.rbMeshCurrent = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbMeshCurrent.setText("")
        self.rbMeshCurrent.setChecked(True)
        self.rbMeshCurrent.setObjectName("rbMeshCurrent")
        self.bgMesh = QtWidgets.QButtonGroup(FilterAndSortLayers)
        self.bgMesh.setObjectName("bgMesh")
        self.bgMesh.addButton(self.rbMeshCurrent)
        self.horizontalLayout_8.addWidget(self.rbMeshCurrent)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.rbMeshOff = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbMeshOff.setText("")
        self.rbMeshOff.setObjectName("rbMeshOff")
        self.bgMesh.addButton(self.rbMeshOff)
        self.horizontalLayout_9.addWidget(self.rbMeshOff)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.rbCheckCurrent = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbCheckCurrent.setText("")
        self.rbCheckCurrent.setChecked(True)
        self.rbCheckCurrent.setObjectName("rbCheckCurrent")
        self.bgCheck = QtWidgets.QButtonGroup(FilterAndSortLayers)
        self.bgCheck.setObjectName("bgCheck")
        self.bgCheck.addButton(self.rbCheckCurrent)
        self.horizontalLayout_2.addWidget(self.rbCheckCurrent)
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.rbDemOn = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbDemOn.setText("")
        self.rbDemOn.setObjectName("rbDemOn")
        self.bgDem.addButton(self.rbDemOn)
        self.horizontalLayout_4.addWidget(self.rbDemOn)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.rbCheckOn = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbCheckOn.setText("")
        self.rbCheckOn.setObjectName("rbCheckOn")
        self.bgCheck.addButton(self.rbCheckOn)
        self.horizontalLayout.addWidget(self.rbCheckOn)
        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.rbDemCurrent = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbDemCurrent.setText("")
        self.rbDemCurrent.setChecked(True)
        self.rbDemCurrent.setObjectName("rbDemCurrent")
        self.bgDem.addButton(self.rbDemCurrent)
        self.horizontalLayout_5.addWidget(self.rbDemCurrent)
        spacerItem13 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.rbMeshOn = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbMeshOn.setText("")
        self.rbMeshOn.setObjectName("rbMeshOn")
        self.bgMesh.addButton(self.rbMeshOn)
        self.horizontalLayout_7.addWidget(self.rbMeshOn)
        spacerItem15 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.rbCheckOff = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbCheckOff.setText("")
        self.rbCheckOff.setObjectName("rbCheckOff")
        self.bgCheck.addButton(self.rbCheckOff)
        self.horizontalLayout_3.addWidget(self.rbCheckOff)
        spacerItem17 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(FilterAndSortLayers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 2, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 1, 1, 1, 1)
        self.pbFilter = QtWidgets.QPushButton(FilterAndSortLayers)
        self.pbFilter.setObjectName("pbFilter")
        self.gridLayout_2.addWidget(self.pbFilter, 2, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(FilterAndSortLayers)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbSortGlobally = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbSortGlobally.setObjectName("rbSortGlobally")
        self.bgSortOptions = QtWidgets.QButtonGroup(FilterAndSortLayers)
        self.bgSortOptions.setObjectName("bgSortOptions")
        self.bgSortOptions.addButton(self.rbSortGlobally)
        self.gridLayout_3.addWidget(self.rbSortGlobally, 2, 0, 1, 1)
        self.rbSortLocally = QtWidgets.QRadioButton(FilterAndSortLayers)
        self.rbSortLocally.setChecked(True)
        self.rbSortLocally.setObjectName("rbSortLocally")
        self.bgSortOptions.addButton(self.rbSortLocally)
        self.gridLayout_3.addWidget(self.rbSortLocally, 1, 0, 1, 1)
        self.pbSort = QtWidgets.QPushButton(FilterAndSortLayers)
        self.pbSort.setObjectName("pbSort")
        self.gridLayout_3.addWidget(self.pbSort, 1, 1, 2, 1)
        self.label_5 = QtWidgets.QLabel(FilterAndSortLayers)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.pbFinished = QtWidgets.QPushButton(FilterAndSortLayers)
        self.pbFinished.setObjectName("pbFinished")
        self.horizontalLayout_13.addWidget(self.pbFinished)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)

        self.retranslateUi(FilterAndSortLayers)
        QtCore.QMetaObject.connectSlotsByName(FilterAndSortLayers)

    def retranslateUi(self, FilterAndSortLayers):
        _translate = QtCore.QCoreApplication.translate
        FilterAndSortLayers.setWindowTitle(_translate("FilterAndSortLayers", "Filter and/or Sort TUFLOW Layers in current Map Window"))
        self.label.setText(_translate("FilterAndSortLayers", "Select the TUFLOW layer names(s) and/or types to switch ON or OFF in the current Map Window..."))
        self.label_2.setText(_translate("FilterAndSortLayers", "Check Files"))
        self.label_4.setText(_translate("FilterAndSortLayers", "Meshes"))
        self.label_3.setText(_translate("FilterAndSortLayers", "Rasters"))
        self.label_7.setText(_translate("FilterAndSortLayers", "No Change"))
        self.label_6.setText(_translate("FilterAndSortLayers", "ON"))
        self.label_8.setText(_translate("FilterAndSortLayers", "OFF"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FilterAndSortLayers", "Open TUFLOW Types"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FilterAndSortLayers", "ON"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FilterAndSortLayers", "No change"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FilterAndSortLayers", "OFF"))
        self.pbFilter.setText(_translate("FilterAndSortLayers", "Filter Selected Data Types(s)"))
        self.rbSortGlobally.setText(_translate("FilterAndSortLayers", "Remove groups and sort layers globally"))
        self.rbSortLocally.setText(_translate("FilterAndSortLayers", "Keep and sort layers withinin groups"))
        self.pbSort.setText(_translate("FilterAndSortLayers", "Group and Sort TUFLOW Layers"))
        self.label_5.setText(_translate("FilterAndSortLayers", "Sort TUFLOW layers"))
        self.pbFinished.setText(_translate("FilterAndSortLayers", "Finished"))

