# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_map_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapDialog(object):
    def setupUi(self, MapDialog):
        MapDialog.setObjectName("MapDialog")
        MapDialog.resize(652, 545)
        self.verticalLayout = QtWidgets.QVBoxLayout(MapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(MapDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radLayoutDefault = QtWidgets.QRadioButton(self.tab)
        self.radLayoutDefault.setChecked(True)
        self.radLayoutDefault.setObjectName("radLayoutDefault")
        self.buttonGroup = QtWidgets.QButtonGroup(MapDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radLayoutDefault)
        self.verticalLayout_6.addWidget(self.radLayoutDefault)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 591, 1635))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupScaleBar = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupScaleBar.setCheckable(True)
        self.groupScaleBar.setChecked(False)
        self.groupScaleBar.setObjectName("groupScaleBar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupScaleBar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cbScaleBarFrame = QtWidgets.QCheckBox(self.groupScaleBar)
        self.cbScaleBarFrame.setObjectName("cbScaleBarFrame")
        self.gridLayout_8.addWidget(self.cbScaleBarFrame, 2, 0, 1, 3)
        self.cboPosScaleBar = QtWidgets.QComboBox(self.groupScaleBar)
        self.cboPosScaleBar.setObjectName("cboPosScaleBar")
        self.cboPosScaleBar.addItem("")
        self.cboPosScaleBar.addItem("")
        self.cboPosScaleBar.addItem("")
        self.cboPosScaleBar.addItem("")
        self.cboPosScaleBar.addItem("")
        self.cboPosScaleBar.addItem("")
        self.gridLayout_8.addWidget(self.cboPosScaleBar, 3, 1, 1, 1)
        self.cbScaleBarBackground = QtWidgets.QCheckBox(self.groupScaleBar)
        self.cbScaleBarBackground.setObjectName("cbScaleBarBackground")
        self.gridLayout_8.addWidget(self.cbScaleBarBackground, 1, 0, 1, 3)
        self.colorScaleBarBackground = QgsColorButton(self.groupScaleBar)
        self.colorScaleBarBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorScaleBarBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorScaleBarBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorScaleBarBackground.setObjectName("colorScaleBarBackground")
        self.gridLayout_8.addWidget(self.colorScaleBarBackground, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupScaleBar)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 3, 0, 1, 1)
        self.colorScaleBarFrame = QgsColorButton(self.groupScaleBar)
        self.colorScaleBarFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorScaleBarFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorScaleBarFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorScaleBarFrame.setObjectName("colorScaleBarFrame")
        self.gridLayout_8.addWidget(self.colorScaleBarFrame, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupScaleBar)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.fbtnScaleBar = QgsFontButton(self.groupScaleBar)
        self.fbtnScaleBar.setMinimumSize(QtCore.QSize(0, 21))
        self.fbtnScaleBar.setMode(QgsFontButton.ModeQFont)
        self.fbtnScaleBar.setObjectName("fbtnScaleBar")
        self.gridLayout_8.addWidget(self.fbtnScaleBar, 0, 1, 1, 1)
        self.colorScaleBarText = QgsColorButton(self.groupScaleBar)
        self.colorScaleBarText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorScaleBarText.setColor(QtGui.QColor(0, 0, 0))
        self.colorScaleBarText.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorScaleBarText.setObjectName("colorScaleBarText")
        self.gridLayout_8.addWidget(self.colorScaleBarText, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.gridLayout_12.addWidget(self.groupScaleBar, 2, 1, 1, 1)
        self.groupNorthArrow = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupNorthArrow.setCheckable(True)
        self.groupNorthArrow.setChecked(False)
        self.groupNorthArrow.setObjectName("groupNorthArrow")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupNorthArrow)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cbNorthArrowBackground = QtWidgets.QCheckBox(self.groupNorthArrow)
        self.cbNorthArrowBackground.setObjectName("cbNorthArrowBackground")
        self.gridLayout_9.addWidget(self.cbNorthArrowBackground, 0, 0, 1, 3)
        self.label_25 = QtWidgets.QLabel(self.groupNorthArrow)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 2, 0, 1, 1)
        self.colorNorthArrowBackground = QgsColorButton(self.groupNorthArrow)
        self.colorNorthArrowBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorNorthArrowBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorNorthArrowBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorNorthArrowBackground.setObjectName("colorNorthArrowBackground")
        self.gridLayout_9.addWidget(self.colorNorthArrowBackground, 0, 3, 1, 1)
        self.cboPosNorthArrow = QtWidgets.QComboBox(self.groupNorthArrow)
        self.cboPosNorthArrow.setObjectName("cboPosNorthArrow")
        self.cboPosNorthArrow.addItem("")
        self.cboPosNorthArrow.addItem("")
        self.cboPosNorthArrow.addItem("")
        self.cboPosNorthArrow.addItem("")
        self.cboPosNorthArrow.addItem("")
        self.cboPosNorthArrow.addItem("")
        self.gridLayout_9.addWidget(self.cboPosNorthArrow, 2, 1, 1, 1)
        self.cbNorthArrowFrame = QtWidgets.QCheckBox(self.groupNorthArrow)
        self.cbNorthArrowFrame.setObjectName("cbNorthArrowFrame")
        self.gridLayout_9.addWidget(self.cbNorthArrowFrame, 1, 0, 1, 3)
        self.colorNorthArrowFrame = QgsColorButton(self.groupNorthArrow)
        self.colorNorthArrowFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorNorthArrowFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorNorthArrowFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorNorthArrowFrame.setObjectName("colorNorthArrowFrame")
        self.gridLayout_9.addWidget(self.colorNorthArrowFrame, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        self.gridLayout_12.addWidget(self.groupNorthArrow, 3, 1, 1, 1)
        self.groupLegend = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupLegend.setCheckable(True)
        self.groupLegend.setChecked(False)
        self.groupLegend.setObjectName("groupLegend")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupLegend)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.groupLegend)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 4, 0, 1, 1)
        self.colorLegendText = QgsColorButton(self.groupLegend)
        self.colorLegendText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendText.setColor(QtGui.QColor(0, 0, 0))
        self.colorLegendText.setObjectName("colorLegendText")
        self.gridLayout_7.addWidget(self.colorLegendText, 1, 3, 1, 1)
        self.cboPosLegend = QtWidgets.QComboBox(self.groupLegend)
        self.cboPosLegend.setObjectName("cboPosLegend")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.gridLayout_7.addWidget(self.cboPosLegend, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupLegend)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.colorLegendBackground = QgsColorButton(self.groupLegend)
        self.colorLegendBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorLegendBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorLegendBackground.setObjectName("colorLegendBackground")
        self.gridLayout_7.addWidget(self.colorLegendBackground, 2, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupLegend)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.cbLegendBackground = QtWidgets.QCheckBox(self.groupLegend)
        self.cbLegendBackground.setObjectName("cbLegendBackground")
        self.gridLayout_7.addWidget(self.cbLegendBackground, 2, 0, 1, 3)
        self.labelLegend = QtWidgets.QLineEdit(self.groupLegend)
        self.labelLegend.setObjectName("labelLegend")
        self.gridLayout_7.addWidget(self.labelLegend, 0, 1, 1, 3)
        self.fbtnLegend = QgsFontButton(self.groupLegend)
        self.fbtnLegend.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fbtnLegend.setFont(font)
        self.fbtnLegend.setMode(QgsFontButton.ModeQFont)
        self.fbtnLegend.setObjectName("fbtnLegend")
        self.gridLayout_7.addWidget(self.fbtnLegend, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 1, 2, 1, 1)
        self.cbLegendFrame = QtWidgets.QCheckBox(self.groupLegend)
        self.cbLegendFrame.setObjectName("cbLegendFrame")
        self.gridLayout_7.addWidget(self.cbLegendFrame, 3, 0, 1, 3)
        self.colorLegendFrame = QgsColorButton(self.groupLegend)
        self.colorLegendFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorLegendFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorLegendFrame.setObjectName("colorLegendFrame")
        self.gridLayout_7.addWidget(self.colorLegendFrame, 3, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.gridLayout_12.addWidget(self.groupLegend, 1, 1, 1, 1)
        self.groupPlot = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupPlot.setCheckable(True)
        self.groupPlot.setChecked(False)
        self.groupPlot.setCollapsed(False)
        self.groupPlot.setObjectName("groupPlot")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupPlot)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnPlotUp = QtWidgets.QToolButton(self.groupPlot)
        self.btnPlotUp.setObjectName("btnPlotUp")
        self.gridLayout_5.addWidget(self.btnPlotUp, 0, 2, 1, 1)
        self.btnAddPlot = QtWidgets.QToolButton(self.groupPlot)
        self.btnAddPlot.setObjectName("btnAddPlot")
        self.gridLayout_5.addWidget(self.btnAddPlot, 0, 0, 1, 1)
        self.btnRemovePlot = QtWidgets.QToolButton(self.groupPlot)
        self.btnRemovePlot.setObjectName("btnRemovePlot")
        self.gridLayout_5.addWidget(self.btnRemovePlot, 0, 1, 1, 1)
        self.tablePlots = QtWidgets.QTableWidget(self.groupPlot)
        self.tablePlots.setMinimumSize(QtCore.QSize(0, 150))
        self.tablePlots.setObjectName("tablePlots")
        self.tablePlots.setColumnCount(4)
        self.tablePlots.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(3, item)
        self.tablePlots.horizontalHeader().setVisible(False)
        self.tablePlots.horizontalHeader().setCascadingSectionResizes(False)
        self.tablePlots.horizontalHeader().setDefaultSectionSize(110)
        self.tablePlots.horizontalHeader().setMinimumSectionSize(80)
        self.tablePlots.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_5.addWidget(self.tablePlots, 1, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 4, 1, 1)
        self.btnPlotDown = QtWidgets.QToolButton(self.groupPlot)
        self.btnPlotDown.setObjectName("btnPlotDown")
        self.gridLayout_5.addWidget(self.btnPlotDown, 0, 3, 1, 1)
        self.tableGraphics = QtWidgets.QTableWidget(self.groupPlot)
        self.tableGraphics.setMinimumSize(QtCore.QSize(0, 150))
        self.tableGraphics.setObjectName("tableGraphics")
        self.tableGraphics.setColumnCount(4)
        self.tableGraphics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(3, item)
        self.tableGraphics.horizontalHeader().setVisible(False)
        self.tableGraphics.horizontalHeader().setDefaultSectionSize(110)
        self.tableGraphics.verticalHeader().setDefaultSectionSize(20)
        self.tableGraphics.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_5.addWidget(self.tableGraphics, 3, 0, 1, 5)
        self.label_28 = QtWidgets.QLabel(self.groupPlot)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 5)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.gridLayout_12.addWidget(self.groupPlot, 5, 1, 1, 1)
        self.groupLabel = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupLabel.setCheckable(True)
        self.groupLabel.setChecked(False)
        self.groupLabel.setObjectName("groupLabel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupLabel)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.fbtnLabel = QgsFontButton(self.groupLabel)
        self.fbtnLabel.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fbtnLabel.setFont(font)
        self.fbtnLabel.setMode(QgsFontButton.ModeQFont)
        self.fbtnLabel.setObjectName("fbtnLabel")
        self.gridLayout_10.addWidget(self.fbtnLabel, 1, 1, 1, 1)
        self.colorLabelBackground = QgsColorButton(self.groupLabel)
        self.colorLabelBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLabelBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorLabelBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorLabelBackground.setObjectName("colorLabelBackground")
        self.gridLayout_10.addWidget(self.colorLabelBackground, 2, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupLabel)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 4, 0, 1, 1)
        self.cbLabelBackground = QtWidgets.QCheckBox(self.groupLabel)
        self.cbLabelBackground.setObjectName("cbLabelBackground")
        self.gridLayout_10.addWidget(self.cbLabelBackground, 2, 0, 1, 3)
        self.colorLabelText = QgsColorButton(self.groupLabel)
        self.colorLabelText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLabelText.setColor(QtGui.QColor(0, 0, 0))
        self.colorLabelText.setObjectName("colorLabelText")
        self.gridLayout_10.addWidget(self.colorLabelText, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupLabel)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupLabel)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 1, 2, 1, 1)
        self.labelInput = QtWidgets.QTextEdit(self.groupLabel)
        self.labelInput.setObjectName("labelInput")
        self.gridLayout_10.addWidget(self.labelInput, 0, 1, 1, 2)
        self.cboPosLabel = QtWidgets.QComboBox(self.groupLabel)
        self.cboPosLabel.setObjectName("cboPosLabel")
        self.cboPosLabel.addItem("")
        self.cboPosLabel.addItem("")
        self.cboPosLabel.addItem("")
        self.cboPosLabel.addItem("")
        self.cboPosLabel.addItem("")
        self.cboPosLabel.addItem("")
        self.gridLayout_10.addWidget(self.cboPosLabel, 4, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pbMapNo = QtWidgets.QPushButton(self.groupLabel)
        self.pbMapNo.setObjectName("pbMapNo")
        self.gridLayout_4.addWidget(self.pbMapNo, 0, 0, 1, 1)
        self.pbResultType = QtWidgets.QPushButton(self.groupLabel)
        self.pbResultType.setObjectName("pbResultType")
        self.gridLayout_4.addWidget(self.pbResultType, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 5, 0, 1, 1)
        self.pbWorkspaceLoc = QtWidgets.QPushButton(self.groupLabel)
        self.pbWorkspaceLoc.setObjectName("pbWorkspaceLoc")
        self.gridLayout_4.addWidget(self.pbWorkspaceLoc, 4, 0, 1, 1)
        self.pbResultName = QtWidgets.QPushButton(self.groupLabel)
        self.pbResultName.setObjectName("pbResultName")
        self.gridLayout_4.addWidget(self.pbResultName, 1, 0, 1, 1)
        self.pbDate = QtWidgets.QPushButton(self.groupLabel)
        self.pbDate.setObjectName("pbDate")
        self.gridLayout_4.addWidget(self.pbDate, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 3, 1, 1)
        self.cbLabelFrame = QtWidgets.QCheckBox(self.groupLabel)
        self.cbLabelFrame.setObjectName("cbLabelFrame")
        self.gridLayout_10.addWidget(self.cbLabelFrame, 3, 0, 1, 3)
        self.colorLabelFrame = QgsColorButton(self.groupLabel)
        self.colorLabelFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLabelFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorLabelFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorLabelFrame.setObjectName("colorLabelFrame")
        self.gridLayout_10.addWidget(self.colorLabelFrame, 3, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_10)
        self.gridLayout_12.addWidget(self.groupLabel, 4, 1, 1, 1)
        self.groupImages = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupImages.setCheckable(True)
        self.groupImages.setChecked(False)
        self.groupImages.setCollapsed(False)
        self.groupImages.setObjectName("groupImages")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupImages)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnImageUp = QtWidgets.QToolButton(self.groupImages)
        self.btnImageUp.setObjectName("btnImageUp")
        self.gridLayout_6.addWidget(self.btnImageUp, 0, 2, 1, 1)
        self.btnRemoveImage = QtWidgets.QToolButton(self.groupImages)
        self.btnRemoveImage.setObjectName("btnRemoveImage")
        self.gridLayout_6.addWidget(self.btnRemoveImage, 0, 1, 1, 1)
        self.btnAddImage = QtWidgets.QToolButton(self.groupImages)
        self.btnAddImage.setObjectName("btnAddImage")
        self.gridLayout_6.addWidget(self.btnAddImage, 0, 0, 1, 1)
        self.btnImageDown = QtWidgets.QToolButton(self.groupImages)
        self.btnImageDown.setObjectName("btnImageDown")
        self.gridLayout_6.addWidget(self.btnImageDown, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 4, 1, 1)
        self.tableImages = QtWidgets.QTableWidget(self.groupImages)
        self.tableImages.setMinimumSize(QtCore.QSize(0, 150))
        self.tableImages.setObjectName("tableImages")
        self.tableImages.setColumnCount(3)
        self.tableImages.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(2, item)
        self.tableImages.horizontalHeader().setDefaultSectionSize(130)
        self.tableImages.horizontalHeader().setMinimumSectionSize(39)
        self.tableImages.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_6.addWidget(self.tableImages, 1, 0, 1, 5)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.gridLayout_12.addWidget(self.groupImages, 6, 1, 1, 1)
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox.setCollapsed(False)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.mGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sbHeight = QtWidgets.QDoubleSpinBox(self.mGroupBox)
        self.sbHeight.setMinimumSize(QtCore.QSize(150, 0))
        self.sbHeight.setMinimum(1.0)
        self.sbHeight.setMaximum(99999.0)
        self.sbHeight.setObjectName("sbHeight")
        self.gridLayout_2.addWidget(self.sbHeight, 1, 0, 1, 1)
        self.sbWidth = QtWidgets.QDoubleSpinBox(self.mGroupBox)
        self.sbWidth.setMinimumSize(QtCore.QSize(150, 0))
        self.sbWidth.setMinimum(1.0)
        self.sbWidth.setMaximum(99999.0)
        self.sbWidth.setObjectName("sbWidth")
        self.gridLayout_2.addWidget(self.sbWidth, 0, 0, 1, 1)
        self.cboUnits = QtWidgets.QComboBox(self.mGroupBox)
        self.cboUnits.setObjectName("cboUnits")
        self.cboUnits.addItem("")
        self.cboUnits.addItem("")
        self.gridLayout_2.addWidget(self.cboUnits, 0, 1, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.mGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.cboPageSize = QtWidgets.QComboBox(self.mGroupBox)
        self.cboPageSize.setObjectName("cboPageSize")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.cboPageSize.addItem("")
        self.gridLayout.addWidget(self.cboPageSize, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.mGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.mGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.cboOrientation = QtWidgets.QComboBox(self.mGroupBox)
        self.cboOrientation.setObjectName("cboOrientation")
        self.cboOrientation.addItem("")
        self.cboOrientation.addItem("")
        self.gridLayout.addWidget(self.cboOrientation, 3, 1, 1, 1)
        self.sbDpi = QtWidgets.QSpinBox(self.mGroupBox)
        self.sbDpi.setMinimum(1)
        self.sbDpi.setMaximum(99999)
        self.sbDpi.setProperty("value", 300)
        self.sbDpi.setObjectName("sbDpi")
        self.gridLayout.addWidget(self.sbDpi, 4, 1, 1, 1)
        self.sbPageFrameThickness = QtWidgets.QDoubleSpinBox(self.mGroupBox)
        self.sbPageFrameThickness.setDecimals(1)
        self.sbPageFrameThickness.setMinimum(0.1)
        self.sbPageFrameThickness.setProperty("value", 0.3)
        self.sbPageFrameThickness.setObjectName("sbPageFrameThickness")
        self.gridLayout.addWidget(self.sbPageFrameThickness, 5, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.mGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.cbPageFrame = QtWidgets.QCheckBox(self.mGroupBox)
        self.cbPageFrame.setObjectName("cbPageFrame")
        self.gridLayout.addWidget(self.cbPageFrame, 5, 0, 1, 2)
        self.colorPageFrame = QgsColorButton(self.mGroupBox)
        self.colorPageFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorPageFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorPageFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorPageFrame.setObjectName("colorPageFrame")
        self.gridLayout.addWidget(self.colorPageFrame, 5, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.mGroupBox)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.sbPageMarginTop = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbPageMarginTop.setDecimals(1)
        self.sbPageMarginTop.setProperty("value", 10.0)
        self.sbPageMarginTop.setObjectName("sbPageMarginTop")
        self.gridLayout_13.addWidget(self.sbPageMarginTop, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 1, 0, 1, 1)
        self.sbPageMarginLeft = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbPageMarginLeft.setDecimals(1)
        self.sbPageMarginLeft.setProperty("value", 10.0)
        self.sbPageMarginLeft.setObjectName("sbPageMarginLeft")
        self.gridLayout_13.addWidget(self.sbPageMarginLeft, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 2, 1, 1, 1)
        self.sbPageMarginBottom = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbPageMarginBottom.setDecimals(1)
        self.sbPageMarginBottom.setProperty("value", 10.0)
        self.sbPageMarginBottom.setObjectName("sbPageMarginBottom")
        self.gridLayout_13.addWidget(self.sbPageMarginBottom, 2, 2, 1, 1)
        self.sbPageMarginRight = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbPageMarginRight.setDecimals(1)
        self.sbPageMarginRight.setProperty("value", 10.0)
        self.sbPageMarginRight.setObjectName("sbPageMarginRight")
        self.gridLayout_13.addWidget(self.sbPageMarginRight, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 6, 0, 1, 5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 2, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_12.addWidget(self.mGroupBox, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem9, 0, 0, 3, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.radLayoutCustom = QtWidgets.QRadioButton(self.tab)
        self.radLayoutCustom.setChecked(False)
        self.radLayoutCustom.setObjectName("radLayoutCustom")
        self.buttonGroup.addButton(self.radLayoutCustom)
        self.verticalLayout_6.addWidget(self.radLayoutCustom)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnBrowseTemplate = QtWidgets.QToolButton(self.tab)
        self.btnBrowseTemplate.setObjectName("btnBrowseTemplate")
        self.gridLayout_11.addWidget(self.btnBrowseTemplate, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 1, 1, 1)
        self.editTemplate = QtWidgets.QLineEdit(self.tab)
        self.editTemplate.setObjectName("editTemplate")
        self.gridLayout_11.addWidget(self.editTemplate, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 1, 1, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 0, 0, 2, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_11)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnMapDown = QtWidgets.QToolButton(self.tab_2)
        self.btnMapDown.setObjectName("btnMapDown")
        self.gridLayout_3.addWidget(self.btnMapDown, 2, 3, 1, 1)
        self.btnAddMap = QtWidgets.QToolButton(self.tab_2)
        self.btnAddMap.setObjectName("btnAddMap")
        self.gridLayout_3.addWidget(self.btnAddMap, 2, 0, 1, 1)
        self.btnRemoveMap = QtWidgets.QToolButton(self.tab_2)
        self.btnRemoveMap.setObjectName("btnRemoveMap")
        self.gridLayout_3.addWidget(self.btnRemoveMap, 2, 1, 1, 1)
        self.btnMapUp = QtWidgets.QToolButton(self.tab_2)
        self.btnMapUp.setObjectName("btnMapUp")
        self.gridLayout_3.addWidget(self.btnMapUp, 2, 2, 1, 1)
        self.tableMaps = QtWidgets.QTableWidget(self.tab_2)
        self.tableMaps.setMinimumSize(QtCore.QSize(0, 300))
        self.tableMaps.setObjectName("tableMaps")
        self.tableMaps.setColumnCount(5)
        self.tableMaps.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMaps.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMaps.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMaps.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMaps.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMaps.setHorizontalHeaderItem(4, item)
        self.tableMaps.horizontalHeader().setDefaultSectionSize(120)
        self.tableMaps.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_3.addWidget(self.tableMaps, 3, 0, 1, 6)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 4)
        self.cbSaveTemplates = QtWidgets.QCheckBox(self.tab_2)
        self.cbSaveTemplates.setObjectName("cbSaveTemplates")
        self.gridLayout_3.addWidget(self.cbSaveTemplates, 0, 0, 1, 4)
        self.leTemplateOut = QtWidgets.QLineEdit(self.tab_2)
        self.leTemplateOut.setObjectName("leTemplateOut")
        self.gridLayout_3.addWidget(self.leTemplateOut, 0, 5, 1, 1)
        self.btnBrowseTemplateOut = QtWidgets.QToolButton(self.tab_2)
        self.btnBrowseTemplateOut.setObjectName("btnBrowseTemplateOut")
        self.gridLayout_3.addWidget(self.btnBrowseTemplateOut, 0, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 2, 4, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progress = QtWidgets.QProgressBar(MapDialog)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.horizontalLayout_4.addWidget(self.progress)
        self.pbPreview = QtWidgets.QPushButton(MapDialog)
        self.pbPreview.setObjectName("pbPreview")
        self.horizontalLayout_4.addWidget(self.pbPreview)
        self.buttonBox = QtWidgets.QDialogButtonBox(MapDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(MapDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cboPageSize.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MapDialog)

    def retranslateUi(self, MapDialog):
        _translate = QtCore.QCoreApplication.translate
        MapDialog.setWindowTitle(_translate("MapDialog", "Export Maps"))
        self.radLayoutDefault.setText(_translate("MapDialog", "Default Layout"))
        self.groupScaleBar.setTitle(_translate("MapDialog", "Scale Bar"))
        self.cbScaleBarFrame.setText(_translate("MapDialog", "Border"))
        self.cboPosScaleBar.setItemText(0, _translate("MapDialog", "Top-Left"))
        self.cboPosScaleBar.setItemText(1, _translate("MapDialog", "Top-Right"))
        self.cboPosScaleBar.setItemText(2, _translate("MapDialog", "Bottom-Left"))
        self.cboPosScaleBar.setItemText(3, _translate("MapDialog", "Bottom-Right"))
        self.cboPosScaleBar.setItemText(4, _translate("MapDialog", "Top-Center"))
        self.cboPosScaleBar.setItemText(5, _translate("MapDialog", "Bottom-Center"))
        self.cbScaleBarBackground.setText(_translate("MapDialog", "Background"))
        self.label_24.setText(_translate("MapDialog", "Position"))
        self.label_8.setText(_translate("MapDialog", "Text"))
        self.groupNorthArrow.setTitle(_translate("MapDialog", "North Arrow"))
        self.cbNorthArrowBackground.setText(_translate("MapDialog", "Background"))
        self.label_25.setText(_translate("MapDialog", "Position"))
        self.cboPosNorthArrow.setItemText(0, _translate("MapDialog", "Top-Left"))
        self.cboPosNorthArrow.setItemText(1, _translate("MapDialog", "Top-Right"))
        self.cboPosNorthArrow.setItemText(2, _translate("MapDialog", "Bottom-Left"))
        self.cboPosNorthArrow.setItemText(3, _translate("MapDialog", "Bottom-Right"))
        self.cboPosNorthArrow.setItemText(4, _translate("MapDialog", "Top-Center"))
        self.cboPosNorthArrow.setItemText(5, _translate("MapDialog", "Bottom-Center"))
        self.cbNorthArrowFrame.setText(_translate("MapDialog", "Border"))
        self.groupLegend.setTitle(_translate("MapDialog", "Legend"))
        self.label_22.setText(_translate("MapDialog", "Position"))
        self.cboPosLegend.setItemText(0, _translate("MapDialog", "Top-Left"))
        self.cboPosLegend.setItemText(1, _translate("MapDialog", "Top-Right"))
        self.cboPosLegend.setItemText(2, _translate("MapDialog", "Bottom-Left"))
        self.cboPosLegend.setItemText(3, _translate("MapDialog", "Bottom-Right"))
        self.cboPosLegend.setItemText(4, _translate("MapDialog", "Top-Center"))
        self.cboPosLegend.setItemText(5, _translate("MapDialog", "Bottom-Center"))
        self.label_20.setText(_translate("MapDialog", "Label"))
        self.label_21.setText(_translate("MapDialog", "Text"))
        self.cbLegendBackground.setText(_translate("MapDialog", "Background"))
        self.fbtnLegend.setText(_translate("MapDialog", "Font . . ."))
        self.cbLegendFrame.setText(_translate("MapDialog", "Border"))
        self.groupPlot.setTitle(_translate("MapDialog", "Plots"))
        self.btnPlotUp.setText(_translate("MapDialog", "..."))
        self.btnAddPlot.setText(_translate("MapDialog", "..."))
        self.btnRemovePlot.setText(_translate("MapDialog", "..."))
        item = self.tablePlots.horizontalHeaderItem(0)
        item.setText(_translate("MapDialog", "Plot Type"))
        item = self.tablePlots.horizontalHeaderItem(1)
        item.setText(_translate("MapDialog", "Plot Items"))
        item = self.tablePlots.horizontalHeaderItem(2)
        item.setText(_translate("MapDialog", "Position"))
        item = self.tablePlots.horizontalHeaderItem(3)
        item.setText(_translate("MapDialog", "Properties"))
        self.btnPlotDown.setText(_translate("MapDialog", "..."))
        item = self.tableGraphics.horizontalHeaderItem(0)
        item.setText(_translate("MapDialog", "ID"))
        item = self.tableGraphics.horizontalHeaderItem(1)
        item.setText(_translate("MapDialog", "User Label"))
        item = self.tableGraphics.horizontalHeaderItem(2)
        item.setText(_translate("MapDialog", "Label Position"))
        item = self.tableGraphics.horizontalHeaderItem(3)
        item.setText(_translate("MapDialog", "Properties"))
        self.label_28.setText(_translate("MapDialog", "Graphics"))
        self.groupLabel.setTitle(_translate("MapDialog", "Label"))
        self.fbtnLabel.setText(_translate("MapDialog", "Font . . ."))
        self.label_26.setText(_translate("MapDialog", "Position"))
        self.cbLabelBackground.setText(_translate("MapDialog", "Background"))
        self.label_23.setText(_translate("MapDialog", "Label"))
        self.label_27.setText(_translate("MapDialog", "Text"))
        self.cboPosLabel.setItemText(0, _translate("MapDialog", "Top-Left"))
        self.cboPosLabel.setItemText(1, _translate("MapDialog", "Top-Right"))
        self.cboPosLabel.setItemText(2, _translate("MapDialog", "Bottom-Left"))
        self.cboPosLabel.setItemText(3, _translate("MapDialog", "Bottom-Right"))
        self.cboPosLabel.setItemText(4, _translate("MapDialog", "Top-Center"))
        self.cboPosLabel.setItemText(5, _translate("MapDialog", "Bottom-Center"))
        self.pbMapNo.setText(_translate("MapDialog", "Dynamic Map Number"))
        self.pbResultType.setText(_translate("MapDialog", "Dynamic Result Type"))
        self.pbWorkspaceLoc.setText(_translate("MapDialog", "Dynamic Workspace Location"))
        self.pbResultName.setText(_translate("MapDialog", "Dynamic Result Name"))
        self.pbDate.setText(_translate("MapDialog", "Dynamic Date"))
        self.cbLabelFrame.setText(_translate("MapDialog", "Border"))
        self.groupImages.setTitle(_translate("MapDialog", "Images"))
        self.btnImageUp.setText(_translate("MapDialog", "..."))
        self.btnRemoveImage.setText(_translate("MapDialog", "..."))
        self.btnAddImage.setText(_translate("MapDialog", "..."))
        self.btnImageDown.setText(_translate("MapDialog", "..."))
        item = self.tableImages.horizontalHeaderItem(0)
        item.setText(_translate("MapDialog", "Image"))
        item = self.tableImages.horizontalHeaderItem(1)
        item.setText(_translate("MapDialog", "Position"))
        item = self.tableImages.horizontalHeaderItem(2)
        item.setText(_translate("MapDialog", "Properties"))
        self.mGroupBox.setTitle(_translate("MapDialog", "Page Properties"))
        self.label_6.setText(_translate("MapDialog", "Page Size"))
        self.cboUnits.setItemText(0, _translate("MapDialog", "mm"))
        self.cboUnits.setItemText(1, _translate("MapDialog", "inch"))
        self.label_2.setText(_translate("MapDialog", "Height"))
        self.label.setText(_translate("MapDialog", "Width"))
        self.cboPageSize.setItemText(0, _translate("MapDialog", "A0"))
        self.cboPageSize.setItemText(1, _translate("MapDialog", "A1"))
        self.cboPageSize.setItemText(2, _translate("MapDialog", "A2"))
        self.cboPageSize.setItemText(3, _translate("MapDialog", "A3"))
        self.cboPageSize.setItemText(4, _translate("MapDialog", "A4"))
        self.cboPageSize.setItemText(5, _translate("MapDialog", "A5"))
        self.cboPageSize.setItemText(6, _translate("MapDialog", "A6"))
        self.cboPageSize.setItemText(7, _translate("MapDialog", "B0"))
        self.cboPageSize.setItemText(8, _translate("MapDialog", "B1"))
        self.cboPageSize.setItemText(9, _translate("MapDialog", "B2"))
        self.cboPageSize.setItemText(10, _translate("MapDialog", "B3"))
        self.cboPageSize.setItemText(11, _translate("MapDialog", "B4"))
        self.cboPageSize.setItemText(12, _translate("MapDialog", "B5"))
        self.cboPageSize.setItemText(13, _translate("MapDialog", "B6"))
        self.cboPageSize.setItemText(14, _translate("MapDialog", "Legal"))
        self.cboPageSize.setItemText(15, _translate("MapDialog", "Letter"))
        self.cboPageSize.setItemText(16, _translate("MapDialog", "ANSI A"))
        self.cboPageSize.setItemText(17, _translate("MapDialog", "ANSI B"))
        self.cboPageSize.setItemText(18, _translate("MapDialog", "ANSI C"))
        self.cboPageSize.setItemText(19, _translate("MapDialog", "ANSI D"))
        self.cboPageSize.setItemText(20, _translate("MapDialog", "ANSI E"))
        self.cboPageSize.setItemText(21, _translate("MapDialog", "Arch A"))
        self.cboPageSize.setItemText(22, _translate("MapDialog", "Arch B"))
        self.cboPageSize.setItemText(23, _translate("MapDialog", "Arch C"))
        self.cboPageSize.setItemText(24, _translate("MapDialog", "Arch D"))
        self.cboPageSize.setItemText(25, _translate("MapDialog", "Arch E"))
        self.cboPageSize.setItemText(26, _translate("MapDialog", "Arch E1"))
        self.cboPageSize.setItemText(27, _translate("MapDialog", "Arch E2"))
        self.cboPageSize.setItemText(28, _translate("MapDialog", "Arch E3"))
        self.cboPageSize.setItemText(29, _translate("MapDialog", "Custom"))
        self.label_7.setText(_translate("MapDialog", "Orientation"))
        self.label_4.setText(_translate("MapDialog", "dpi"))
        self.cboOrientation.setItemText(0, _translate("MapDialog", "Portrait"))
        self.cboOrientation.setItemText(1, _translate("MapDialog", "Landscape"))
        self.label_9.setText(_translate("MapDialog", "Thickness (mm)"))
        self.cbPageFrame.setText(_translate("MapDialog", "Page Border"))
        self.groupBox.setTitle(_translate("MapDialog", "Page Margins"))
        self.label_11.setText(_translate("MapDialog", "Top"))
        self.label_12.setText(_translate("MapDialog", "Left"))
        self.label_14.setText(_translate("MapDialog", "Bottom"))
        self.label_13.setText(_translate("MapDialog", "Right"))
        self.radLayoutCustom.setText(_translate("MapDialog", "Custom layout (QGIS Print Layout.qpt)"))
        self.btnBrowseTemplate.setText(_translate("MapDialog", "..."))
        self.label_5.setText(_translate("MapDialog", "Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MapDialog", "Layout"))
        self.btnMapDown.setText(_translate("MapDialog", "..."))
        self.btnAddMap.setText(_translate("MapDialog", "..."))
        self.btnRemoveMap.setText(_translate("MapDialog", "..."))
        self.btnMapUp.setText(_translate("MapDialog", "..."))
        item = self.tableMaps.horizontalHeaderItem(0)
        item.setText(_translate("MapDialog", "Result"))
        item = self.tableMaps.horizontalHeaderItem(1)
        item.setText(_translate("MapDialog", "Scalar Type"))
        item = self.tableMaps.horizontalHeaderItem(2)
        item.setText(_translate("MapDialog", "Vector Type"))
        item = self.tableMaps.horizontalHeaderItem(3)
        item.setText(_translate("MapDialog", "Time"))
        item = self.tableMaps.horizontalHeaderItem(4)
        item.setText(_translate("MapDialog", "Output"))
        self.label_3.setText(_translate("MapDialog", "Maps"))
        self.cbSaveTemplates.setText(_translate("MapDialog", "Save Templates"))
        self.btnBrowseTemplateOut.setText(_translate("MapDialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MapDialog", "Export Maps"))
        self.progress.setFormat(_translate("MapDialog", "Completed %v of %m"))
        self.pbPreview.setText(_translate("MapDialog", "Preview"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgscolorbutton import QgsColorButton
from qgsfontbutton import QgsFontButton
