# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_NullGeometryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NullGeometryConfirmation(object):
    def setupUi(self, NullGeometryConfirmation):
        NullGeometryConfirmation.setObjectName("NullGeometryConfirmation")
        NullGeometryConfirmation.resize(452, 353)
        self.verticalLayout = QtWidgets.QVBoxLayout(NullGeometryConfirmation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.teNullGeometry = QtWidgets.QTextBrowser(NullGeometryConfirmation)
        self.teNullGeometry.setObjectName("teNullGeometry")
        self.verticalLayout.addWidget(self.teNullGeometry)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbCancel = QtWidgets.QPushButton(NullGeometryConfirmation)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.pbConfirm = QtWidgets.QPushButton(NullGeometryConfirmation)
        self.pbConfirm.setObjectName("pbConfirm")
        self.horizontalLayout.addWidget(self.pbConfirm)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NullGeometryConfirmation)
        QtCore.QMetaObject.connectSlotsByName(NullGeometryConfirmation)

    def retranslateUi(self, NullGeometryConfirmation):
        _translate = QtCore.QCoreApplication.translate
        NullGeometryConfirmation.setWindowTitle(_translate("NullGeometryConfirmation", "Empty Geometries"))
        self.pbCancel.setText(_translate("NullGeometryConfirmation", "Cancel"))
        self.pbConfirm.setText(_translate("NullGeometryConfirmation", "Confirm Delete"))
