# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_replace_features.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_FORM_LAYOUT_FIELD_ROLE, QT_BUTTON_BOX_CANCEL, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM, QT_BUTTON_BOX_OK, QT_FORM_LAYOUT_LABEL_ROLE, QT_HORIZONTAL


class Ui_dlg_features_from_layer(object):
    def setupUi(self, dlg_features_from_layer):
        dlg_features_from_layer.setObjectName("dlg_features_from_layer")
        dlg_features_from_layer.resize(399, 75)
        sizePolicy = QtWidgets.QSizePolicy(QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_MINIMUM)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlg_features_from_layer.sizePolicy().hasHeightForWidth())
        dlg_features_from_layer.setSizePolicy(sizePolicy)
        dlg_features_from_layer.setSizeGripEnabled(True)
        self.formLayout = QtWidgets.QFormLayout(dlg_features_from_layer)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(dlg_features_from_layer)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QT_FORM_LAYOUT_LABEL_ROLE, self.label)
        self.comboBox = QtWidgets.QComboBox(dlg_features_from_layer)
        self.comboBox.setMinimumContentsLength(30)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QT_FORM_LAYOUT_FIELD_ROLE, self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.formLayout.setItem(2, QT_FORM_LAYOUT_LABEL_ROLE, spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlg_features_from_layer)
        self.buttonBox.setOrientation(QT_HORIZONTAL)
        self.buttonBox.setStandardButtons(QT_BUTTON_BOX_CANCEL|QT_BUTTON_BOX_OK)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QT_FORM_LAYOUT_FIELD_ROLE, self.buttonBox)

        self.retranslateUi(dlg_features_from_layer)
        self.buttonBox.accepted.connect(dlg_features_from_layer.accept)
        self.buttonBox.rejected.connect(dlg_features_from_layer.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_features_from_layer)

    def retranslateUi(self, dlg_features_from_layer):
        _translate = QtCore.QCoreApplication.translate
        dlg_features_from_layer.setWindowTitle(_translate("dlg_features_from_layer", "Replace Features From Layer"))
        self.label.setText(_translate("dlg_features_from_layer", "Source Layer"))
