# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_tuflowqgis_import_empties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tuflowqgis_import_empty(object):
    def setupUi(self, tuflowqgis_import_empty):
        tuflowqgis_import_empty.setObjectName("tuflowqgis_import_empty")
        tuflowqgis_import_empty.setWindowModality(QtCore.Qt.ApplicationModal)
        tuflowqgis_import_empty.setEnabled(True)
        tuflowqgis_import_empty.resize(729, 518)
        tuflowqgis_import_empty.setMouseTracking(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(tuflowqgis_import_empty)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(tuflowqgis_import_empty)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 4)
        self.label1 = QtWidgets.QLabel(tuflowqgis_import_empty)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkPoint = QtWidgets.QCheckBox(tuflowqgis_import_empty)
        self.checkPoint.setObjectName("checkPoint")
        self.horizontalLayout.addWidget(self.checkPoint)
        self.checkLine = QtWidgets.QCheckBox(tuflowqgis_import_empty)
        self.checkLine.setObjectName("checkLine")
        self.horizontalLayout.addWidget(self.checkLine)
        self.checkRegion = QtWidgets.QCheckBox(tuflowqgis_import_empty)
        self.checkRegion.setObjectName("checkRegion")
        self.horizontalLayout.addWidget(self.checkRegion)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 4)
        self.emptydir = QtWidgets.QLineEdit(tuflowqgis_import_empty)
        self.emptydir.setMinimumSize(QtCore.QSize(250, 0))
        self.emptydir.setReadOnly(False)
        self.emptydir.setObjectName("emptydir")
        self.gridLayout.addWidget(self.emptydir, 1, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(tuflowqgis_import_empty)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 0, 1, 1)
        self.txtRunID = QtWidgets.QLineEdit(tuflowqgis_import_empty)
        self.txtRunID.setReadOnly(False)
        self.txtRunID.setObjectName("txtRunID")
        self.gridLayout.addWidget(self.txtRunID, 5, 0, 1, 4)
        self.label3 = QtWidgets.QLabel(tuflowqgis_import_empty)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 4, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(tuflowqgis_import_empty)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 6, 0, 1, 1)
        self.emptyType = QtWidgets.QListWidget(tuflowqgis_import_empty)
        self.emptyType.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.emptyType.setObjectName("emptyType")
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.emptyType.addItem(item)
        self.gridLayout.addWidget(self.emptyType, 3, 0, 1, 4)
        self.browsedir = QtWidgets.QPushButton(tuflowqgis_import_empty)
        self.browsedir.setObjectName("browsedir")
        self.gridLayout.addWidget(self.browsedir, 1, 1, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbHideToolTip = QtWidgets.QPushButton(tuflowqgis_import_empty)
        self.pbHideToolTip.setObjectName("pbHideToolTip")
        self.horizontalLayout_2.addWidget(self.pbHideToolTip)
        self.pbShowToolTip = QtWidgets.QPushButton(tuflowqgis_import_empty)
        self.pbShowToolTip.setObjectName("pbShowToolTip")
        self.horizontalLayout_2.addWidget(self.pbShowToolTip)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.teToolTip = QtWidgets.QTextBrowser(tuflowqgis_import_empty)
        self.teToolTip.setOpenExternalLinks(True)
        self.teToolTip.setObjectName("teToolTip")
        self.gridLayout_2.addWidget(self.teToolTip, 0, 1, 1, 1)

        self.retranslateUi(tuflowqgis_import_empty)
        self.buttonBox.accepted.connect(tuflowqgis_import_empty.accept)
        self.buttonBox.rejected.connect(tuflowqgis_import_empty.reject)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_import_empty)

    def retranslateUi(self, tuflowqgis_import_empty):
        _translate = QtCore.QCoreApplication.translate
        tuflowqgis_import_empty.setWindowTitle(_translate("tuflowqgis_import_empty", "Import TUFLOW Empty File"))
        self.label1.setText(_translate("tuflowqgis_import_empty", "Empty Directory"))
        self.checkPoint.setText(_translate("tuflowqgis_import_empty", "Points"))
        self.checkLine.setText(_translate("tuflowqgis_import_empty", "Lines"))
        self.checkRegion.setText(_translate("tuflowqgis_import_empty", "Regions"))
        self.emptydir.setText(_translate("tuflowqgis_import_empty", "<directory>"))
        self.label2.setText(_translate("tuflowqgis_import_empty", "Empty Type"))
        self.txtRunID.setText(_translate("tuflowqgis_import_empty", "RunID"))
        self.label3.setText(_translate("tuflowqgis_import_empty", "Run ID"))
        self.label4.setText(_translate("tuflowqgis_import_empty", "Geometry Type"))
        __sortingEnabled = self.emptyType.isSortingEnabled()
        self.emptyType.setSortingEnabled(False)
        item = self.emptyType.item(0)
        item.setText(_translate("tuflowqgis_import_empty", "0d_RL"))
        item = self.emptyType.item(1)
        item.setText(_translate("tuflowqgis_import_empty", "1d_bc"))
        item = self.emptyType.item(2)
        item.setText(_translate("tuflowqgis_import_empty", "1d_iwl"))
        item = self.emptyType.item(3)
        item.setText(_translate("tuflowqgis_import_empty", "1d_mh"))
        item = self.emptyType.item(4)
        item.setText(_translate("tuflowqgis_import_empty", "1d_nd"))
        item = self.emptyType.item(5)
        item.setText(_translate("tuflowqgis_import_empty", "1d_nwk"))
        item = self.emptyType.item(6)
        item.setText(_translate("tuflowqgis_import_empty", "1d_nwkB"))
        item = self.emptyType.item(7)
        item.setText(_translate("tuflowqgis_import_empty", "1d_nwke"))
        item = self.emptyType.item(8)
        item.setText(_translate("tuflowqgis_import_empty", "1d_pit"))
        item = self.emptyType.item(9)
        item.setText(_translate("tuflowqgis_import_empty", "1d_tab"))
        item = self.emptyType.item(10)
        item.setText(_translate("tuflowqgis_import_empty", "1d_WLL"))
        item = self.emptyType.item(11)
        item.setText(_translate("tuflowqgis_import_empty", "2d_bc"))
        item = self.emptyType.item(12)
        item.setText(_translate("tuflowqgis_import_empty", "2d_code"))
        item = self.emptyType.item(13)
        item.setText(_translate("tuflowqgis_import_empty", "2d_fc"))
        item = self.emptyType.item(14)
        item.setText(_translate("tuflowqgis_import_empty", "2d_fcsh"))
        item = self.emptyType.item(15)
        item.setText(_translate("tuflowqgis_import_empty", "2d_glo"))
        item = self.emptyType.item(16)
        item.setText(_translate("tuflowqgis_import_empty", "2d_gw"))
        item = self.emptyType.item(17)
        item.setText(_translate("tuflowqgis_import_empty", "2d_iwl"))
        item = self.emptyType.item(18)
        item.setText(_translate("tuflowqgis_import_empty", "2d_lfcsh"))
        item = self.emptyType.item(19)
        item.setText(_translate("tuflowqgis_import_empty", "2d_loc"))
        item = self.emptyType.item(20)
        item.setText(_translate("tuflowqgis_import_empty", "2d_lp"))
        item = self.emptyType.item(21)
        item.setText(_translate("tuflowqgis_import_empty", "2d_mat"))
        item = self.emptyType.item(22)
        item.setText(_translate("tuflowqgis_import_empty", "2d_oz"))
        item = self.emptyType.item(23)
        item.setText(_translate("tuflowqgis_import_empty", "2d_po"))
        item = self.emptyType.item(24)
        item.setText(_translate("tuflowqgis_import_empty", "2d_rf"))
        item = self.emptyType.item(25)
        item.setText(_translate("tuflowqgis_import_empty", "2d_sa"))
        item = self.emptyType.item(26)
        item.setText(_translate("tuflowqgis_import_empty", "2d_sa_rf"))
        item = self.emptyType.item(27)
        item.setText(_translate("tuflowqgis_import_empty", "2d_sa_tr"))
        item = self.emptyType.item(28)
        item.setText(_translate("tuflowqgis_import_empty", "2d_soil"))
        item = self.emptyType.item(29)
        item.setText(_translate("tuflowqgis_import_empty", "2d_vzsh"))
        item = self.emptyType.item(30)
        item.setText(_translate("tuflowqgis_import_empty", "2d_z__"))
        item = self.emptyType.item(31)
        item.setText(_translate("tuflowqgis_import_empty", "2d_zsh"))
        item = self.emptyType.item(32)
        item.setText(_translate("tuflowqgis_import_empty", "2d_zshr"))
        self.emptyType.setSortingEnabled(__sortingEnabled)
        self.browsedir.setText(_translate("tuflowqgis_import_empty", "Browse..."))
        self.pbHideToolTip.setText(_translate("tuflowqgis_import_empty", "<< Hide Tool Tip"))
        self.pbShowToolTip.setText(_translate("tuflowqgis_import_empty", "Show Tool Tip >>"))
        self.teToolTip.setHtml(_translate("tuflowqgis_import_empty", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">Tool Tip</span></p></body></html>"))

