# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_tuflowqgis_insert_tuflow_attributes.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tuflowqgis_insert_tuflow_attributes(object):
    def setupUi(self, tuflowqgis_insert_tuflow_attributes):
        tuflowqgis_insert_tuflow_attributes.setObjectName("tuflowqgis_insert_tuflow_attributes")
        tuflowqgis_insert_tuflow_attributes.setWindowModality(QtCore.Qt.ApplicationModal)
        tuflowqgis_insert_tuflow_attributes.setEnabled(True)
        tuflowqgis_insert_tuflow_attributes.resize(372, 242)
        tuflowqgis_insert_tuflow_attributes.setMouseTracking(False)
        self.label1 = QtWidgets.QLabel(tuflowqgis_insert_tuflow_attributes)
        self.label1.setGeometry(QtCore.QRect(10, 10, 108, 22))
        self.label1.setObjectName("label1")
        self.emptydir = QtWidgets.QLineEdit(tuflowqgis_insert_tuflow_attributes)
        self.emptydir.setGeometry(QtCore.QRect(10, 30, 261, 21))
        self.emptydir.setReadOnly(False)
        self.emptydir.setObjectName("emptydir")
        self.browsedir = QtWidgets.QPushButton(tuflowqgis_insert_tuflow_attributes)
        self.browsedir.setGeometry(QtCore.QRect(281, 27, 79, 26))
        self.browsedir.setObjectName("browsedir")
        self.label2 = QtWidgets.QLabel(tuflowqgis_insert_tuflow_attributes)
        self.label2.setGeometry(QtCore.QRect(10, 110, 121, 22))
        self.label2.setObjectName("label2")
        self.txtRunID = QtWidgets.QLineEdit(tuflowqgis_insert_tuflow_attributes)
        self.txtRunID.setGeometry(QtCore.QRect(10, 180, 261, 21))
        self.txtRunID.setReadOnly(False)
        self.txtRunID.setObjectName("txtRunID")
        self.label3 = QtWidgets.QLabel(tuflowqgis_insert_tuflow_attributes)
        self.label3.setGeometry(QtCore.QRect(10, 160, 108, 22))
        self.label3.setObjectName("label3")
        self.label3_2 = QtWidgets.QLabel(tuflowqgis_insert_tuflow_attributes)
        self.label3_2.setGeometry(QtCore.QRect(10, 60, 108, 22))
        self.label3_2.setObjectName("label3_2")
        self.comboBox_inputLayer = QtWidgets.QComboBox(tuflowqgis_insert_tuflow_attributes)
        self.comboBox_inputLayer.setGeometry(QtCore.QRect(10, 80, 351, 22))
        self.comboBox_inputLayer.setObjectName("comboBox_inputLayer")
        self.comboBox_tfType = QtWidgets.QComboBox(tuflowqgis_insert_tuflow_attributes)
        self.comboBox_tfType.setGeometry(QtCore.QRect(10, 130, 261, 22))
        self.comboBox_tfType.setObjectName("comboBox_tfType")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.comboBox_tfType.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(tuflowqgis_insert_tuflow_attributes)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 210, 160, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbOk = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout.addWidget(self.pbOk)
        self.pbCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)

        self.retranslateUi(tuflowqgis_insert_tuflow_attributes)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_insert_tuflow_attributes)

    def retranslateUi(self, tuflowqgis_insert_tuflow_attributes):
        _translate = QtCore.QCoreApplication.translate
        tuflowqgis_insert_tuflow_attributes.setWindowTitle(_translate("tuflowqgis_insert_tuflow_attributes", "Insert TUFLOW attributes to existing GIS layer"))
        self.label1.setText(_translate("tuflowqgis_insert_tuflow_attributes", "Empty Directory"))
        self.emptydir.setText(_translate("tuflowqgis_insert_tuflow_attributes", "<directory>"))
        self.browsedir.setText(_translate("tuflowqgis_insert_tuflow_attributes", "Browse..."))
        self.label2.setText(_translate("tuflowqgis_insert_tuflow_attributes", "TUFLOW attribute type"))
        self.txtRunID.setText(_translate("tuflowqgis_insert_tuflow_attributes", "<RunID>"))
        self.label3.setText(_translate("tuflowqgis_insert_tuflow_attributes", "Run ID"))
        self.label3_2.setText(_translate("tuflowqgis_insert_tuflow_attributes", "Input Layer"))
        self.comboBox_tfType.setItemText(0, _translate("tuflowqgis_insert_tuflow_attributes", "0d_RL"))
        self.comboBox_tfType.setItemText(1, _translate("tuflowqgis_insert_tuflow_attributes", "1d_bc"))
        self.comboBox_tfType.setItemText(2, _translate("tuflowqgis_insert_tuflow_attributes", "1d_iwl"))
        self.comboBox_tfType.setItemText(3, _translate("tuflowqgis_insert_tuflow_attributes", "1d_mh"))
        self.comboBox_tfType.setItemText(4, _translate("tuflowqgis_insert_tuflow_attributes", "1d_nd"))
        self.comboBox_tfType.setItemText(5, _translate("tuflowqgis_insert_tuflow_attributes", "1d_nwk"))
        self.comboBox_tfType.setItemText(6, _translate("tuflowqgis_insert_tuflow_attributes", "1d_nwkb"))
        self.comboBox_tfType.setItemText(7, _translate("tuflowqgis_insert_tuflow_attributes", "1d_nwke"))
        self.comboBox_tfType.setItemText(8, _translate("tuflowqgis_insert_tuflow_attributes", "1d_pit"))
        self.comboBox_tfType.setItemText(9, _translate("tuflowqgis_insert_tuflow_attributes", "1d_tab"))
        self.comboBox_tfType.setItemText(10, _translate("tuflowqgis_insert_tuflow_attributes", "1d_WLL"))
        self.comboBox_tfType.setItemText(11, _translate("tuflowqgis_insert_tuflow_attributes", "2d_bc"))
        self.comboBox_tfType.setItemText(12, _translate("tuflowqgis_insert_tuflow_attributes", "2d_code"))
        self.comboBox_tfType.setItemText(13, _translate("tuflowqgis_insert_tuflow_attributes", "2d_fc"))
        self.comboBox_tfType.setItemText(14, _translate("tuflowqgis_insert_tuflow_attributes", "2d_fcsh"))
        self.comboBox_tfType.setItemText(15, _translate("tuflowqgis_insert_tuflow_attributes", "2d_glo"))
        self.comboBox_tfType.setItemText(16, _translate("tuflowqgis_insert_tuflow_attributes", "2d_gw"))
        self.comboBox_tfType.setItemText(17, _translate("tuflowqgis_insert_tuflow_attributes", "2d_iwl"))
        self.comboBox_tfType.setItemText(18, _translate("tuflowqgis_insert_tuflow_attributes", "2d_lfcsh"))
        self.comboBox_tfType.setItemText(19, _translate("tuflowqgis_insert_tuflow_attributes", "2d_loc"))
        self.comboBox_tfType.setItemText(20, _translate("tuflowqgis_insert_tuflow_attributes", "2d_lp"))
        self.comboBox_tfType.setItemText(21, _translate("tuflowqgis_insert_tuflow_attributes", "2d_mat"))
        self.comboBox_tfType.setItemText(22, _translate("tuflowqgis_insert_tuflow_attributes", "2d_oz"))
        self.comboBox_tfType.setItemText(23, _translate("tuflowqgis_insert_tuflow_attributes", "2d_po"))
        self.comboBox_tfType.setItemText(24, _translate("tuflowqgis_insert_tuflow_attributes", "2d_rf"))
        self.comboBox_tfType.setItemText(25, _translate("tuflowqgis_insert_tuflow_attributes", "2d_sa"))
        self.comboBox_tfType.setItemText(26, _translate("tuflowqgis_insert_tuflow_attributes", "2d_sa_rf"))
        self.comboBox_tfType.setItemText(27, _translate("tuflowqgis_insert_tuflow_attributes", "2d_sa_tr"))
        self.comboBox_tfType.setItemText(28, _translate("tuflowqgis_insert_tuflow_attributes", "2d_soil"))
        self.comboBox_tfType.setItemText(29, _translate("tuflowqgis_insert_tuflow_attributes", "2d_vzsh"))
        self.comboBox_tfType.setItemText(30, _translate("tuflowqgis_insert_tuflow_attributes", "2d_z__"))
        self.comboBox_tfType.setItemText(31, _translate("tuflowqgis_insert_tuflow_attributes", "2d_zsh"))
        self.comboBox_tfType.setItemText(32, _translate("tuflowqgis_insert_tuflow_attributes", "2d_zshr"))
        self.pbOk.setText(_translate("tuflowqgis_insert_tuflow_attributes", "OK"))
        self.pbCancel.setText(_translate("tuflowqgis_insert_tuflow_attributes", "Cancel"))

