# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_tuflowqgis_TuOptionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TuViewOptions(object):
    def setupUi(self, TuViewOptions):
        TuViewOptions.setObjectName("TuViewOptions")
        TuViewOptions.resize(401, 782)
        self.verticalLayout = QtWidgets.QVBoxLayout(TuViewOptions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.cbShowTriangles = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbShowTriangles.setObjectName("cbShowTriangles")
        self.gridLayout.addWidget(self.cbShowTriangles, 0, 2, 1, 1)
        self.cbShowGrid = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbShowGrid.setObjectName("cbShowGrid")
        self.gridLayout.addWidget(self.cbShowGrid, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.rbTimeUnitsHours = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbTimeUnitsHours.setChecked(True)
        self.rbTimeUnitsHours.setObjectName("rbTimeUnitsHours")
        self.buttonGroup = QtWidgets.QButtonGroup(TuViewOptions)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbTimeUnitsHours)
        self.horizontalLayout.addWidget(self.rbTimeUnitsHours)
        self.rbTimeUnitsSeconds = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbTimeUnitsSeconds.setObjectName("rbTimeUnitsSeconds")
        self.buttonGroup.addButton(self.rbTimeUnitsSeconds)
        self.horizontalLayout.addWidget(self.rbTimeUnitsSeconds)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 2)
        self.datePreview = QtWidgets.QLabel(self.groupBox)
        self.datePreview.setText("")
        self.datePreview.setObjectName("datePreview")
        self.gridLayout_2.addWidget(self.datePreview, 3, 2, 1, 1)
        self.rbLiveCursorTrackingOff = QtWidgets.QRadioButton(self.groupBox)
        self.rbLiveCursorTrackingOff.setObjectName("rbLiveCursorTrackingOff")
        self.LiveCursorTracking = QtWidgets.QButtonGroup(TuViewOptions)
        self.LiveCursorTracking.setObjectName("LiveCursorTracking")
        self.LiveCursorTracking.addButton(self.rbLiveCursorTrackingOff)
        self.gridLayout_2.addWidget(self.rbLiveCursorTrackingOff, 0, 3, 1, 1)
        self.cbDates = QtWidgets.QCheckBox(self.groupBox)
        self.cbDates.setObjectName("cbDates")
        self.gridLayout_2.addWidget(self.cbDates, 2, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.dteZeroDate = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dteZeroDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dteZeroDate.setCalendarPopup(True)
        self.dteZeroDate.setObjectName("dteZeroDate")
        self.gridLayout_2.addWidget(self.dteZeroDate, 5, 2, 1, 4)
        self.rbLiveCursorTrackingOn = QtWidgets.QRadioButton(self.groupBox)
        self.rbLiveCursorTrackingOn.setChecked(True)
        self.rbLiveCursorTrackingOn.setObjectName("rbLiveCursorTrackingOn")
        self.LiveCursorTracking.addButton(self.rbLiveCursorTrackingOn)
        self.gridLayout_2.addWidget(self.rbLiveCursorTrackingOn, 0, 2, 1, 1)
        self.sbXAxisLabelRotation = QtWidgets.QSpinBox(self.groupBox)
        self.sbXAxisLabelRotation.setMinimum(-359)
        self.sbXAxisLabelRotation.setMaximum(359)
        self.sbXAxisLabelRotation.setObjectName("sbXAxisLabelRotation")
        self.gridLayout_2.addWidget(self.sbXAxisLabelRotation, 6, 3, 1, 1)
        self.leDateFormat = QtWidgets.QLineEdit(self.groupBox)
        self.leDateFormat.setObjectName("leDateFormat")
        self.gridLayout_2.addWidget(self.leDateFormat, 4, 2, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 6, 4, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 5)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sbPlaySpeed = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sbPlaySpeed.setDecimals(1)
        self.sbPlaySpeed.setMinimum(0.1)
        self.sbPlaySpeed.setProperty("value", 1.0)
        self.sbPlaySpeed.setObjectName("sbPlaySpeed")
        self.gridLayout_3.addWidget(self.sbPlaySpeed, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 1, 1)
        self.sbResolution = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sbResolution.setDecimals(1)
        self.sbResolution.setMinimum(0.1)
        self.sbResolution.setProperty("value", 1.0)
        self.sbResolution.setObjectName("sbResolution")
        self.gridLayout_4.addWidget(self.sbResolution, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.sbLabelFieldIndex = QtWidgets.QSpinBox(self.groupBox_4)
        self.sbLabelFieldIndex.setMinimum(1)
        self.sbLabelFieldIndex.setMaximum(999)
        self.sbLabelFieldIndex.setProperty("value", 1)
        self.sbLabelFieldIndex.setObjectName("sbLabelFieldIndex")
        self.gridLayout_4.addWidget(self.sbLabelFieldIndex, 1, 1, 1, 1)
        self.cbInterpolateVertProf = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbInterpolateVertProf.setObjectName("cbInterpolateVertProf")
        self.gridLayout_4.addWidget(self.cbInterpolateVertProf, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.rbARRNextHigher = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbARRNextHigher.setChecked(True)
        self.rbARRNextHigher.setObjectName("rbARRNextHigher")
        self.MeanSelection = QtWidgets.QButtonGroup(TuViewOptions)
        self.MeanSelection.setObjectName("MeanSelection")
        self.MeanSelection.addButton(self.rbARRNextHigher)
        self.gridLayout_5.addWidget(self.rbARRNextHigher, 0, 1, 1, 1)
        self.rbARRClosest = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbARRClosest.setObjectName("rbARRClosest")
        self.MeanSelection.addButton(self.rbARRClosest)
        self.gridLayout_5.addWidget(self.rbARRClosest, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbDefaultLayoutPlotView = QtWidgets.QRadioButton(self.groupBox_6)
        self.rbDefaultLayoutPlotView.setChecked(True)
        self.rbDefaultLayoutPlotView.setObjectName("rbDefaultLayoutPlotView")
        self.DefaultLayout = QtWidgets.QButtonGroup(TuViewOptions)
        self.DefaultLayout.setObjectName("DefaultLayout")
        self.DefaultLayout.addButton(self.rbDefaultLayoutPlotView)
        self.horizontalLayout_2.addWidget(self.rbDefaultLayoutPlotView)
        self.rbDeafultLayoutNarrowView = QtWidgets.QRadioButton(self.groupBox_6)
        self.rbDeafultLayoutNarrowView.setObjectName("rbDeafultLayoutNarrowView")
        self.DefaultLayout.addButton(self.rbDeafultLayoutNarrowView)
        self.horizontalLayout_2.addWidget(self.rbDeafultLayoutNarrowView)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.gbCheckFiles = QgsCollapsibleGroupBox(TuViewOptions)
        self.gbCheckFiles.setCollapsed(False)
        self.gbCheckFiles.setObjectName("gbCheckFiles")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbCheckFiles)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbMeshIntCheck = QtWidgets.QCheckBox(self.gbCheckFiles)
        self.cbMeshIntCheck.setObjectName("cbMeshIntCheck")
        self.verticalLayout_4.addWidget(self.cbMeshIntCheck)
        self.cbParticleDebug = QtWidgets.QCheckBox(self.gbCheckFiles)
        self.cbParticleDebug.setObjectName("cbParticleDebug")
        self.verticalLayout_4.addWidget(self.cbParticleDebug)
        self.verticalLayout.addWidget(self.gbCheckFiles)
        self.buttonBox = QtWidgets.QDialogButtonBox(TuViewOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TuViewOptions)
        self.buttonBox.accepted.connect(TuViewOptions.accept)
        self.buttonBox.rejected.connect(TuViewOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(TuViewOptions)

    def retranslateUi(self, TuViewOptions):
        _translate = QtCore.QCoreApplication.translate
        TuViewOptions.setWindowTitle(_translate("TuViewOptions", "Settings"))
        self.groupBox_5.setTitle(_translate("TuViewOptions", "Mesh Rendering"))
        self.cbShowTriangles.setText(_translate("TuViewOptions", "Show Triangles"))
        self.cbShowGrid.setText(_translate("TuViewOptions", "Show Grid"))
        self.label_9.setText(_translate("TuViewOptions", "XMDF / DAT time units"))
        self.rbTimeUnitsHours.setText(_translate("TuViewOptions", "Hours"))
        self.rbTimeUnitsSeconds.setText(_translate("TuViewOptions", "Seconds (TUFLOW FV)"))
        self.groupBox.setTitle(_translate("TuViewOptions", "Plotting"))
        self.label_8.setText(_translate("TuViewOptions", "X-Axis Label Rotation (deg):"))
        self.label.setText(_translate("TuViewOptions", "Live Map Tracking:"))
        self.label_5.setText(_translate("TuViewOptions", "Zero Date:"))
        self.rbLiveCursorTrackingOff.setText(_translate("TuViewOptions", "Off"))
        self.cbDates.setText(_translate("TuViewOptions", "Display Time Series X-Axis as Dates:"))
        self.label_6.setText(_translate("TuViewOptions", "Display Format*: "))
        self.label_7.setText(_translate("TuViewOptions", "Preview: "))
        self.rbLiveCursorTrackingOn.setText(_translate("TuViewOptions", "On"))
        self.leDateFormat.setText(_translate("TuViewOptions", "DD/MM/YYYY hh:mm:ss"))
        self.label_11.setText(_translate("TuViewOptions", "<html><head/><body><p>*Capitals for date (DD/MM/YYYY) lower case for time (hh:mm:ss)</p><p>DD/MM/YYYY hh:mm:ss - 31/12/1988 12:00:00</p><p>MMM/YY - Dec/88</p><p>DD/MMMM hh:mm - 31/December 12:00</p></body></html>"))
        self.groupBox_3.setTitle(_translate("TuViewOptions", "Auto Play"))
        self.label_3.setText(_translate("TuViewOptions", "Auto Play Speed (sec)"))
        self.groupBox_4.setTitle(_translate("TuViewOptions", "Map Plotting"))
        self.label_4.setText(_translate("TuViewOptions", "Resolution (map units)"))
        self.label_10.setText(_translate("TuViewOptions", "Label Field Index"))
        self.cbInterpolateVertProf.setText(_translate("TuViewOptions", "Interpolate Vertical Profile"))
        self.groupBox_2.setTitle(_translate("TuViewOptions", "ARR2019"))
        self.label_2.setText(_translate("TuViewOptions", "Mean Event Selection:"))
        self.rbARRNextHigher.setText(_translate("TuViewOptions", "Next higher"))
        self.rbARRClosest.setText(_translate("TuViewOptions", "Closest"))
        self.groupBox_6.setTitle(_translate("TuViewOptions", "Default Layout"))
        self.rbDefaultLayoutPlotView.setText(_translate("TuViewOptions", "Plot View"))
        self.rbDeafultLayoutNarrowView.setText(_translate("TuViewOptions", "Narrow View"))
        self.gbCheckFiles.setTitle(_translate("TuViewOptions", "Check Files"))
        self.cbMeshIntCheck.setText(_translate("TuViewOptions", "Mesh intercept locations (for map plotting line types e.g. cross section)"))
        self.cbParticleDebug.setText(_translate("TuViewOptions", "Particles - Include X, Y, Z, Time info in attribute table"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
