# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\animation_plot_properties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotProperties(object):
    def setupUi(self, PlotProperties):
        PlotProperties.setObjectName("PlotProperties")
        PlotProperties.resize(380, 325)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PlotProperties)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbGridX = QtWidgets.QCheckBox(PlotProperties)
        self.cbGridX.setChecked(True)
        self.cbGridX.setObjectName("cbGridX")
        self.gridLayout.addWidget(self.cbGridX, 8, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(PlotProperties)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(PlotProperties)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.sbXmin = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbXmin.setDecimals(1)
        self.sbXmin.setMinimum(-99999.0)
        self.sbXmin.setMaximum(99999.0)
        self.sbXmin.setObjectName("sbXmin")
        self.gridLayout_2.addWidget(self.sbXmin, 0, 1, 1, 1)
        self.sbXMax = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbXMax.setDecimals(1)
        self.sbXMax.setMinimum(-99999.0)
        self.sbXMax.setMaximum(99999.0)
        self.sbXMax.setObjectName("sbXMax")
        self.gridLayout_2.addWidget(self.sbXMax, 0, 3, 1, 1)
        self.pbAutoCalcXLim = QtWidgets.QPushButton(PlotProperties)
        self.pbAutoCalcXLim.setObjectName("pbAutoCalcXLim")
        self.gridLayout_2.addWidget(self.pbAutoCalcXLim, 0, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(PlotProperties)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(PlotProperties)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sbFigSizeX = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbFigSizeX.setDecimals(2)
        self.sbFigSizeX.setMaximum(99999.0)
        self.sbFigSizeX.setProperty("value", 100.0)
        self.sbFigSizeX.setObjectName("sbFigSizeX")
        self.gridLayout_4.addWidget(self.sbFigSizeX, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(PlotProperties)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(PlotProperties)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.sbFigSizeY = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbFigSizeY.setMaximum(99999.0)
        self.sbFigSizeY.setProperty("value", 100.0)
        self.sbFigSizeY.setObjectName("sbFigSizeY")
        self.gridLayout_4.addWidget(self.sbFigSizeY, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 9, 1, 1, 1)
        self.leXLabel = QtWidgets.QLineEdit(PlotProperties)
        self.leXLabel.setObjectName("leXLabel")
        self.gridLayout.addWidget(self.leXLabel, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(PlotProperties)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(PlotProperties)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(PlotProperties)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.cbLegend = QtWidgets.QCheckBox(PlotProperties)
        self.cbLegend.setObjectName("cbLegend")
        self.gridLayout.addWidget(self.cbLegend, 7, 0, 1, 1)
        self.leTitle = QtWidgets.QLineEdit(PlotProperties)
        self.leTitle.setObjectName("leTitle")
        self.gridLayout.addWidget(self.leTitle, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.leYLabel = QtWidgets.QLineEdit(PlotProperties)
        self.leYLabel.setObjectName("leYLabel")
        self.gridLayout.addWidget(self.leYLabel, 2, 1, 1, 1)
        self.cboLegendPos = QtWidgets.QComboBox(PlotProperties)
        self.cboLegendPos.setObjectName("cboLegendPos")
        self.cboLegendPos.addItem("")
        self.cboLegendPos.addItem("")
        self.cboLegendPos.addItem("")
        self.cboLegendPos.addItem("")
        self.gridLayout.addWidget(self.cboLegendPos, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(PlotProperties)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sbYMin = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbYMin.setDecimals(1)
        self.sbYMin.setMinimum(-99999.0)
        self.sbYMin.setMaximum(99999.0)
        self.sbYMin.setObjectName("sbYMin")
        self.gridLayout_3.addWidget(self.sbYMin, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(PlotProperties)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(PlotProperties)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.sbYMax = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbYMax.setDecimals(1)
        self.sbYMax.setMinimum(-99999.0)
        self.sbYMax.setMaximum(99999.0)
        self.sbYMax.setObjectName("sbYMax")
        self.gridLayout_3.addWidget(self.sbYMax, 0, 3, 1, 1)
        self.pbAutoCalcYLim = QtWidgets.QPushButton(PlotProperties)
        self.pbAutoCalcYLim.setObjectName("pbAutoCalcYLim")
        self.gridLayout_3.addWidget(self.pbAutoCalcYLim, 0, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(PlotProperties)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sbY2Max = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbY2Max.setDecimals(1)
        self.sbY2Max.setMinimum(-99999.0)
        self.sbY2Max.setMaximum(99999.0)
        self.sbY2Max.setObjectName("sbY2Max")
        self.gridLayout_5.addWidget(self.sbY2Max, 0, 3, 1, 1)
        self.sbY2Min = QtWidgets.QDoubleSpinBox(PlotProperties)
        self.sbY2Min.setDecimals(1)
        self.sbY2Min.setMinimum(-99999.0)
        self.sbY2Min.setMaximum(99999.0)
        self.sbY2Min.setObjectName("sbY2Min")
        self.gridLayout_5.addWidget(self.sbY2Min, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(PlotProperties)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(PlotProperties)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 2, 1, 1)
        self.pbAutoCalcY2Lim = QtWidgets.QPushButton(PlotProperties)
        self.pbAutoCalcY2Lim.setObjectName("pbAutoCalcY2Lim")
        self.gridLayout_5.addWidget(self.pbAutoCalcY2Lim, 0, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 6, 1, 1, 1)
        self.leY2Label = QtWidgets.QLineEdit(PlotProperties)
        self.leY2Label.setObjectName("leY2Label")
        self.gridLayout.addWidget(self.leY2Label, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(PlotProperties)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.cbGridY = QtWidgets.QCheckBox(PlotProperties)
        self.cbGridY.setChecked(True)
        self.cbGridY.setObjectName("cbGridY")
        self.gridLayout.addWidget(self.cbGridY, 8, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(PlotProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(PlotProperties)
        self.buttonBox.accepted.connect(PlotProperties.accept)
        self.buttonBox.rejected.connect(PlotProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(PlotProperties)
        PlotProperties.setTabOrder(self.leTitle, self.leXLabel)
        PlotProperties.setTabOrder(self.leXLabel, self.leYLabel)
        PlotProperties.setTabOrder(self.leYLabel, self.leY2Label)
        PlotProperties.setTabOrder(self.leY2Label, self.sbXmin)
        PlotProperties.setTabOrder(self.sbXmin, self.sbXMax)
        PlotProperties.setTabOrder(self.sbXMax, self.sbYMin)
        PlotProperties.setTabOrder(self.sbYMin, self.sbYMax)
        PlotProperties.setTabOrder(self.sbYMax, self.sbY2Min)
        PlotProperties.setTabOrder(self.sbY2Min, self.sbY2Max)
        PlotProperties.setTabOrder(self.sbY2Max, self.cboLegendPos)
        PlotProperties.setTabOrder(self.cboLegendPos, self.cbGridY)
        PlotProperties.setTabOrder(self.cbGridY, self.cbGridX)
        PlotProperties.setTabOrder(self.cbGridX, self.sbFigSizeX)
        PlotProperties.setTabOrder(self.sbFigSizeX, self.sbFigSizeY)
        PlotProperties.setTabOrder(self.sbFigSizeY, self.cbLegend)

    def retranslateUi(self, PlotProperties):
        _translate = QtCore.QCoreApplication.translate
        PlotProperties.setWindowTitle(_translate("PlotProperties", "Plot Properties"))
        self.cbGridX.setText(_translate("PlotProperties", "X Grid Lines"))
        self.label_5.setText(_translate("PlotProperties", "Min"))
        self.label_6.setText(_translate("PlotProperties", "Max"))
        self.pbAutoCalcXLim.setText(_translate("PlotProperties", "Auto Calc"))
        self.label_7.setText(_translate("PlotProperties", "Y Axis Limits"))
        self.label_10.setText(_translate("PlotProperties", "Figure Size (mm)"))
        self.label_12.setText(_translate("PlotProperties", "Y: "))
        self.label_11.setText(_translate("PlotProperties", "X: "))
        self.label_4.setText(_translate("PlotProperties", "X Axis Limits"))
        self.label.setText(_translate("PlotProperties", "Title"))
        self.label_3.setText(_translate("PlotProperties", "Y Axis Label"))
        self.cbLegend.setText(_translate("PlotProperties", "Legend"))
        self.cboLegendPos.setItemText(0, _translate("PlotProperties", "Top-Right"))
        self.cboLegendPos.setItemText(1, _translate("PlotProperties", "Top-Left"))
        self.cboLegendPos.setItemText(2, _translate("PlotProperties", "Bottom-Left"))
        self.cboLegendPos.setItemText(3, _translate("PlotProperties", "Bottom-Right"))
        self.label_2.setText(_translate("PlotProperties", "X Axis Label"))
        self.label_9.setText(_translate("PlotProperties", "Max"))
        self.label_8.setText(_translate("PlotProperties", "Min"))
        self.pbAutoCalcYLim.setText(_translate("PlotProperties", "Auto Calc"))
        self.label_13.setText(_translate("PlotProperties", "2nd Y Axis Label"))
        self.label_15.setText(_translate("PlotProperties", "Min"))
        self.label_16.setText(_translate("PlotProperties", "Max"))
        self.pbAutoCalcY2Lim.setText(_translate("PlotProperties", "Auto Calc"))
        self.label_14.setText(_translate("PlotProperties", "2nd Y Axis Limits"))
        self.cbGridY.setText(_translate("PlotProperties", "Y Grid Lines"))

