# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\tuflow_main_dock.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(325, 878)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 10)
        self.gridLayout_3.setColumnStretch(1, 10)
        self.gridLayout_3.setColumnStretch(2, 4)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.Tuviewer = DataSetView(self.dockWidgetContents)
        self.Tuviewer.setMinimumSize(QtCore.QSize(0, 55))
        self.Tuviewer.setObjectName("Tuviewer")
        self.verticalLayout_2.addWidget(self.Tuviewer)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.contoursGroupBox = QgsCollapsibleGroupBox(self.dockWidgetContents)
        self.contoursGroupBox.setCheckable(True)
        self.contoursGroupBox.setObjectName("contoursGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contoursGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.contoursGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.contourTransparencySlider = QtWidgets.QSlider(self.contoursGroupBox)
        self.contourTransparencySlider.setMaximum(255)
        self.contourTransparencySlider.setPageStep(20)
        self.contourTransparencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.contourTransparencySlider.setObjectName("contourTransparencySlider")
        self.horizontalLayout_2.addWidget(self.contourTransparencySlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radContourBasic = QtWidgets.QRadioButton(self.contoursGroupBox)
        self.radContourBasic.setChecked(True)
        self.radContourBasic.setObjectName("radContourBasic")
        self.horizontalLayout_3.addWidget(self.radContourBasic)
        self.cboContourBasic = QgsColorButton(self.contoursGroupBox)
        self.cboContourBasic.setObjectName("cboContourBasic")
        self.horizontalLayout_3.addWidget(self.cboContourBasic)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.contourCustomRangeCheckBox = QtWidgets.QCheckBox(self.contoursGroupBox)
        self.contourCustomRangeCheckBox.setText("")
        self.contourCustomRangeCheckBox.setObjectName("contourCustomRangeCheckBox")
        self.horizontalLayout.addWidget(self.contourCustomRangeCheckBox)
        self.contourMinLabel = QtWidgets.QLabel(self.contoursGroupBox)
        self.contourMinLabel.setObjectName("contourMinLabel")
        self.horizontalLayout.addWidget(self.contourMinLabel)
        self.contourMinLineEdit = QtWidgets.QLineEdit(self.contoursGroupBox)
        self.contourMinLineEdit.setEnabled(False)
        self.contourMinLineEdit.setObjectName("contourMinLineEdit")
        self.horizontalLayout.addWidget(self.contourMinLineEdit)
        self.contourMaxLabel = QtWidgets.QLabel(self.contoursGroupBox)
        self.contourMaxLabel.setObjectName("contourMaxLabel")
        self.horizontalLayout.addWidget(self.contourMaxLabel)
        self.contourMaxLineEdit = QtWidgets.QLineEdit(self.contoursGroupBox)
        self.contourMaxLineEdit.setEnabled(False)
        self.contourMaxLineEdit.setObjectName("contourMaxLineEdit")
        self.horizontalLayout.addWidget(self.contourMaxLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radContourAdvanced = QtWidgets.QRadioButton(self.contoursGroupBox)
        self.radContourAdvanced.setObjectName("radContourAdvanced")
        self.horizontalLayout_4.addWidget(self.radContourAdvanced)
        self.lblAdvancedPreview = QtWidgets.QLabel(self.contoursGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAdvancedPreview.sizePolicy().hasHeightForWidth())
        self.lblAdvancedPreview.setSizePolicy(sizePolicy)
        self.lblAdvancedPreview.setMinimumSize(QtCore.QSize(100, 0))
        self.lblAdvancedPreview.setText("")
        self.lblAdvancedPreview.setObjectName("lblAdvancedPreview")
        self.horizontalLayout_4.addWidget(self.lblAdvancedPreview)
        self.btnAdvanced = QtWidgets.QToolButton(self.contoursGroupBox)
        self.btnAdvanced.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnAdvanced.setAutoRaise(True)
        self.btnAdvanced.setArrowType(QtCore.Qt.NoArrow)
        self.btnAdvanced.setObjectName("btnAdvanced")
        self.horizontalLayout_4.addWidget(self.btnAdvanced)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.contoursGroupBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 7, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.displayMeshCheckBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.displayMeshCheckBox.setObjectName("displayMeshCheckBox")
        self.gridLayout.addWidget(self.displayMeshCheckBox, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btnVectorOptions = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnVectorOptions.setAutoRaise(True)
        self.btnVectorOptions.setObjectName("btnVectorOptions")
        self.horizontalLayout_5.addWidget(self.btnVectorOptions)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 2, 1)
        self.displayVectorsCheckBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.displayVectorsCheckBox.setObjectName("displayVectorsCheckBox")
        self.gridLayout.addWidget(self.displayVectorsCheckBox, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnMeshOptions = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnMeshOptions.setEnabled(True)
        self.btnMeshOptions.setAutoRaise(True)
        self.btnMeshOptions.setObjectName("btnMeshOptions")
        self.horizontalLayout_8.addWidget(self.btnMeshOptions)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.valueLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.valueLabel.setObjectName("valueLabel")
        self.verticalLayout_2.addWidget(self.valueLabel)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.displayVectorsCheckBox.toggled['bool'].connect(DockWidget.displayVectorsButtonToggled)
        self.displayMeshCheckBox.toggled['bool'].connect(DockWidget.displayMeshButtonToggled)
        self.btnVectorOptions.clicked.connect(DockWidget.displayVectorPropsDialog)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.Tuviewer, self.contoursGroupBox)
        DockWidget.setTabOrder(self.contoursGroupBox, self.contourTransparencySlider)
        DockWidget.setTabOrder(self.contourTransparencySlider, self.radContourBasic)
        DockWidget.setTabOrder(self.radContourBasic, self.contourCustomRangeCheckBox)
        DockWidget.setTabOrder(self.contourCustomRangeCheckBox, self.contourMinLineEdit)
        DockWidget.setTabOrder(self.contourMinLineEdit, self.contourMaxLineEdit)
        DockWidget.setTabOrder(self.contourMaxLineEdit, self.radContourAdvanced)
        DockWidget.setTabOrder(self.radContourAdvanced, self.btnAdvanced)
        DockWidget.setTabOrder(self.btnAdvanced, self.displayVectorsCheckBox)
        DockWidget.setTabOrder(self.displayVectorsCheckBox, self.btnVectorOptions)
        DockWidget.setTabOrder(self.btnVectorOptions, self.displayMeshCheckBox)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "TUFLOW"))
        self.pushButton_3.setText(_translate("DockWidget", "Add 1D and 2D Results"))
        self.pushButton.setText(_translate("DockWidget", "Add 2D Results"))
        self.pushButton_2.setText(_translate("DockWidget", "TUPLOT"))
        self.label.setText(_translate("DockWidget", "Results"))
        self.label_2.setText(_translate("DockWidget", "Output Time"))
        self.contoursGroupBox.setTitle(_translate("DockWidget", "Display Contours"))
        self.label_3.setText(_translate("DockWidget", "Transparency"))
        self.radContourBasic.setText(_translate("DockWidget", "Basic"))
        self.contourMinLabel.setText(_translate("DockWidget", "Min"))
        self.contourMaxLabel.setText(_translate("DockWidget", "Max"))
        self.radContourAdvanced.setText(_translate("DockWidget", "Advanced"))
        self.btnAdvanced.setToolTip(_translate("DockWidget", "Advanced Contour Options"))
        self.btnAdvanced.setText(_translate("DockWidget", "..."))
        self.displayMeshCheckBox.setText(_translate("DockWidget", "Display Mesh"))
        self.btnVectorOptions.setToolTip(_translate("DockWidget", "Vector Options"))
        self.btnVectorOptions.setText(_translate("DockWidget", "..."))
        self.displayVectorsCheckBox.setText(_translate("DockWidget", "Display Vectors"))
        self.btnMeshOptions.setText(_translate("DockWidget", "..."))
        self.valueLabel.setText(_translate("DockWidget", "(0.000) 0.000"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgscolorbutton import QgsColorButton
from tuflow.dataset_view import DataSetView
