# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\tuflow_plotting_dock.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tuplot(object):
    def setupUi(self, Tuplot):
        Tuplot.setObjectName("Tuplot")
        Tuplot.resize(1118, 479)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.InteractionLayout = QtWidgets.QGridLayout()
        self.InteractionLayout.setObjectName("InteractionLayout")
        self.ResultsLayout = QtWidgets.QGridLayout()
        self.ResultsLayout.setObjectName("ResultsLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.ResultsLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.OpenResultTypes = DataSetView(self.dockWidgetContents)
        self.OpenResultTypes.setMinimumSize(QtCore.QSize(150, 55))
        self.OpenResultTypes.setMouseTracking(True)
        self.OpenResultTypes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.OpenResultTypes.setObjectName("OpenResultTypes")
        self.ResultsLayout.addWidget(self.OpenResultTypes, 1, 2, 7, 2)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ResultsLayout.addItem(spacerItem, 0, 4, 7, 1)
        self.cbShowCurrentTime = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cbShowCurrentTime.setObjectName("cbShowCurrentTime")
        self.ResultsLayout.addWidget(self.cbShowCurrentTime, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.ResultsLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.ResultsLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MapOutputPlotFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.MapOutputPlotFrame.setMinimumSize(QtCore.QSize(100, 30))
        self.MapOutputPlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MapOutputPlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MapOutputPlotFrame.setObjectName("MapOutputPlotFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MapOutputPlotFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.MapOutputPlotFrame)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.ViewToolbarFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.ViewToolbarFrame.setMinimumSize(QtCore.QSize(100, 30))
        self.ViewToolbarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewToolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewToolbarFrame.setObjectName("ViewToolbarFrame")
        self.verticalLayout.addWidget(self.ViewToolbarFrame)
        self.mplToolbarFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.mplToolbarFrame.setMinimumSize(QtCore.QSize(100, 30))
        self.mplToolbarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mplToolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mplToolbarFrame.setObjectName("mplToolbarFrame")
        self.verticalLayout.addWidget(self.mplToolbarFrame)
        self.ResultsLayout.addLayout(self.verticalLayout, 4, 0, 1, 2)
        self.OpenResults = QtWidgets.QListWidget(self.dockWidgetContents)
        self.OpenResults.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.OpenResults.setMovement(QtWidgets.QListView.Static)
        self.OpenResults.setResizeMode(QtWidgets.QListView.Fixed)
        self.OpenResults.setObjectName("OpenResults")
        self.ResultsLayout.addWidget(self.OpenResults, 1, 0, 1, 2)
        self.cboSelectType = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboSelectType.setEditable(True)
        self.cboSelectType.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cboSelectType.setObjectName("cboSelectType")
        self.cboSelectType.addItem("")
        self.cboSelectType.addItem("")
        self.cboSelectType.addItem("")
        self.ResultsLayout.addWidget(self.cboSelectType, 3, 0, 1, 2)
        self.InteractionLayout.addLayout(self.ResultsLayout, 0, 0, 2, 1)
        self.ReultOptionLayout = QtWidgets.QGridLayout()
        self.ReultOptionLayout.setObjectName("ReultOptionLayout")
        self.btnPrev = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnPrev.setAutoRaise(True)
        self.btnPrev.setObjectName("btnPrev")
        self.ReultOptionLayout.addWidget(self.btnPrev, 1, 2, 1, 1)
        self.btnLast = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnLast.setAutoRaise(True)
        self.btnLast.setObjectName("btnLast")
        self.ReultOptionLayout.addWidget(self.btnLast, 1, 4, 1, 1)
        self.btnTimePlay = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnTimePlay.setCheckable(True)
        self.btnTimePlay.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnTimePlay.setAutoRaise(True)
        self.btnTimePlay.setArrowType(QtCore.Qt.NoArrow)
        self.btnTimePlay.setObjectName("btnTimePlay")
        self.ReultOptionLayout.addWidget(self.btnTimePlay, 1, 5, 1, 1)
        self.btnNext = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnNext.setAutoRaise(True)
        self.btnNext.setObjectName("btnNext")
        self.ReultOptionLayout.addWidget(self.btnNext, 1, 3, 1, 1)
        self.btnFirst = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnFirst.setAutoRaise(True)
        self.btnFirst.setObjectName("btnFirst")
        self.ReultOptionLayout.addWidget(self.btnFirst, 1, 1, 1, 1)
        self.cboTime = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboTime.setEditable(True)
        self.cboTime.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cboTime.setObjectName("cboTime")
        self.ReultOptionLayout.addWidget(self.cboTime, 1, 0, 1, 1)
        self.btn2dLock = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btn2dLock.setCheckable(False)
        self.btn2dLock.setAutoRaise(True)
        self.btn2dLock.setObjectName("btn2dLock")
        self.ReultOptionLayout.addWidget(self.btn2dLock, 1, 7, 1, 1)
        self.sliderTime = QtWidgets.QSlider(self.dockWidgetContents)
        self.sliderTime.setMaximum(100)
        self.sliderTime.setPageStep(100)
        self.sliderTime.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTime.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderTime.setTickInterval(1)
        self.sliderTime.setObjectName("sliderTime")
        self.ReultOptionLayout.addWidget(self.sliderTime, 0, 0, 1, 9)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ReultOptionLayout.addItem(spacerItem2, 1, 8, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ReultOptionLayout.addWidget(self.line_2, 1, 6, 1, 1)
        self.ReultOptionLayout.setColumnStretch(0, 10)
        self.ReultOptionLayout.setColumnStretch(1, 10)
        self.ReultOptionLayout.setColumnStretch(2, 10)
        self.ReultOptionLayout.setColumnStretch(3, 10)
        self.ReultOptionLayout.setColumnStretch(4, 10)
        self.ReultOptionLayout.setColumnStretch(5, 10)
        self.ReultOptionLayout.setColumnStretch(6, 10)
        self.ReultOptionLayout.setColumnStretch(7, 1)
        self.ReultOptionLayout.setRowStretch(0, 10)
        self.InteractionLayout.addLayout(self.ReultOptionLayout, 2, 0, 1, 1)
        self.InteractionLayout.setRowStretch(0, 10)
        self.gridLayout.addLayout(self.InteractionLayout, 0, 3, 3, 2)
        self.mainMenu = QtWidgets.QVBoxLayout()
        self.mainMenu.setObjectName("mainMenu")
        self.gridLayout.addLayout(self.mainMenu, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logo/TUFLOW_logo_resized.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.TimeSeriesTab = QtWidgets.QWidget()
        self.TimeSeriesTab.setObjectName("TimeSeriesTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TimeSeriesTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TimeSeriesLayout = QtWidgets.QGridLayout()
        self.TimeSeriesLayout.setObjectName("TimeSeriesLayout")
        self.TimeSeriesFrame = QtWidgets.QFrame(self.TimeSeriesTab)
        self.TimeSeriesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TimeSeriesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TimeSeriesFrame.setObjectName("TimeSeriesFrame")
        self.TimeSeriesLayout.addWidget(self.TimeSeriesFrame, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.TimeSeriesLayout, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 10)
        self.gridLayout_3.setRowStretch(0, 10)
        self.tabWidget.addTab(self.TimeSeriesTab, "")
        self.LongPlotTab = QtWidgets.QWidget()
        self.LongPlotTab.setObjectName("LongPlotTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.LongPlotTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LongPlotLayout = QtWidgets.QGridLayout()
        self.LongPlotLayout.setObjectName("LongPlotLayout")
        self.LongPlotFrame = QtWidgets.QFrame(self.LongPlotTab)
        self.LongPlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LongPlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LongPlotFrame.setObjectName("LongPlotFrame")
        self.LongPlotLayout.addWidget(self.LongPlotFrame, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.LongPlotLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.LongPlotTab, "")
        self.CrossSectionTab = QtWidgets.QWidget()
        self.CrossSectionTab.setObjectName("CrossSectionTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CrossSectionTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CrossSectionLayout = QtWidgets.QGridLayout()
        self.CrossSectionLayout.setObjectName("CrossSectionLayout")
        self.CrossSectionFrame = QtWidgets.QFrame(self.CrossSectionTab)
        self.CrossSectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CrossSectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CrossSectionFrame.setObjectName("CrossSectionFrame")
        self.CrossSectionLayout.addWidget(self.CrossSectionFrame, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.CrossSectionLayout, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.CrossSectionTab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.CrossSectionTab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 10)
        Tuplot.setWidget(self.dockWidgetContents)

        self.retranslateUi(Tuplot)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Tuplot)

    def retranslateUi(self, Tuplot):
        _translate = QtCore.QCoreApplication.translate
        Tuplot.setWindowTitle(_translate("Tuplot", "TUFLOW"))
        self.label_2.setText(_translate("Tuplot", "Result Type"))
        self.OpenResultTypes.setToolTip(_translate("Tuplot", "Test"))
        self.cbShowCurrentTime.setText(_translate("Tuplot", "Show Current Time"))
        self.label.setText(_translate("Tuplot", "Open Results"))
        self.label_3.setText(_translate("Tuplot", "Map Output Plotting"))
        self.cboSelectType.setItemText(0, _translate("Tuplot", "From Map"))
        self.cboSelectType.setItemText(1, _translate("Tuplot", "From Map Multi"))
        self.cboSelectType.setItemText(2, _translate("Tuplot", "Layer Selection"))
        self.btnPrev.setToolTip(_translate("Tuplot", "Previous Timestep"))
        self.btnPrev.setText(_translate("Tuplot", "<"))
        self.btnLast.setToolTip(_translate("Tuplot", "Last Timestep"))
        self.btnLast.setText(_translate("Tuplot", ">|"))
        self.btnTimePlay.setToolTip(_translate("Tuplot", "Play Through Timesteps"))
        self.btnTimePlay.setText(_translate("Tuplot", "..."))
        self.btnNext.setToolTip(_translate("Tuplot", "Next Timestep"))
        self.btnNext.setText(_translate("Tuplot", ">"))
        self.btnFirst.setToolTip(_translate("Tuplot", "First Timestep"))
        self.btnFirst.setText(_translate("Tuplot", "|<"))
        self.btn2dLock.setToolTip(_translate("Tuplot", "Lock Timesteps to Map Outputs"))
        self.btn2dLock.setText(_translate("Tuplot", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TimeSeriesTab), _translate("Tuplot", "Time Series"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LongPlotTab), _translate("Tuplot", "Cross Section / Long Profile"))
        self.textEdit.setHtml(_translate("Tuplot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">TODO</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Coming Soon..</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CrossSectionTab), _translate("Tuplot", "1D Cross Section Viewer"))

from tuflow.dataset_view import DataSetView
import tuflow.resources.TUFLOW_logo_rc
