# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_animation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnimationDialog(object):
    def setupUi(self, AnimationDialog):
        AnimationDialog.setObjectName("AnimationDialog")
        AnimationDialog.resize(583, 550)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(AnimationDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(AnimationDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cboStart = QtWidgets.QComboBox(self.tab)
        self.cboStart.setObjectName("cboStart")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cboStart)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cboEnd = QtWidgets.QComboBox(self.tab)
        self.cboEnd.setObjectName("cboEnd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cboEnd)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cboResult = QtWidgets.QComboBox(self.tab)
        self.cboResult.setObjectName("cboResult")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cboResult)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cboScalar = QtWidgets.QComboBox(self.tab)
        self.cboScalar.setObjectName("cboScalar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cboScalar)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cboVector = QtWidgets.QComboBox(self.tab)
        self.cboVector.setObjectName("cboVector")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cboVector)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinWidth = QtWidgets.QSpinBox(self.tab)
        self.spinWidth.setMinimum(16)
        self.spinWidth.setMaximum(9999)
        self.spinWidth.setProperty("value", 1920)
        self.spinWidth.setObjectName("spinWidth")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinWidth)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinHeight = QtWidgets.QSpinBox(self.tab)
        self.spinHeight.setMinimum(16)
        self.spinHeight.setMaximum(9999)
        self.spinHeight.setProperty("value", 1080)
        self.spinHeight.setObjectName("spinHeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinHeight)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinSpeed = QtWidgets.QSpinBox(self.tab)
        self.spinSpeed.setMinimum(1)
        self.spinSpeed.setMaximum(60)
        self.spinSpeed.setProperty("value", 5)
        self.spinSpeed.setObjectName("spinSpeed")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinSpeed)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editOutput = QtWidgets.QLineEdit(self.tab)
        self.editOutput.setObjectName("editOutput")
        self.horizontalLayout.addWidget(self.editOutput)
        self.btnBrowseOutput = QtWidgets.QToolButton(self.tab)
        self.btnBrowseOutput.setObjectName("btnBrowseOutput")
        self.horizontalLayout.addWidget(self.btnBrowseOutput)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radLayoutDefault = QtWidgets.QRadioButton(self.tab_2)
        self.radLayoutDefault.setChecked(True)
        self.radLayoutDefault.setObjectName("radLayoutDefault")
        self.verticalLayout_5.addWidget(self.radLayoutDefault)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 488, 1125))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupTitle = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupTitle.setCheckable(True)
        self.groupTitle.setChecked(False)
        self.groupTitle.setObjectName("groupTitle")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupTitle)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupTitle)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.cboPosTitle = QtWidgets.QComboBox(self.groupTitle)
        self.cboPosTitle.setObjectName("cboPosTitle")
        self.cboPosTitle.addItem("")
        self.cboPosTitle.addItem("")
        self.cboPosTitle.addItem("")
        self.cboPosTitle.addItem("")
        self.cboPosTitle.addItem("")
        self.cboPosTitle.addItem("")
        self.gridLayout_5.addWidget(self.cboPosTitle, 4, 1, 1, 2)
        self.fbtnTitle = QgsFontButton(self.groupTitle)
        self.fbtnTitle.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fbtnTitle.setFont(font)
        self.fbtnTitle.setMode(QgsFontButton.ModeQFont)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fbtnTitle.setCurrentFont(font)
        self.fbtnTitle.setObjectName("fbtnTitle")
        self.gridLayout_5.addWidget(self.fbtnTitle, 1, 1, 1, 2)
        self.colorTitleText = QgsColorButton(self.groupTitle)
        self.colorTitleText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTitleText.setColor(QtGui.QColor(0, 0, 0))
        self.colorTitleText.setShowNoColor(True)
        self.colorTitleText.setObjectName("colorTitleText")
        self.gridLayout_5.addWidget(self.colorTitleText, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupTitle)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 4, 0, 1, 1)
        self.colorTitleBackground = QgsColorButton(self.groupTitle)
        self.colorTitleBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTitleBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorTitleBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorTitleBackground.setShowNoColor(True)
        self.colorTitleBackground.setObjectName("colorTitleBackground")
        self.gridLayout_5.addWidget(self.colorTitleBackground, 2, 4, 1, 1)
        self.labelTitle = QtWidgets.QLineEdit(self.groupTitle)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout_5.addWidget(self.labelTitle, 0, 1, 1, 4)
        self.cbTitleBackground = QtWidgets.QCheckBox(self.groupTitle)
        self.cbTitleBackground.setObjectName("cbTitleBackground")
        self.gridLayout_5.addWidget(self.cbTitleBackground, 2, 0, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.groupTitle)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.cbTitleFrame = QtWidgets.QCheckBox(self.groupTitle)
        self.cbTitleFrame.setObjectName("cbTitleFrame")
        self.gridLayout_5.addWidget(self.cbTitleFrame, 3, 0, 1, 4)
        self.colorTitleFrame = QgsColorButton(self.groupTitle)
        self.colorTitleFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTitleFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorTitleFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorTitleFrame.setObjectName("colorTitleFrame")
        self.gridLayout_5.addWidget(self.colorTitleFrame, 3, 4, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 10)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addWidget(self.groupTitle)
        self.groupTime = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupTime.setCheckable(True)
        self.groupTime.setChecked(False)
        self.groupTime.setObjectName("groupTime")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupTime)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.colorTimeBackground = QgsColorButton(self.groupTime)
        self.colorTimeBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTimeBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorTimeBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorTimeBackground.setObjectName("colorTimeBackground")
        self.gridLayout_6.addWidget(self.colorTimeBackground, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 2, 1, 1)
        self.fbtnTime = QgsFontButton(self.groupTime)
        self.fbtnTime.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fbtnTime.setFont(font)
        self.fbtnTime.setMode(QgsFontButton.ModeQFont)
        self.fbtnTime.setObjectName("fbtnTime")
        self.gridLayout_6.addWidget(self.fbtnTime, 1, 1, 1, 1)
        self.cbTimeBackground = QtWidgets.QCheckBox(self.groupTime)
        self.cbTimeBackground.setObjectName("cbTimeBackground")
        self.gridLayout_6.addWidget(self.cbTimeBackground, 2, 0, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.groupTime)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupTime)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.cboPosTime = QtWidgets.QComboBox(self.groupTime)
        self.cboPosTime.setObjectName("cboPosTime")
        self.cboPosTime.addItem("")
        self.cboPosTime.addItem("")
        self.cboPosTime.addItem("")
        self.cboPosTime.addItem("")
        self.cboPosTime.addItem("")
        self.cboPosTime.addItem("")
        self.gridLayout_6.addWidget(self.cboPosTime, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupTime)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 4, 0, 1, 1)
        self.colorTimeText = QgsColorButton(self.groupTime)
        self.colorTimeText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTimeText.setColor(QtGui.QColor(0, 0, 0))
        self.colorTimeText.setObjectName("colorTimeText")
        self.gridLayout_6.addWidget(self.colorTimeText, 1, 3, 1, 1)
        self.labelTime = QtWidgets.QLineEdit(self.groupTime)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout_6.addWidget(self.labelTime, 0, 1, 1, 3)
        self.cbTimeFrame = QtWidgets.QCheckBox(self.groupTime)
        self.cbTimeFrame.setObjectName("cbTimeFrame")
        self.gridLayout_6.addWidget(self.cbTimeFrame, 3, 0, 1, 3)
        self.colorTimeFrame = QgsColorButton(self.groupTime)
        self.colorTimeFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorTimeFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorTimeFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorTimeFrame.setObjectName("colorTimeFrame")
        self.gridLayout_6.addWidget(self.colorTimeFrame, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayout_4.addWidget(self.groupTime)
        self.groupLegend = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupLegend.setCheckable(True)
        self.groupLegend.setChecked(False)
        self.groupLegend.setObjectName("groupLegend")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupLegend)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.groupLegend)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 4, 0, 1, 1)
        self.cboPosLegend = QtWidgets.QComboBox(self.groupLegend)
        self.cboPosLegend.setObjectName("cboPosLegend")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.cboPosLegend.addItem("")
        self.gridLayout_7.addWidget(self.cboPosLegend, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupLegend)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.colorLegendText = QgsColorButton(self.groupLegend)
        self.colorLegendText.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendText.setColor(QtGui.QColor(0, 0, 0))
        self.colorLegendText.setObjectName("colorLegendText")
        self.gridLayout_7.addWidget(self.colorLegendText, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupLegend)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.cbLegendBackground = QtWidgets.QCheckBox(self.groupLegend)
        self.cbLegendBackground.setObjectName("cbLegendBackground")
        self.gridLayout_7.addWidget(self.cbLegendBackground, 2, 0, 1, 3)
        self.labelLegend = QtWidgets.QLineEdit(self.groupLegend)
        self.labelLegend.setObjectName("labelLegend")
        self.gridLayout_7.addWidget(self.labelLegend, 0, 1, 1, 3)
        self.colorLegendBackground = QgsColorButton(self.groupLegend)
        self.colorLegendBackground.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendBackground.setColor(QtGui.QColor(255, 255, 255))
        self.colorLegendBackground.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.colorLegendBackground.setObjectName("colorLegendBackground")
        self.gridLayout_7.addWidget(self.colorLegendBackground, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 2, 1, 1)
        self.fbtnLegend = QgsFontButton(self.groupLegend)
        self.fbtnLegend.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fbtnLegend.setFont(font)
        self.fbtnLegend.setMode(QgsFontButton.ModeQFont)
        self.fbtnLegend.setObjectName("fbtnLegend")
        self.gridLayout_7.addWidget(self.fbtnLegend, 1, 1, 1, 1)
        self.cbLegendFrame = QtWidgets.QCheckBox(self.groupLegend)
        self.cbLegendFrame.setObjectName("cbLegendFrame")
        self.gridLayout_7.addWidget(self.cbLegendFrame, 3, 0, 1, 3)
        self.colorLegendFrame = QgsColorButton(self.groupLegend)
        self.colorLegendFrame.setMinimumSize(QtCore.QSize(24, 21))
        self.colorLegendFrame.setColor(QtGui.QColor(0, 0, 0))
        self.colorLegendFrame.setDefaultColor(QtGui.QColor(0, 0, 0))
        self.colorLegendFrame.setObjectName("colorLegendFrame")
        self.gridLayout_7.addWidget(self.colorLegendFrame, 3, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.verticalLayout_4.addWidget(self.groupLegend)
        self.groupPlot = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupPlot.setCheckable(True)
        self.groupPlot.setChecked(False)
        self.groupPlot.setCollapsed(False)
        self.groupPlot.setObjectName("groupPlot")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupPlot)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnPlotUp = QtWidgets.QToolButton(self.groupPlot)
        self.btnPlotUp.setObjectName("btnPlotUp")
        self.gridLayout_4.addWidget(self.btnPlotUp, 0, 2, 1, 1)
        self.btnAddPlot = QtWidgets.QToolButton(self.groupPlot)
        self.btnAddPlot.setObjectName("btnAddPlot")
        self.gridLayout_4.addWidget(self.btnAddPlot, 0, 0, 1, 1)
        self.btnRemovePlot = QtWidgets.QToolButton(self.groupPlot)
        self.btnRemovePlot.setObjectName("btnRemovePlot")
        self.gridLayout_4.addWidget(self.btnRemovePlot, 0, 1, 1, 1)
        self.tablePlots = QtWidgets.QTableWidget(self.groupPlot)
        self.tablePlots.setMinimumSize(QtCore.QSize(0, 150))
        self.tablePlots.setObjectName("tablePlots")
        self.tablePlots.setColumnCount(4)
        self.tablePlots.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePlots.setHorizontalHeaderItem(3, item)
        self.tablePlots.horizontalHeader().setVisible(False)
        self.tablePlots.horizontalHeader().setCascadingSectionResizes(False)
        self.tablePlots.horizontalHeader().setDefaultSectionSize(110)
        self.tablePlots.horizontalHeader().setMinimumSectionSize(80)
        self.tablePlots.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_4.addWidget(self.tablePlots, 1, 0, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 4, 1, 1)
        self.btnPlotDown = QtWidgets.QToolButton(self.groupPlot)
        self.btnPlotDown.setObjectName("btnPlotDown")
        self.gridLayout_4.addWidget(self.btnPlotDown, 0, 3, 1, 1)
        self.tableGraphics = QtWidgets.QTableWidget(self.groupPlot)
        self.tableGraphics.setMinimumSize(QtCore.QSize(0, 150))
        self.tableGraphics.setObjectName("tableGraphics")
        self.tableGraphics.setColumnCount(4)
        self.tableGraphics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGraphics.setHorizontalHeaderItem(3, item)
        self.tableGraphics.horizontalHeader().setVisible(False)
        self.tableGraphics.horizontalHeader().setDefaultSectionSize(110)
        self.tableGraphics.verticalHeader().setDefaultSectionSize(20)
        self.tableGraphics.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.tableGraphics, 3, 0, 1, 5)
        self.label_23 = QtWidgets.QLabel(self.groupPlot)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 5)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.groupPlot)
        self.groupImages = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupImages.setCheckable(True)
        self.groupImages.setChecked(False)
        self.groupImages.setCollapsed(False)
        self.groupImages.setObjectName("groupImages")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupImages)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnImageUp = QtWidgets.QToolButton(self.groupImages)
        self.btnImageUp.setObjectName("btnImageUp")
        self.gridLayout_3.addWidget(self.btnImageUp, 0, 2, 1, 1)
        self.btnRemoveImage = QtWidgets.QToolButton(self.groupImages)
        self.btnRemoveImage.setObjectName("btnRemoveImage")
        self.gridLayout_3.addWidget(self.btnRemoveImage, 0, 1, 1, 1)
        self.btnAddImage = QtWidgets.QToolButton(self.groupImages)
        self.btnAddImage.setObjectName("btnAddImage")
        self.gridLayout_3.addWidget(self.btnAddImage, 0, 0, 1, 1)
        self.btnImageDown = QtWidgets.QToolButton(self.groupImages)
        self.btnImageDown.setObjectName("btnImageDown")
        self.gridLayout_3.addWidget(self.btnImageDown, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 4, 1, 1)
        self.tableImages = QtWidgets.QTableWidget(self.groupImages)
        self.tableImages.setMinimumSize(QtCore.QSize(0, 150))
        self.tableImages.setObjectName("tableImages")
        self.tableImages.setColumnCount(3)
        self.tableImages.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(2, item)
        self.tableImages.horizontalHeader().setDefaultSectionSize(130)
        self.tableImages.horizontalHeader().setMinimumSectionSize(39)
        self.tableImages.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_3.addWidget(self.tableImages, 1, 0, 1, 5)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.groupImages)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.radLayoutCustom = QtWidgets.QRadioButton(self.tab_2)
        self.radLayoutCustom.setObjectName("radLayoutCustom")
        self.verticalLayout_5.addWidget(self.radLayoutCustom)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnBrowseTemplate = QtWidgets.QToolButton(self.tab_2)
        self.btnBrowseTemplate.setObjectName("btnBrowseTemplate")
        self.gridLayout_2.addWidget(self.btnBrowseTemplate, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.editTemplate = QtWidgets.QLineEdit(self.tab_2)
        self.editTemplate.setObjectName("editTemplate")
        self.gridLayout_2.addWidget(self.editTemplate, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 1, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.radQualBest = QtWidgets.QRadioButton(self.tab_3)
        self.radQualBest.setChecked(False)
        self.radQualBest.setObjectName("radQualBest")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radQualBest)
        self.radQualHigh = QtWidgets.QRadioButton(self.tab_3)
        self.radQualHigh.setChecked(True)
        self.radQualHigh.setObjectName("radQualHigh")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radQualHigh)
        self.radQualLow = QtWidgets.QRadioButton(self.tab_3)
        self.radQualLow.setObjectName("radQualLow")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radQualLow)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBrowseFfmpegPath = QtWidgets.QToolButton(self.groupBox)
        self.btnBrowseFfmpegPath.setObjectName("btnBrowseFfmpegPath")
        self.gridLayout.addWidget(self.btnBrowseFfmpegPath, 3, 2, 1, 1)
        self.editFfmpegPath = QtWidgets.QLineEdit(self.groupBox)
        self.editFfmpegPath.setObjectName("editFfmpegPath")
        self.gridLayout.addWidget(self.editFfmpegPath, 3, 1, 1, 1)
        self.radFfmpegCustom = QtWidgets.QRadioButton(self.groupBox)
        self.radFfmpegCustom.setObjectName("radFfmpegCustom")
        self.gridLayout.addWidget(self.radFfmpegCustom, 3, 0, 1, 1)
        self.radFfmpegSystem = QtWidgets.QRadioButton(self.groupBox)
        self.radFfmpegSystem.setChecked(True)
        self.radFfmpegSystem.setObjectName("radFfmpegSystem")
        self.gridLayout.addWidget(self.radFfmpegSystem, 2, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 3)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progress = QtWidgets.QProgressBar(AnimationDialog)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.horizontalLayout_4.addWidget(self.progress)
        self.pbPreview = QtWidgets.QPushButton(AnimationDialog)
        self.pbPreview.setObjectName("pbPreview")
        self.horizontalLayout_4.addWidget(self.pbPreview)
        self.buttonBox = QtWidgets.QDialogButtonBox(AnimationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(AnimationDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(AnimationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AnimationDialog)

    def retranslateUi(self, AnimationDialog):
        _translate = QtCore.QCoreApplication.translate
        AnimationDialog.setWindowTitle(_translate("AnimationDialog", "Export Animation"))
        self.label_6.setText(_translate("AnimationDialog", "Start Time"))
        self.label_7.setText(_translate("AnimationDialog", "End Time"))
        self.label_13.setText(_translate("AnimationDialog", "Result"))
        self.label_11.setText(_translate("AnimationDialog", "Active Scalar Result"))
        self.label_12.setText(_translate("AnimationDialog", "Active Vector Result"))
        self.label_2.setText(_translate("AnimationDialog", "Width"))
        self.spinWidth.setSuffix(_translate("AnimationDialog", " px"))
        self.label_3.setText(_translate("AnimationDialog", "Height"))
        self.spinHeight.setSuffix(_translate("AnimationDialog", " px"))
        self.label_8.setText(_translate("AnimationDialog", "Speed"))
        self.spinSpeed.setSuffix(_translate("AnimationDialog", " fps"))
        self.label.setText(_translate("AnimationDialog", "Output"))
        self.btnBrowseOutput.setText(_translate("AnimationDialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AnimationDialog", "General"))
        self.radLayoutDefault.setText(_translate("AnimationDialog", "Default layout"))
        self.groupTitle.setTitle(_translate("AnimationDialog", "Title"))
        self.label_14.setText(_translate("AnimationDialog", "Label"))
        self.cboPosTitle.setItemText(0, _translate("AnimationDialog", "Top-Left"))
        self.cboPosTitle.setItemText(1, _translate("AnimationDialog", "Top-Right"))
        self.cboPosTitle.setItemText(2, _translate("AnimationDialog", "Bottom-Left"))
        self.cboPosTitle.setItemText(3, _translate("AnimationDialog", "Bottom-Right"))
        self.cboPosTitle.setItemText(4, _translate("AnimationDialog", "Top-Center"))
        self.cboPosTitle.setItemText(5, _translate("AnimationDialog", "Bottom-Center"))
        self.fbtnTitle.setText(_translate("AnimationDialog", "Font . . ."))
        self.label_17.setText(_translate("AnimationDialog", "Position"))
        self.cbTitleBackground.setText(_translate("AnimationDialog", "Background"))
        self.label_15.setText(_translate("AnimationDialog", "Text"))
        self.cbTitleFrame.setText(_translate("AnimationDialog", "Border"))
        self.groupTime.setTitle(_translate("AnimationDialog", "Time"))
        self.fbtnTime.setText(_translate("AnimationDialog", "Font . . ."))
        self.cbTimeBackground.setText(_translate("AnimationDialog", "Background"))
        self.label_18.setText(_translate("AnimationDialog", "Text"))
        self.label_16.setText(_translate("AnimationDialog", "Label"))
        self.cboPosTime.setItemText(0, _translate("AnimationDialog", "Top-Left"))
        self.cboPosTime.setItemText(1, _translate("AnimationDialog", "Top-Right"))
        self.cboPosTime.setItemText(2, _translate("AnimationDialog", "Bottom-Left"))
        self.cboPosTime.setItemText(3, _translate("AnimationDialog", "Bottom-Right"))
        self.cboPosTime.setItemText(4, _translate("AnimationDialog", "Top-Center"))
        self.cboPosTime.setItemText(5, _translate("AnimationDialog", "Bottom-Center"))
        self.label_19.setText(_translate("AnimationDialog", "Position"))
        self.cbTimeFrame.setText(_translate("AnimationDialog", "Border"))
        self.groupLegend.setTitle(_translate("AnimationDialog", "Legend"))
        self.label_22.setText(_translate("AnimationDialog", "Position"))
        self.cboPosLegend.setItemText(0, _translate("AnimationDialog", "Top-Left"))
        self.cboPosLegend.setItemText(1, _translate("AnimationDialog", "Top-Right"))
        self.cboPosLegend.setItemText(2, _translate("AnimationDialog", "Bottom-Left"))
        self.cboPosLegend.setItemText(3, _translate("AnimationDialog", "Bottom-Right"))
        self.cboPosLegend.setItemText(4, _translate("AnimationDialog", "Top-Center"))
        self.cboPosLegend.setItemText(5, _translate("AnimationDialog", "Bottom-Center"))
        self.label_20.setText(_translate("AnimationDialog", "Label"))
        self.label_21.setText(_translate("AnimationDialog", "Text"))
        self.cbLegendBackground.setText(_translate("AnimationDialog", "Background"))
        self.fbtnLegend.setText(_translate("AnimationDialog", "Font . . ."))
        self.cbLegendFrame.setText(_translate("AnimationDialog", "Border"))
        self.groupPlot.setTitle(_translate("AnimationDialog", "Plots"))
        self.btnPlotUp.setText(_translate("AnimationDialog", "..."))
        self.btnAddPlot.setText(_translate("AnimationDialog", "..."))
        self.btnRemovePlot.setText(_translate("AnimationDialog", "..."))
        item = self.tablePlots.horizontalHeaderItem(0)
        item.setText(_translate("AnimationDialog", "Plot Type"))
        item = self.tablePlots.horizontalHeaderItem(1)
        item.setText(_translate("AnimationDialog", "Plot Items"))
        item = self.tablePlots.horizontalHeaderItem(2)
        item.setText(_translate("AnimationDialog", "Position"))
        item = self.tablePlots.horizontalHeaderItem(3)
        item.setText(_translate("AnimationDialog", "Properties"))
        self.btnPlotDown.setText(_translate("AnimationDialog", "..."))
        item = self.tableGraphics.horizontalHeaderItem(0)
        item.setText(_translate("AnimationDialog", "ID"))
        item = self.tableGraphics.horizontalHeaderItem(1)
        item.setText(_translate("AnimationDialog", "User Label"))
        item = self.tableGraphics.horizontalHeaderItem(2)
        item.setText(_translate("AnimationDialog", "Label Position"))
        item = self.tableGraphics.horizontalHeaderItem(3)
        item.setText(_translate("AnimationDialog", "Properties"))
        self.label_23.setText(_translate("AnimationDialog", "Graphics"))
        self.groupImages.setTitle(_translate("AnimationDialog", "Images"))
        self.btnImageUp.setText(_translate("AnimationDialog", "..."))
        self.btnRemoveImage.setText(_translate("AnimationDialog", "..."))
        self.btnAddImage.setText(_translate("AnimationDialog", "..."))
        self.btnImageDown.setText(_translate("AnimationDialog", "..."))
        item = self.tableImages.horizontalHeaderItem(0)
        item.setText(_translate("AnimationDialog", "Image"))
        item = self.tableImages.horizontalHeaderItem(1)
        item.setText(_translate("AnimationDialog", "Position"))
        item = self.tableImages.horizontalHeaderItem(2)
        item.setText(_translate("AnimationDialog", "Properties"))
        self.radLayoutCustom.setText(_translate("AnimationDialog", "Custom layout (QGIS Print Layout.qpt)"))
        self.btnBrowseTemplate.setText(_translate("AnimationDialog", "..."))
        self.label_5.setText(_translate("AnimationDialog", "Template"))
        self.label_10.setText(_translate("AnimationDialog", "(Note: label with ID \'time\' will display output time)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AnimationDialog", "Layout"))
        self.label_4.setText(_translate("AnimationDialog", "Quality"))
        self.radQualBest.setText(_translate("AnimationDialog", "Best (lossless)"))
        self.radQualHigh.setText(_translate("AnimationDialog", "High"))
        self.radQualLow.setText(_translate("AnimationDialog", "Low"))
        self.btnBrowseFfmpegPath.setText(_translate("AnimationDialog", "..."))
        self.radFfmpegCustom.setText(_translate("AnimationDialog", "custom"))
        self.radFfmpegSystem.setText(_translate("AnimationDialog", "default from system path"))
        self.label_9.setText(_translate("AnimationDialog", "Video encoding utility (FFmpeg) to use:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AnimationDialog", "Video"))
        self.pbPreview.setText(_translate("AnimationDialog", "Preview"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgscolorbutton import QgsColorButton
from qgsfontbutton import QgsFontButton
