# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ellis.Symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\ui_tuflowqgis_TuOptionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TuViewOptions(object):
    def setupUi(self, TuViewOptions):
        TuViewOptions.setObjectName("TuViewOptions")
        TuViewOptions.resize(363, 515)
        self.verticalLayout = QtWidgets.QVBoxLayout(TuViewOptions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.cbShowTriangles = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbShowTriangles.setObjectName("cbShowTriangles")
        self.gridLayout.addWidget(self.cbShowTriangles, 0, 1, 1, 1)
        self.cbShowGrid = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbShowGrid.setObjectName("cbShowGrid")
        self.gridLayout.addWidget(self.cbShowGrid, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.rbLiveCursorTrackingOff = QtWidgets.QRadioButton(self.groupBox)
        self.rbLiveCursorTrackingOff.setObjectName("rbLiveCursorTrackingOff")
        self.LiveCursorTracking = QtWidgets.QButtonGroup(TuViewOptions)
        self.LiveCursorTracking.setObjectName("LiveCursorTracking")
        self.LiveCursorTracking.addButton(self.rbLiveCursorTrackingOff)
        self.gridLayout_2.addWidget(self.rbLiveCursorTrackingOff, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.rbLiveCursorTrackingOn = QtWidgets.QRadioButton(self.groupBox)
        self.rbLiveCursorTrackingOn.setChecked(True)
        self.rbLiveCursorTrackingOn.setObjectName("rbLiveCursorTrackingOn")
        self.LiveCursorTracking.addButton(self.rbLiveCursorTrackingOn)
        self.gridLayout_2.addWidget(self.rbLiveCursorTrackingOn, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.cbDates = QtWidgets.QCheckBox(self.groupBox)
        self.cbDates.setObjectName("cbDates")
        self.gridLayout_2.addWidget(self.cbDates, 2, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 2)
        self.datePreview = QtWidgets.QLabel(self.groupBox)
        self.datePreview.setText("")
        self.datePreview.setObjectName("datePreview")
        self.gridLayout_2.addWidget(self.datePreview, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 3)
        self.dteZeroDate = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dteZeroDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dteZeroDate.setCalendarPopup(True)
        self.dteZeroDate.setObjectName("dteZeroDate")
        self.gridLayout_2.addWidget(self.dteZeroDate, 5, 2, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 6, 4, 1, 2)
        self.leDateFormat = QtWidgets.QLineEdit(self.groupBox)
        self.leDateFormat.setObjectName("leDateFormat")
        self.gridLayout_2.addWidget(self.leDateFormat, 4, 2, 1, 4)
        self.sbXAxisLabelRotation = QtWidgets.QSpinBox(self.groupBox)
        self.sbXAxisLabelRotation.setMinimum(-359)
        self.sbXAxisLabelRotation.setMaximum(359)
        self.sbXAxisLabelRotation.setObjectName("sbXAxisLabelRotation")
        self.gridLayout_2.addWidget(self.sbXAxisLabelRotation, 6, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sbPlaySpeed = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sbPlaySpeed.setDecimals(1)
        self.sbPlaySpeed.setMinimum(0.1)
        self.sbPlaySpeed.setProperty("value", 1.0)
        self.sbPlaySpeed.setObjectName("sbPlaySpeed")
        self.gridLayout_3.addWidget(self.sbPlaySpeed, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sbResolution = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sbResolution.setDecimals(1)
        self.sbResolution.setMinimum(0.1)
        self.sbResolution.setProperty("value", 1.0)
        self.sbResolution.setObjectName("sbResolution")
        self.gridLayout_4.addWidget(self.sbResolution, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(TuViewOptions)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.rbARRNextHigher = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbARRNextHigher.setChecked(True)
        self.rbARRNextHigher.setObjectName("rbARRNextHigher")
        self.MeanSelection = QtWidgets.QButtonGroup(TuViewOptions)
        self.MeanSelection.setObjectName("MeanSelection")
        self.MeanSelection.addButton(self.rbARRNextHigher)
        self.gridLayout_5.addWidget(self.rbARRNextHigher, 0, 1, 1, 1)
        self.rbARRClosest = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbARRClosest.setObjectName("rbARRClosest")
        self.MeanSelection.addButton(self.rbARRClosest)
        self.gridLayout_5.addWidget(self.rbARRClosest, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(TuViewOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TuViewOptions)
        self.buttonBox.accepted.connect(TuViewOptions.accept)
        self.buttonBox.rejected.connect(TuViewOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(TuViewOptions)

    def retranslateUi(self, TuViewOptions):
        _translate = QtCore.QCoreApplication.translate
        TuViewOptions.setWindowTitle(_translate("TuViewOptions", "Settings"))
        self.groupBox_5.setTitle(_translate("TuViewOptions", "Mesh Rendering"))
        self.cbShowTriangles.setText(_translate("TuViewOptions", "Show Triangles"))
        self.cbShowGrid.setText(_translate("TuViewOptions", "Show Grid"))
        self.groupBox.setTitle(_translate("TuViewOptions", "Plotting"))
        self.label.setText(_translate("TuViewOptions", "Live Map Tracking:"))
        self.rbLiveCursorTrackingOff.setText(_translate("TuViewOptions", "Off"))
        self.rbLiveCursorTrackingOn.setText(_translate("TuViewOptions", "On"))
        self.cbDates.setText(_translate("TuViewOptions", "Display Time Series X-Axis as Dates:"))
        self.label_6.setText(_translate("TuViewOptions", "Display Format: "))
        self.label_5.setText(_translate("TuViewOptions", "Zero Date:"))
        self.label_7.setText(_translate("TuViewOptions", "Preview: "))
        self.label_8.setText(_translate("TuViewOptions", "X-Axis Label Rotation (deg):"))
        self.leDateFormat.setText(_translate("TuViewOptions", "DD/MM/YYYY hh:mm:ss"))
        self.groupBox_3.setTitle(_translate("TuViewOptions", "Auto Play"))
        self.label_3.setText(_translate("TuViewOptions", "Auto Play Speed (sec)"))
        self.groupBox_4.setTitle(_translate("TuViewOptions", "Cross Section and Flux Line"))
        self.label_4.setText(_translate("TuViewOptions", "Resolution (map units)"))
        self.groupBox_2.setTitle(_translate("TuViewOptions", "ARR2016"))
        self.label_2.setText(_translate("TuViewOptions", "Mean Event Selection:"))
        self.rbARRNextHigher.setText(_translate("TuViewOptions", "Next higher"))
        self.rbARRClosest.setText(_translate("TuViewOptions", "Closest"))

