# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow_catch\ui\ui_increment_file_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

from ..compatibility_routines import QT_RICH_TEXT, QT_BUTTON_BOX_CANCEL, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM, QT_BUTTON_BOX_OK, QT_HORIZONTAL


class Ui_IncrementFileDialog(object):
    def setupUi(self, IncrementFileDialog):
        IncrementFileDialog.setObjectName("IncrementFileDialog")
        IncrementFileDialog.resize(536, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(IncrementFileDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(IncrementFileDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 516, 340))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QT_HORIZONTAL)
        self.splitter.setObjectName("splitter")
        self.main_widget = QtWidgets.QWidget(self.splitter)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.output_folder_label = QtWidgets.QLabel(self.main_widget)
        self.output_folder_label.setObjectName("output_folder_label")
        self.verticalLayout_3.addWidget(self.output_folder_label)
        self.output_folder_err_txt = QtWidgets.QLabel(self.main_widget)
        self.output_folder_err_txt.setTextFormat(QT_RICH_TEXT)
        self.output_folder_err_txt.setWordWrap(True)
        self.output_folder_err_txt.setObjectName("output_folder_err_txt")
        self.verticalLayout_3.addWidget(self.output_folder_err_txt)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_folder_line_edit = QtWidgets.QLineEdit(self.main_widget)
        self.output_folder_line_edit.setObjectName("output_folder_line_edit")
        self.horizontalLayout.addWidget(self.output_folder_line_edit)
        self.output_folder_browse_btn = QtWidgets.QToolButton(self.main_widget)
        self.output_folder_browse_btn.setObjectName("output_folder_browse_btn")
        self.horizontalLayout.addWidget(self.output_folder_browse_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.output_name_label = QtWidgets.QLabel(self.main_widget)
        self.output_name_label.setObjectName("output_name_label")
        self.verticalLayout_3.addWidget(self.output_name_label)
        self.output_name_err_txt = QtWidgets.QLabel(self.main_widget)
        self.output_name_err_txt.setTextFormat(QT_RICH_TEXT)
        self.output_name_err_txt.setWordWrap(True)
        self.output_name_err_txt.setObjectName("output_name_err_txt")
        self.verticalLayout_3.addWidget(self.output_name_err_txt)
        self.output_name_line_edit = QtWidgets.QLineEdit(self.main_widget)
        self.output_name_line_edit.setObjectName("output_name_line_edit")
        self.verticalLayout_3.addWidget(self.output_name_line_edit)
        self.remove_old_layer_rb = QtWidgets.QRadioButton(self.main_widget)
        self.remove_old_layer_rb.setChecked(True)
        self.remove_old_layer_rb.setObjectName("remove_old_layer_rb")
        self.buttonGroup = QtWidgets.QButtonGroup(IncrementFileDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.remove_old_layer_rb)
        self.verticalLayout_3.addWidget(self.remove_old_layer_rb)
        self.keep_old_layer_rb = QtWidgets.QRadioButton(self.main_widget)
        self.keep_old_layer_rb.setObjectName("keep_old_layer_rb")
        self.buttonGroup.addButton(self.keep_old_layer_rb)
        self.verticalLayout_3.addWidget(self.keep_old_layer_rb)
        spacerItem = QtWidgets.QSpacerItem(20, 106, QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING)
        self.verticalLayout_3.addItem(spacerItem)
        self.html_help = QtWidgets.QTextBrowser(self.splitter)
        self.html_help.setObjectName("html_help")
        self.verticalLayout_2.addWidget(self.splitter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(IncrementFileDialog)
        self.buttonBox.setOrientation(QT_HORIZONTAL)
        self.buttonBox.setStandardButtons(QT_BUTTON_BOX_CANCEL|QT_BUTTON_BOX_OK)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(IncrementFileDialog)
        self.buttonBox.accepted.connect(IncrementFileDialog.accept)
        self.buttonBox.rejected.connect(IncrementFileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(IncrementFileDialog)

    def retranslateUi(self, IncrementFileDialog):
        _translate = QtCore.QCoreApplication.translate
        IncrementFileDialog.setWindowTitle(_translate("IncrementFileDialog", "Increment Layer"))
        self.output_folder_label.setText(_translate("IncrementFileDialog", "Output Folder"))
        self.output_folder_err_txt.setText(_translate("IncrementFileDialog", "TextLabel"))
        self.output_folder_line_edit.setToolTip(_translate("IncrementFileDialog", "Output folder location"))
        self.output_folder_line_edit.setPlaceholderText(_translate("IncrementFileDialog", "[Output Folder]"))
        self.output_folder_browse_btn.setText(_translate("IncrementFileDialog", "..."))
        self.output_name_label.setText(_translate("IncrementFileDialog", "Output Name"))
        self.output_name_err_txt.setText(_translate("IncrementFileDialog", "TextLabel"))
        self.output_name_line_edit.setToolTip(_translate("IncrementFileDialog", "Name of output file - extension not required"))
        self.output_name_line_edit.setPlaceholderText(_translate("IncrementFileDialog", "[Output Name]"))
        self.remove_old_layer_rb.setText(_translate("IncrementFileDialog", "Remove old layer"))
        self.keep_old_layer_rb.setText(_translate("IncrementFileDialog", "Keep old layer"))
