# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\plot_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

if not QtCore.QSettings().value('TUFLOW/TestCase', False, type=bool):
    from ....compatibility_routines import QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM
else:
    from tuflow.compatibility_routines import QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM


class Ui_TVPlotWidget(object):
    def setupUi(self, TVPlotWidget):
        TVPlotWidget.setObjectName("TVPlotWidget")
        TVPlotWidget.resize(360, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(TVPlotWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbar = TVPlotToolBar(TVPlotWidget)
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout.addWidget(self.toolbar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem)
        self.plot_linker = ClickableIcon(TVPlotWidget)
        self.plot_linker.setObjectName("plot_linker")
        self.horizontalLayout.addWidget(self.plot_linker)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.plot_graph = CustomPlotWidget(TVPlotWidget)
        self.plot_graph.setObjectName("plot_graph")
        self.verticalLayout_2.addWidget(self.plot_graph)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(TVPlotWidget)
        QtCore.QMetaObject.connectSlotsByName(TVPlotWidget)

    def retranslateUi(self, TVPlotWidget):
        _translate = QtCore.QCoreApplication.translate
        TVPlotWidget.setWindowTitle(_translate("TVPlotWidget", "Form"))
from ..clickable_icon import ClickableIcon
from .pyqtgraph_subclass.custom_plot_widget import CustomPlotWidget
from ..tv_plot_toolbar import TVPlotToolBar
