# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\forms\refh2_dock.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_refh2(object):
    def setupUi(self, refh2):
        refh2.setObjectName("refh2")
        refh2.resize(571, 888)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 534, 1770))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/logo/TUFLOW_logo_resized.png"))
        self.label_26.setScaledContents(False)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_51.addWidget(self.label_26)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setOpenExternalLinks(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_51.addWidget(self.label_24)
        self.verticalLayout_17.addLayout(self.horizontalLayout_51)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox_2.setCollapsed(False)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnInputXML = QtWidgets.QToolButton(self.mGroupBox_2)
        self.btnInputXML.setObjectName("btnInputXML")
        self.horizontalLayout_4.addWidget(self.btnInputXML)
        self.leInputXML = QtWidgets.QLineEdit(self.mGroupBox_2)
        self.leInputXML.setObjectName("leInputXML")
        self.horizontalLayout_4.addWidget(self.leInputXML)
        self.verticalLayout_22.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_22)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rbEngland = QtWidgets.QRadioButton(self.mGroupBox_2)
        self.rbEngland.setChecked(True)
        self.rbEngland.setObjectName("rbEngland")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbEngland)
        self.horizontalLayout_5.addWidget(self.rbEngland)
        self.rbScotland = QtWidgets.QRadioButton(self.mGroupBox_2)
        self.rbScotland.setObjectName("rbScotland")
        self.buttonGroup_2.addButton(self.rbScotland)
        self.horizontalLayout_5.addWidget(self.rbScotland)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.mGroupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.rbUserArea = QtWidgets.QRadioButton(self.groupBox)
        self.rbUserArea.setChecked(True)
        self.rbUserArea.setObjectName("rbUserArea")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.rbUserArea)
        self.verticalLayout_18.addWidget(self.rbUserArea)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.sbArea = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbArea.setDecimals(3)
        self.sbArea.setMaximum(999999.0)
        self.sbArea.setObjectName("sbArea")
        self.horizontalLayout_6.addWidget(self.sbArea)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_18.addLayout(self.horizontalLayout_6)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.rbQgisArea = QtWidgets.QRadioButton(self.groupBox)
        self.rbQgisArea.setObjectName("rbQgisArea")
        self.buttonGroup_6.addButton(self.rbQgisArea)
        self.horizontalLayout_50.addWidget(self.rbQgisArea)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_50.addWidget(self.label_27)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem4)
        self.verticalLayout_23.addLayout(self.horizontalLayout_50)
        self.verticalLayout_18.addLayout(self.verticalLayout_23)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_48.addWidget(self.label_22)
        self.sbAreaUrban = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbAreaUrban.setDecimals(3)
        self.sbAreaUrban.setMaximum(999999.0)
        self.sbAreaUrban.setObjectName("sbAreaUrban")
        self.horizontalLayout_48.addWidget(self.sbAreaUrban)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_48.addWidget(self.label_25)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem5)
        self.verticalLayout_18.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.cbARF = QtWidgets.QCheckBox(self.groupBox)
        self.cbARF.setObjectName("cbARF")
        self.horizontalLayout_49.addWidget(self.cbARF)
        self.sbARF = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbARF.setMinimum(0.01)
        self.sbARF.setMaximum(1.0)
        self.sbARF.setSingleStep(0.1)
        self.sbARF.setProperty("value", 1.0)
        self.sbARF.setObjectName("sbARF")
        self.horizontalLayout_49.addWidget(self.sbARF)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_49)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_17.addWidget(self.mGroupBox_2)
        self.mGroupBox_3 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox_3.setCollapsed(False)
        self.mGroupBox_3.setObjectName("mGroupBox_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.mGroupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_SAEP = QtWidgets.QGroupBox(self.mGroupBox_3)
        self.groupBox_SAEP.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_SAEP.setMaximumSize(QtCore.QSize(300, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_SAEP.setPalette(palette)
        self.groupBox_SAEP.setAutoFillBackground(True)
        self.groupBox_SAEP.setObjectName("groupBox_SAEP")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_SAEP)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_19 = QtWidgets.QLabel(self.groupBox_SAEP)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_35.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.groupBox_SAEP)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_35.addWidget(self.label_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.cbSelectAll = QtWidgets.QCheckBox(self.groupBox_SAEP)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbSelectAll.setFont(font)
        self.cbSelectAll.setTristate(True)
        self.cbSelectAll.setObjectName("cbSelectAll")
        self.horizontalLayout_37.addWidget(self.cbSelectAll)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem7)
        self.cbCCAllActive = QtWidgets.QCheckBox(self.groupBox_SAEP)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbCCAllActive.setFont(font)
        self.cbCCAllActive.setObjectName("cbCCAllActive")
        self.horizontalLayout_24.addWidget(self.cbCCAllActive)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.cb0001y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0001y.setObjectName("cb0001y")
        self.horizontalLayout_38.addWidget(self.cb0001y)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem8 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem8)
        self.cb0001y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0001y_CC.setText("")
        self.cb0001y_CC.setObjectName("cb0001y_CC")
        self.horizontalLayout_25.addWidget(self.cb0001y_CC)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.cb0002y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0002y.setObjectName("cb0002y")
        self.horizontalLayout_39.addWidget(self.cb0002y)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem9 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem9)
        self.cb0002y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0002y_CC.setText("")
        self.cb0002y_CC.setObjectName("cb0002y_CC")
        self.horizontalLayout_26.addWidget(self.cb0002y_CC)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_26)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.cb0005y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0005y.setObjectName("cb0005y")
        self.horizontalLayout_40.addWidget(self.cb0005y)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem10 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem10)
        self.cb0005y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0005y_CC.setText("")
        self.cb0005y_CC.setObjectName("cb0005y_CC")
        self.horizontalLayout_27.addWidget(self.cb0005y_CC)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_27)
        self.verticalLayout_3.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.cb0010y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0010y.setObjectName("cb0010y")
        self.horizontalLayout_41.addWidget(self.cb0010y)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem11)
        self.cb0010y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0010y_CC.setText("")
        self.cb0010y_CC.setObjectName("cb0010y_CC")
        self.horizontalLayout_28.addWidget(self.cb0010y_CC)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_28)
        self.verticalLayout_3.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.cb0030y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0030y.setObjectName("cb0030y")
        self.horizontalLayout_42.addWidget(self.cb0030y)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem12 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem12)
        self.cb0030y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0030y_CC.setText("")
        self.cb0030y_CC.setObjectName("cb0030y_CC")
        self.horizontalLayout_29.addWidget(self.cb0030y_CC)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_29)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.cb0050y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0050y.setObjectName("cb0050y")
        self.horizontalLayout_43.addWidget(self.cb0050y)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem13 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem13)
        self.cb0050y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0050y_CC.setText("")
        self.cb0050y_CC.setObjectName("cb0050y_CC")
        self.horizontalLayout_30.addWidget(self.cb0050y_CC)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_30)
        self.verticalLayout_3.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.cb0075y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0075y.setObjectName("cb0075y")
        self.horizontalLayout_44.addWidget(self.cb0075y)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem14 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem14)
        self.cb0075y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0075y_CC.setText("")
        self.cb0075y_CC.setObjectName("cb0075y_CC")
        self.horizontalLayout_31.addWidget(self.cb0075y_CC)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_31)
        self.verticalLayout_3.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.cb0100y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0100y.setObjectName("cb0100y")
        self.horizontalLayout_45.addWidget(self.cb0100y)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem15 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem15)
        self.cb0100y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0100y_CC.setText("")
        self.cb0100y_CC.setObjectName("cb0100y_CC")
        self.horizontalLayout_32.addWidget(self.cb0100y_CC)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.cb0200y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0200y.setObjectName("cb0200y")
        self.horizontalLayout_46.addWidget(self.cb0200y)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem16 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem16)
        self.cb0200y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb0200y_CC.setText("")
        self.cb0200y_CC.setObjectName("cb0200y_CC")
        self.horizontalLayout_33.addWidget(self.cb0200y_CC)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_33)
        self.verticalLayout_3.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.cb1000y = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb1000y.setObjectName("cb1000y")
        self.horizontalLayout_47.addWidget(self.cb1000y)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem17 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem17)
        self.cb1000y_CC = QtWidgets.QCheckBox(self.groupBox_SAEP)
        self.cb1000y_CC.setText("")
        self.cb1000y_CC.setObjectName("cb1000y_CC")
        self.horizontalLayout_34.addWidget(self.cb1000y_CC)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_34)
        self.verticalLayout_3.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_9.addWidget(self.groupBox_SAEP)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_21 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_10.addWidget(self.label_21)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.rbEngine23 = QtWidgets.QRadioButton(self.mGroupBox_3)
        self.rbEngine23.setChecked(True)
        self.rbEngine23.setObjectName("rbEngine23")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.rbEngine23)
        self.horizontalLayout_36.addWidget(self.rbEngine23)
        self.rbEngine22 = QtWidgets.QRadioButton(self.mGroupBox_3)
        self.rbEngine22.setObjectName("rbEngine22")
        self.buttonGroup_3.addButton(self.rbEngine22)
        self.horizontalLayout_36.addWidget(self.rbEngine22)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem18)
        self.verticalLayout_10.addLayout(self.horizontalLayout_36)
        spacerItem19 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem19)
        self.label_11 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rbWinter = QtWidgets.QRadioButton(self.mGroupBox_3)
        self.rbWinter.setChecked(True)
        self.rbWinter.setObjectName("rbWinter")
        self.buttonGroup = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbWinter)
        self.horizontalLayout_11.addWidget(self.rbWinter)
        self.rbSummer = QtWidgets.QRadioButton(self.mGroupBox_3)
        self.rbSummer.setObjectName("rbSummer")
        self.buttonGroup.addButton(self.rbSummer)
        self.horizontalLayout_11.addWidget(self.rbSummer)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem20)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.sbCCFactor = QtWidgets.QDoubleSpinBox(self.mGroupBox_3)
        self.sbCCFactor.setDecimals(1)
        self.sbCCFactor.setSingleStep(0.1)
        self.sbCCFactor.setProperty("value", 1.0)
        self.sbCCFactor.setObjectName("sbCCFactor")
        self.horizontalLayout_23.addWidget(self.sbCCFactor)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem21)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        spacerItem22 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem22)
        self.label_9 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.leDuration = QtWidgets.QLineEdit(self.mGroupBox_3)
        self.leDuration.setMinimumSize(QtCore.QSize(60, 0))
        self.leDuration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leDuration.setInputMask("")
        self.leDuration.setText("")
        self.leDuration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leDuration.setObjectName("leDuration")
        self.verticalLayout_8.addWidget(self.leDuration)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem23 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.leTimestep = QtWidgets.QLineEdit(self.mGroupBox_3)
        self.leTimestep.setMinimumSize(QtCore.QSize(60, 0))
        self.leTimestep.setMaximumSize(QtCore.QSize(70, 16777215))
        self.leTimestep.setInputMask("")
        self.leTimestep.setText("")
        self.leTimestep.setObjectName("leTimestep")
        self.verticalLayout_9.addWidget(self.leTimestep)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_SAEP_2 = QtWidgets.QGroupBox(self.mGroupBox_3)
        self.groupBox_SAEP_2.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_SAEP_2.setMaximumSize(QtCore.QSize(300, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_SAEP_2.setPalette(palette)
        self.groupBox_SAEP_2.setAutoFillBackground(True)
        self.groupBox_SAEP_2.setObjectName("groupBox_SAEP_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_SAEP_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sbRP = QtWidgets.QSpinBox(self.groupBox_SAEP_2)
        self.sbRP.setMinimum(1)
        self.sbRP.setMaximum(999999)
        self.sbRP.setProperty("value", 1)
        self.sbRP.setObjectName("sbRP")
        self.horizontalLayout_3.addWidget(self.sbRP)
        self.btnAddRP = QtWidgets.QToolButton(self.groupBox_SAEP_2)
        self.btnAddRP.setObjectName("btnAddRP")
        self.horizontalLayout_3.addWidget(self.btnAddRP)
        self.btnRemoveRP = QtWidgets.QToolButton(self.groupBox_SAEP_2)
        self.btnRemoveRP.setObjectName("btnRemoveRP")
        self.horizontalLayout_3.addWidget(self.btnRemoveRP)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lwRP = QtWidgets.QListWidget(self.groupBox_SAEP_2)
        self.lwRP.setMaximumSize(QtCore.QSize(16777215, 75))
        self.lwRP.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwRP.setObjectName("lwRP")
        self.verticalLayout_4.addWidget(self.lwRP)
        self.horizontalLayout_10.addWidget(self.groupBox_SAEP_2)
        self.gbDurations = QtWidgets.QGroupBox(self.mGroupBox_3)
        self.gbDurations.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.gbDurations.setPalette(palette)
        self.gbDurations.setAutoFillBackground(True)
        self.gbDurations.setObjectName("gbDurations")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.gbDurations)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnAddDur = QtWidgets.QToolButton(self.gbDurations)
        self.btnAddDur.setObjectName("btnAddDur")
        self.horizontalLayout_18.addWidget(self.btnAddDur)
        self.btnRemDur = QtWidgets.QToolButton(self.gbDurations)
        self.btnRemDur.setObjectName("btnRemDur")
        self.horizontalLayout_18.addWidget(self.btnRemDur)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem26)
        self.verticalLayout_26.addLayout(self.horizontalLayout_18)
        self.lwDuration = QtWidgets.QListWidget(self.gbDurations)
        self.lwDuration.setMaximumSize(QtCore.QSize(16777215, 75))
        self.lwDuration.setObjectName("lwDuration")
        self.verticalLayout_26.addWidget(self.lwDuration)
        self.horizontalLayout_10.addWidget(self.gbDurations)
        spacerItem27 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addWidget(self.mGroupBox_3)
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem28 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem28)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.mGroupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cboInputGIS = QtWidgets.QComboBox(self.mGroupBox)
        self.cboInputGIS.setObjectName("cboInputGIS")
        self.verticalLayout.addWidget(self.cboInputGIS)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem29 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem29)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.mGroupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.cboFields = QtWidgets.QComboBox(self.mGroupBox)
        self.cboFields.setObjectName("cboFields")
        self.verticalLayout_2.addWidget(self.cboFields)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem30 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem30)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.mGroupBox)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_19.addWidget(self.label_14)
        self.cboFeatures = QtWidgets.QComboBox(self.mGroupBox)
        self.cboFeatures.setObjectName("cboFeatures")
        self.verticalLayout_19.addWidget(self.cboFeatures)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_17.addWidget(self.mGroupBox)
        self.mGroupBox_4 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.mGroupBox_4.setCollapsed(False)
        self.mGroupBox_4.setObjectName("mGroupBox_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.mGroupBox_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gbOutRainfall = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.gbOutRainfall.setCheckable(True)
        self.gbOutRainfall.setChecked(False)
        self.gbOutRainfall.setObjectName("gbOutRainfall")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.gbOutRainfall)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.rbGrossRainfall = QtWidgets.QCheckBox(self.gbOutRainfall)
        self.rbGrossRainfall.setChecked(True)
        self.rbGrossRainfall.setObjectName("rbGrossRainfall")
        self.horizontalLayout_16.addWidget(self.rbGrossRainfall)
        self.rbNetRainfall = QtWidgets.QCheckBox(self.gbOutRainfall)
        self.rbNetRainfall.setObjectName("rbNetRainfall")
        self.horizontalLayout_16.addWidget(self.rbNetRainfall)
        self.verticalLayout_21.addLayout(self.horizontalLayout_16)
        self.label_15 = QtWidgets.QLabel(self.gbOutRainfall)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.rbRuralClone = QtWidgets.QRadioButton(self.gbOutRainfall)
        self.rbRuralClone.setChecked(True)
        self.rbRuralClone.setObjectName("rbRuralClone")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.rbRuralClone)
        self.horizontalLayout_20.addWidget(self.rbRuralClone)
        self.rbUrbanClone = QtWidgets.QRadioButton(self.gbOutRainfall)
        self.rbUrbanClone.setChecked(False)
        self.rbUrbanClone.setObjectName("rbUrbanClone")
        self.buttonGroup_9.addButton(self.rbUrbanClone)
        self.horizontalLayout_20.addWidget(self.rbUrbanClone)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem31)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.gbRainToGis = QtWidgets.QGroupBox(self.gbOutRainfall)
        self.gbRainToGis.setCheckable(True)
        self.gbRainToGis.setChecked(False)
        self.gbRainToGis.setObjectName("gbRainToGis")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.gbRainToGis)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.rb2dRf = QtWidgets.QRadioButton(self.gbRainToGis)
        self.rb2dRf.setChecked(True)
        self.rb2dRf.setObjectName("rb2dRf")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.rb2dRf)
        self.horizontalLayout_22.addWidget(self.rb2dRf)
        self.rb2dSaRf = QtWidgets.QRadioButton(self.gbRainToGis)
        self.rb2dSaRf.setObjectName("rb2dSaRf")
        self.buttonGroup_7.addButton(self.rb2dSaRf)
        self.horizontalLayout_22.addWidget(self.rb2dSaRf)
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem32)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem33)
        self.verticalLayout_29.addLayout(self.horizontalLayout_22)
        self.verticalLayout_28.addLayout(self.verticalLayout_29)
        self.verticalLayout_21.addWidget(self.gbRainToGis)
        self.horizontalLayout_12.addLayout(self.verticalLayout_21)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.verticalLayout_16.addWidget(self.gbOutRainfall)
        self.gbOutHydrograph = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.gbOutHydrograph.setCheckable(True)
        self.gbOutHydrograph.setChecked(False)
        self.gbOutHydrograph.setObjectName("gbOutHydrograph")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.gbOutHydrograph)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rbDirectRunoff = QtWidgets.QCheckBox(self.gbOutHydrograph)
        self.rbDirectRunoff.setObjectName("rbDirectRunoff")
        self.horizontalLayout_14.addWidget(self.rbDirectRunoff)
        self.rbBaseFlow = QtWidgets.QCheckBox(self.gbOutHydrograph)
        self.rbBaseFlow.setObjectName("rbBaseFlow")
        self.horizontalLayout_14.addWidget(self.rbBaseFlow)
        self.rbTotalRunoff = QtWidgets.QCheckBox(self.gbOutHydrograph)
        self.rbTotalRunoff.setChecked(True)
        self.rbTotalRunoff.setObjectName("rbTotalRunoff")
        self.horizontalLayout_14.addWidget(self.rbTotalRunoff)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem35)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.label_12 = QtWidgets.QLabel(self.gbOutHydrograph)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rbRural = QtWidgets.QRadioButton(self.gbOutHydrograph)
        self.rbRural.setChecked(True)
        self.rbRural.setObjectName("rbRural")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.rbRural)
        self.horizontalLayout_13.addWidget(self.rbRural)
        self.rbUrban = QtWidgets.QRadioButton(self.gbOutHydrograph)
        self.rbUrban.setChecked(False)
        self.rbUrban.setObjectName("rbUrban")
        self.buttonGroup_4.addButton(self.rbUrban)
        self.horizontalLayout_13.addWidget(self.rbUrban)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem36)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.gbHydToGis = QtWidgets.QGroupBox(self.gbOutHydrograph)
        self.gbHydToGis.setCheckable(True)
        self.gbHydToGis.setChecked(False)
        self.gbHydToGis.setObjectName("gbHydToGis")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.gbHydToGis)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.rb2dSa = QtWidgets.QRadioButton(self.gbHydToGis)
        self.rb2dSa.setObjectName("rb2dSa")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.rb2dSa)
        self.horizontalLayout_17.addWidget(self.rb2dSa)
        spacerItem37 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem37)
        self.rb1dBc = QtWidgets.QRadioButton(self.gbHydToGis)
        self.rb1dBc.setObjectName("rb1dBc")
        self.buttonGroup_8.addButton(self.rb1dBc)
        self.horizontalLayout_17.addWidget(self.rb1dBc)
        self.rb2dBc = QtWidgets.QRadioButton(self.gbHydToGis)
        self.rb2dBc.setChecked(True)
        self.rb2dBc.setObjectName("rb2dBc")
        self.buttonGroup_8.addButton(self.rb2dBc)
        self.horizontalLayout_17.addWidget(self.rb2dBc)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem38)
        self.verticalLayout_30.addLayout(self.horizontalLayout_17)
        self.verticalLayout_31.addLayout(self.verticalLayout_30)
        self.verticalLayout_13.addWidget(self.gbHydToGis)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_16.addWidget(self.gbOutHydrograph)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.gbBoundaryName = QtWidgets.QGroupBox(self.groupBox_2)
        self.gbBoundaryName.setCheckable(True)
        self.gbBoundaryName.setChecked(False)
        self.gbBoundaryName.setObjectName("gbBoundaryName")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.gbBoundaryName)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_16 = QtWidgets.QLabel(self.gbBoundaryName)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_24.addWidget(self.label_16)
        self.leBoundaryName = QtWidgets.QLineEdit(self.gbBoundaryName)
        self.leBoundaryName.setObjectName("leBoundaryName")
        self.verticalLayout_24.addWidget(self.leBoundaryName)
        self.verticalLayout_25.addWidget(self.gbBoundaryName)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_25.addWidget(self.label_17)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.rbAutoPad = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbAutoPad.setChecked(True)
        self.rbAutoPad.setObjectName("rbAutoPad")
        self.buttonGroup_10 = QtWidgets.QButtonGroup(refh2)
        self.buttonGroup_10.setObjectName("buttonGroup_10")
        self.buttonGroup_10.addButton(self.rbAutoPad)
        self.horizontalLayout_21.addWidget(self.rbAutoPad)
        self.rbNoPad = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbNoPad.setObjectName("rbNoPad")
        self.buttonGroup_10.addButton(self.rbNoPad)
        self.horizontalLayout_21.addWidget(self.rbNoPad)
        self.rbSetPad = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbSetPad.setObjectName("rbSetPad")
        self.buttonGroup_10.addButton(self.rbSetPad)
        self.horizontalLayout_21.addWidget(self.rbSetPad)
        self.sbPadNo = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbPadNo.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbPadNo.setProperty("value", 3)
        self.sbPadNo.setObjectName("sbPadNo")
        self.horizontalLayout_21.addWidget(self.sbPadNo)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem39)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        self.verticalLayout_25.addLayout(self.verticalLayout_20)
        self.verticalLayout_16.addWidget(self.groupBox_2)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.mGroupBox_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnOutfile = QtWidgets.QToolButton(self.mGroupBox_4)
        self.btnOutfile.setObjectName("btnOutfile")
        self.horizontalLayout_15.addWidget(self.btnOutfile)
        self.leOutfile = QtWidgets.QLineEdit(self.mGroupBox_4)
        self.leOutfile.setObjectName("leOutfile")
        self.horizontalLayout_15.addWidget(self.leOutfile)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.verticalLayout_17.addWidget(self.mGroupBox_4)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem40)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.progressBarLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.progressBarLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBarLabel.setObjectName("progressBarLabel")
        self.horizontalLayout.addWidget(self.progressBarLabel)
        self.pbRun = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pbRun.setObjectName("pbRun")
        self.horizontalLayout.addWidget(self.pbRun)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        refh2.setWidget(self.dockWidgetContents)

        self.retranslateUi(refh2)
        QtCore.QMetaObject.connectSlotsByName(refh2)

    def retranslateUi(self, refh2):
        _translate = QtCore.QCoreApplication.translate
        refh2.setWindowTitle(_translate("refh2", "ReFH2 to TUFLOW"))
        self.label_24.setText(_translate("refh2", "<html><head/><body><p><a href=\"https://wiki.tuflow.com/index.php?title=QGIS_ReFH2_to_TUFLOW\"><span style=\" text-decoration: underline; color:#0000ff;\">Link to ReFH2 to TUFLOW Documentation</span></a></p></body></html>"))
        self.mGroupBox_2.setTitle(_translate("refh2", "Location"))
        self.label_4.setText(_translate("refh2", "Catchment Descriptor Input Locator (.xml)"))
        self.btnInputXML.setText(_translate("refh2", "..."))
        self.label_5.setText(_translate("refh2", "Location:"))
        self.rbEngland.setText(_translate("refh2", "England / Wales / Northern Ireland"))
        self.rbScotland.setText(_translate("refh2", "Scotland"))
        self.groupBox.setTitle(_translate("refh2", "Area"))
        self.rbUserArea.setText(_translate("refh2", "User specify"))
        self.label_6.setText(_translate("refh2", "<html><head/><body><p>Total Area (km<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.label_23.setText(_translate("refh2", "<html><head/><body><p><span style=\" font-style:italic;\">Used for Point Descriptors Only</span></p></body></html>"))
        self.rbQgisArea.setText(_translate("refh2", "Calculate in QGIS (must specify input GIS for this option)"))
        self.label_27.setText(_translate("refh2", "<html><head/><body><p><span style=\" font-style:italic;\">Used for Point Descriptors Only</span></p></body></html>"))
        self.label_22.setText(_translate("refh2", "<html><head/><body><p>Urban Area (km<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.label_25.setText(_translate("refh2", "<html><head/><body><p><span style=\" font-style:italic;\">See documentation on when this is applied</span></p></body></html>"))
        self.cbARF.setText(_translate("refh2", "User Specified Areal Reduction Factor"))
        self.mGroupBox_3.setTitle(_translate("refh2", "Event Selection"))
        self.groupBox_SAEP.setTitle(_translate("refh2", "Standard Return Periods"))
        self.label_19.setText(_translate("refh2", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Event</span></p></body></html>"))
        self.label_20.setText(_translate("refh2", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Climate Change</span></p></body></html>"))
        self.cbSelectAll.setText(_translate("refh2", "Select ALL"))
        self.cbCCAllActive.setText(_translate("refh2", "Apply to ALL Active"))
        self.cb0001y.setText(_translate("refh2", "1 year"))
        self.cb0002y.setText(_translate("refh2", "2 year"))
        self.cb0005y.setText(_translate("refh2", "5 year"))
        self.cb0010y.setText(_translate("refh2", "10 year"))
        self.cb0030y.setText(_translate("refh2", "30 year"))
        self.cb0050y.setText(_translate("refh2", "50 year"))
        self.cb0075y.setText(_translate("refh2", "75 year"))
        self.cb0100y.setText(_translate("refh2", "100 year"))
        self.cb0200y.setText(_translate("refh2", "200 year"))
        self.cb1000y.setText(_translate("refh2", "1000 year"))
        self.label_21.setText(_translate("refh2", "ReFH2 Engine Version:"))
        self.rbEngine23.setText(_translate("refh2", "2.3"))
        self.rbEngine22.setText(_translate("refh2", "2.2"))
        self.label_11.setText(_translate("refh2", "Season:"))
        self.rbWinter.setText(_translate("refh2", "Winter"))
        self.rbSummer.setText(_translate("refh2", "Summer"))
        self.label_18.setText(_translate("refh2", "Climate Change Factor:"))
        self.label_9.setText(_translate("refh2", "<html><head/><body><p>If no duration is specified then the tool will use the recommended duration based on the Tp and SAAR parameters</p><p>- if outputting multiple durations, use + / - signs to add to Duration - Timestep box below</p></body></html>"))
        self.label_8.setText(_translate("refh2", "Duration (hh:mm:ss)"))
        self.label_10.setText(_translate("refh2", "Timestep (hh:mm:ss)"))
        self.groupBox_SAEP_2.setTitle(_translate("refh2", "Other Return Periods"))
        self.sbRP.setSuffix(_translate("refh2", " year"))
        self.btnAddRP.setText(_translate("refh2", "..."))
        self.btnRemoveRP.setText(_translate("refh2", "..."))
        self.gbDurations.setTitle(_translate("refh2", "Duration - Timestep"))
        self.btnAddDur.setText(_translate("refh2", "..."))
        self.btnRemDur.setText(_translate("refh2", "..."))
        self.mGroupBox.setTitle(_translate("refh2", "Input GIS (optional)"))
        self.label.setText(_translate("refh2", "<html><head/><body><p>Used only to calculate area if required and to output a TUFLOW boundary GIS layer e.g. 2d_sa</p><p>If used, must specify:</p><p>- GIS Layer e.g. catchment_region.shp</p><p>- ID Field - will be used for TUFLOW boundary name</p><p>- Feature - which feature in GIS layer to use<br/></p></body></html>"))
        self.label_2.setText(_translate("refh2", "Input Catchment Layer:"))
        self.label_3.setText(_translate("refh2", "ID Field:"))
        self.label_14.setText(_translate("refh2", "Feature:"))
        self.mGroupBox_4.setTitle(_translate("refh2", "Output"))
        self.gbOutRainfall.setTitle(_translate("refh2", "Output Rainfall (applied as 2d_rf or 2d_sa_rf)"))
        self.rbGrossRainfall.setText(_translate("refh2", "Gross Design Rainfall"))
        self.rbNetRainfall.setText(_translate("refh2", "Net Design Rainfall"))
        self.label_15.setText(_translate("refh2", "Type"))
        self.rbRuralClone.setText(_translate("refh2", "Rural"))
        self.rbUrbanClone.setText(_translate("refh2", "Urban"))
        self.gbRainToGis.setTitle(_translate("refh2", "Output To TUFLOW GIS"))
        self.rb2dRf.setText(_translate("refh2", "2d_rf"))
        self.rb2dSaRf.setText(_translate("refh2", "2d_sa_rf"))
        self.gbOutHydrograph.setTitle(_translate("refh2", "Output Hydrograph (applied as 1d_bc, 2d_bc, 2d_sa)"))
        self.rbDirectRunoff.setText(_translate("refh2", "Direct Runoff"))
        self.rbBaseFlow.setText(_translate("refh2", "Base Flow"))
        self.rbTotalRunoff.setText(_translate("refh2", "Total Runoff"))
        self.label_12.setText(_translate("refh2", "Type"))
        self.rbRural.setText(_translate("refh2", "Rural"))
        self.rbUrban.setText(_translate("refh2", "Urban"))
        self.gbHydToGis.setTitle(_translate("refh2", "Output To TUFLOW GIS"))
        self.rb2dSa.setText(_translate("refh2", "2d_sa"))
        self.rb1dBc.setText(_translate("refh2", "1d_bc"))
        self.rb2dBc.setText(_translate("refh2", "2d_bc"))
        self.groupBox_2.setTitle(_translate("refh2", "Output Event Naming (optional)"))
        self.gbBoundaryName.setTitle(_translate("refh2", "Boundary Name"))
        self.label_16.setText(_translate("refh2", "Sets the boundary name in the bc_dbase. Using a GIS layer will take precedence over this."))
        self.label_17.setText(_translate("refh2", "<html><head/><body><p>Zero Padding: e.g. 001yr<br/>Auto padding will set all selected events to the same character length</p></body></html>"))
        self.rbAutoPad.setText(_translate("refh2", "Auto Pad With Zeros"))
        self.rbNoPad.setText(_translate("refh2", "No Zero Padding"))
        self.rbSetPad.setText(_translate("refh2", "Set Zero Padding:"))
        self.label_13.setText(_translate("refh2", "ReFH2 Output File (optional - otherwide default to same folder and name as input XML):"))
        self.btnOutfile.setText(_translate("refh2", "..."))
        self.progressBarLabel.setText(_translate("refh2", "Ready"))
        self.pbRun.setText(_translate("refh2", "Run"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
import tuflow.resources.TUFLOW_logo_rc
