# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ellis.symons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\tuflow_viewer_v2\widgets\ui\options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

if not QtCore.QSettings().value('TUFLOW/TestCase', False, type=bool):
   from ....compatibility_routines import (QT_HORIZONTAL, QT_BUTTON_BOX_CLOSE, QT_SCROLL_BAR_ALWAYS_OFF,
     QT_ABSTRACT_ITEM_VIEW_NO_EDIT_TRIGGERS, QT_ELIDE_NONE)
else:
   from tuflow.compatibility_routines import (QT_HORIZONTAL, QT_BUTTON_BOX_CLOSE, QT_SCROLL_BAR_ALWAYS_OFF,
     QT_ABSTRACT_ITEM_VIEW_NO_EDIT_TRIGGERS, QT_ELIDE_NONE)


class Ui_TuflowViewerOptions(object):
    def setupUi(self, TuflowViewerOptions):
        TuflowViewerOptions.setObjectName("TuflowViewerOptions")
        TuflowViewerOptions.resize(507, 463)
        self.layout = QtWidgets.QVBoxLayout(TuflowViewerOptions)
        self.layout.setObjectName("layout")
        self.splitter = QtWidgets.QSplitter(TuflowViewerOptions)
        self.splitter.setOrientation(QT_HORIZONTAL)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.contents_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.contents_layout.setContentsMargins(0, 0, 0, 0)
        self.contents_layout.setObjectName("contents_layout")
        self.options_tree_view = QtWidgets.QTreeView(self.verticalLayoutWidget)
        self.options_tree_view.setMinimumSize(QtCore.QSize(58, 0))
        self.options_tree_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.options_tree_view.setHorizontalScrollBarPolicy(QT_SCROLL_BAR_ALWAYS_OFF)
        self.options_tree_view.setEditTriggers(QT_ABSTRACT_ITEM_VIEW_NO_EDIT_TRIGGERS)
        self.options_tree_view.setIconSize(QtCore.QSize(32, 32))
        self.options_tree_view.setTextElideMode(QT_ELIDE_NONE)
        self.options_tree_view.setObjectName("options_tree_view")
        self.contents_layout.addWidget(self.options_tree_view)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.page_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.page_layout.setContentsMargins(0, 0, 0, 0)
        self.page_layout.setObjectName("page_layout")
        self.layout.addWidget(self.splitter)
        self.button_box = QtWidgets.QDialogButtonBox(TuflowViewerOptions)
        self.button_box.setOrientation(QT_HORIZONTAL)
        self.button_box.setStandardButtons(QT_BUTTON_BOX_CLOSE)
        self.button_box.setObjectName("button_box")
        self.layout.addWidget(self.button_box)

        self.retranslateUi(TuflowViewerOptions)
        self.button_box.rejected.connect(TuflowViewerOptions.reject) # type: ignore
        self.button_box.accepted.connect(TuflowViewerOptions.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TuflowViewerOptions)

    def retranslateUi(self, TuflowViewerOptions):
        _translate = QtCore.QCoreApplication.translate
        TuflowViewerOptions.setWindowTitle(_translate("TuflowViewerOptions", "TUFLOW Viewer Settings"))
