# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\esymons\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\bridge_editor\ArchBridgeList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



from ..compatibility_routines import QT_SIZE_POLICY_MINIMUM, QT_SIZE_POLICY_EXPANDING


class Ui_ArchBridgeList(object):
    def setupUi(self, ArchBridgeList):
        ArchBridgeList.setObjectName("ArchBridgeList")
        ArchBridgeList.resize(272, 325)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArchBridgeList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(ArchBridgeList)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.leFilter = QtWidgets.QLineEdit(ArchBridgeList)
        self.leFilter.setClearButtonEnabled(True)
        self.leFilter.setObjectName("leFilter")
        self.verticalLayout.addWidget(self.leFilter)
        self.label = QtWidgets.QLabel(ArchBridgeList)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lwBridges = QtWidgets.QListWidget(ArchBridgeList)
        self.lwBridges.setObjectName("lwBridges")
        self.verticalLayout.addWidget(self.lwBridges)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QT_SIZE_POLICY_EXPANDING, QT_SIZE_POLICY_MINIMUM)
        self.horizontalLayout.addItem(spacerItem)
        self.pbOk = QtWidgets.QPushButton(ArchBridgeList)
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout.addWidget(self.pbOk)
        self.pbCancel = QtWidgets.QPushButton(ArchBridgeList)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ArchBridgeList)
        QtCore.QMetaObject.connectSlotsByName(ArchBridgeList)

    def retranslateUi(self, ArchBridgeList):
        _translate = QtCore.QCoreApplication.translate
        ArchBridgeList.setWindowTitle(_translate("ArchBridgeList", "Select a bridge to import"))
        self.label_2.setText(_translate("ArchBridgeList", "Filter"))
        self.label.setText(_translate("ArchBridgeList", "Arch Bridges"))
        self.pbOk.setText(_translate("ArchBridgeList", "OK"))
        self.pbCancel.setText(_translate("ArchBridgeList", "Cancel"))
