# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuflowqgis_bridge_editor.ui'
#
# Created: Thu Aug 09 16:39:29 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tuflowqgis_BridgeEditor(object):
    def setupUi(self, tuflowqgis_BridgeEditor):
        tuflowqgis_BridgeEditor.setObjectName(_fromUtf8("tuflowqgis_BridgeEditor"))
        tuflowqgis_BridgeEditor.resize(943, 833)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bridgeEditor_Layout = QtGui.QVBoxLayout()
        self.bridgeEditor_Layout.setObjectName(_fromUtf8("bridgeEditor_Layout"))
        self.bridgeProperties = QtGui.QHBoxLayout()
        self.bridgeProperties.setObjectName(_fromUtf8("bridgeProperties"))
        self.bridgeInputs = QtGui.QGridLayout()
        self.bridgeInputs.setObjectName(_fromUtf8("bridgeInputs"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.bridgeInputs.addWidget(self.label_5, 1, 0, 2, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.bridgeInputs.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bridgeInputs.addWidget(self.label_2, 12, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.bridgeInputs.addWidget(self.label, 11, 0, 1, 5)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.bridgeInputs.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.bridgeInputs.addWidget(self.label_8, 8, 0, 1, 1)
        self.pierNo = QtGui.QSpinBox(self.tab)
        self.pierNo.setObjectName(_fromUtf8("pierNo"))
        self.bridgeInputs.addWidget(self.pierNo, 8, 1, 1, 1)
        self.pierWidth = QtGui.QDoubleSpinBox(self.tab)
        self.pierWidth.setObjectName(_fromUtf8("pierWidth"))
        self.bridgeInputs.addWidget(self.pierWidth, 9, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bridgeInputs.addWidget(self.label_12, 10, 0, 1, 1)
        self.pierShape = QtGui.QComboBox(self.tab)
        self.pierShape.setObjectName(_fromUtf8("pierShape"))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.pierShape.addItem(_fromUtf8(""))
        self.bridgeInputs.addWidget(self.pierShape, 10, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.bridgeInputs.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.bridgeInputs.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.bridgeInputs.addWidget(self.label_7, 7, 0, 1, 1)
        self.handRailBlockage = QtGui.QSpinBox(self.tab)
        self.handRailBlockage.setObjectName(_fromUtf8("handRailBlockage"))
        self.bridgeInputs.addWidget(self.handRailBlockage, 6, 5, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.bridgeInputs.addWidget(self.label_33, 6, 2, 1, 1)
        self.pbUseMapWindowSel = QtGui.QPushButton(self.tab)
        self.pbUseMapWindowSel.setIconSize(QtCore.QSize(15, 15))
        self.pbUseMapWindowSel.setObjectName(_fromUtf8("pbUseMapWindowSel"))
        self.bridgeInputs.addWidget(self.pbUseMapWindowSel, 1, 5, 2, 1)
        self.demComboBox = QtGui.QComboBox(self.tab)
        self.demComboBox.setObjectName(_fromUtf8("demComboBox"))
        self.bridgeInputs.addWidget(self.demComboBox, 1, 1, 2, 3)
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.bridgeInputs.addWidget(self.label_32, 0, 0, 1, 1)
        self.bridgeName = QtGui.QLineEdit(self.tab)
        self.bridgeName.setObjectName(_fromUtf8("bridgeName"))
        self.bridgeInputs.addWidget(self.bridgeName, 0, 1, 1, 4)
        self.zLineWidth = QtGui.QDoubleSpinBox(self.tab)
        self.zLineWidth.setObjectName(_fromUtf8("zLineWidth"))
        self.bridgeInputs.addWidget(self.zLineWidth, 12, 1, 1, 1)
        self.deckElevationBottom = QtGui.QDoubleSpinBox(self.tab)
        self.deckElevationBottom.setMaximum(99999.0)
        self.deckElevationBottom.setObjectName(_fromUtf8("deckElevationBottom"))
        self.bridgeInputs.addWidget(self.deckElevationBottom, 4, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.bridgeInputs.addWidget(self.label_16, 6, 4, 1, 1)
        self.handRailFlc = QtGui.QDoubleSpinBox(self.tab)
        self.handRailFlc.setObjectName(_fromUtf8("handRailFlc"))
        self.bridgeInputs.addWidget(self.handRailFlc, 6, 3, 1, 1)
        self.rbDrowned = QtGui.QRadioButton(self.tab)
        self.rbDrowned.setChecked(True)
        self.rbDrowned.setObjectName(_fromUtf8("rbDrowned"))
        self.bridgeInputs.addWidget(self.rbDrowned, 4, 5, 1, 1)
        self.handRailDepth = QtGui.QDoubleSpinBox(self.tab)
        self.handRailDepth.setObjectName(_fromUtf8("handRailDepth"))
        self.bridgeInputs.addWidget(self.handRailDepth, 6, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.bridgeInputs.addWidget(self.label_17, 4, 3, 2, 2)
        self.pbUpdateDeckData = QtGui.QPushButton(self.tab)
        self.pbUpdateDeckData.setObjectName(_fromUtf8("pbUpdateDeckData"))
        self.bridgeInputs.addWidget(self.pbUpdateDeckData, 3, 1, 1, 2)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.bridgeInputs.addWidget(self.label_13, 4, 0, 1, 1)
        self.pbDrawXsection = QtGui.QPushButton(self.tab)
        self.pbDrawXsection.setIconSize(QtCore.QSize(15, 15))
        self.pbDrawXsection.setObjectName(_fromUtf8("pbDrawXsection"))
        self.bridgeInputs.addWidget(self.pbDrawXsection, 1, 4, 2, 1)
        self.pbSaveFile = QtGui.QPushButton(self.tab)
        self.pbSaveFile.setObjectName(_fromUtf8("pbSaveFile"))
        self.bridgeInputs.addWidget(self.pbSaveFile, 0, 5, 1, 1)
        self.deckThickness = QtGui.QDoubleSpinBox(self.tab)
        self.deckThickness.setObjectName(_fromUtf8("deckThickness"))
        self.bridgeInputs.addWidget(self.deckThickness, 5, 1, 1, 1)
        self.rbUnderPressure = QtGui.QRadioButton(self.tab)
        self.rbUnderPressure.setObjectName(_fromUtf8("rbUnderPressure"))
        self.bridgeInputs.addWidget(self.rbUnderPressure, 5, 5, 1, 1)
        self.pbUpdatePierData = QtGui.QPushButton(self.tab)
        self.pbUpdatePierData.setObjectName(_fromUtf8("pbUpdatePierData"))
        self.bridgeInputs.addWidget(self.pbUpdatePierData, 7, 1, 1, 2)
        self.pierWidthLeft = QtGui.QDoubleSpinBox(self.tab)
        self.pierWidthLeft.setMinimum(-99999.0)
        self.pierWidthLeft.setMaximum(999999.0)
        self.pierWidthLeft.setObjectName(_fromUtf8("pierWidthLeft"))
        self.bridgeInputs.addWidget(self.pierWidthLeft, 8, 5, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.bridgeInputs.addWidget(self.label_34, 9, 4, 1, 1)
        self.pierGap = QtGui.QDoubleSpinBox(self.tab)
        self.pierGap.setMaximum(99999.0)
        self.pierGap.setObjectName(_fromUtf8("pierGap"))
        self.bridgeInputs.addWidget(self.pierGap, 9, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.bridgeInputs.addWidget(self.label_14, 8, 3, 1, 2)
        self.enforceInTerrain = QtGui.QCheckBox(self.tab)
        self.enforceInTerrain.setObjectName(_fromUtf8("enforceInTerrain"))
        self.bridgeInputs.addWidget(self.enforceInTerrain, 12, 3, 1, 3)
        self.pbClearXsection = QtGui.QPushButton(self.tab)
        self.pbClearXsection.setObjectName(_fromUtf8("pbClearXsection"))
        self.bridgeInputs.addWidget(self.pbClearXsection, 3, 4, 1, 1)
        self.bridgeInputs.setColumnStretch(0, 10)
        self.bridgeProperties.addLayout(self.bridgeInputs)
        self.bridgeTables = QtGui.QGridLayout()
        self.bridgeTables.setObjectName(_fromUtf8("bridgeTables"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_40 = QtGui.QLabel(self.tab_6)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 1, 0, 1, 1)
        self.xSectionRowCount = QtGui.QSpinBox(self.tab_6)
        self.xSectionRowCount.setMaximum(99999)
        self.xSectionRowCount.setObjectName(_fromUtf8("xSectionRowCount"))
        self.gridLayout_6.addWidget(self.xSectionRowCount, 1, 1, 1, 1)
        self.xSectionTable = QtGui.QTableWidget(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.xSectionTable.setFont(font)
        self.xSectionTable.setColumnCount(2)
        self.xSectionTable.setObjectName(_fromUtf8("xSectionTable"))
        self.xSectionTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.xSectionTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.xSectionTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.xSectionTable, 0, 0, 1, 2)
        self.gridLayout_6.setColumnStretch(0, 10)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_41 = QtGui.QLabel(self.tab_8)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_9.addWidget(self.label_41, 1, 0, 1, 1)
        self.deckRowCount = QtGui.QSpinBox(self.tab_8)
        self.deckRowCount.setMaximum(99999)
        self.deckRowCount.setObjectName(_fromUtf8("deckRowCount"))
        self.gridLayout_9.addWidget(self.deckRowCount, 1, 1, 1, 1)
        self.deckTable = QtGui.QTableWidget(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.deckTable.setFont(font)
        self.deckTable.setColumnCount(2)
        self.deckTable.setObjectName(_fromUtf8("deckTable"))
        self.deckTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.deckTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.deckTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.deckTable, 0, 0, 1, 2)
        self.gridLayout_9.setColumnStretch(0, 10)
        self.gridLayout_9.setColumnStretch(1, 2)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_42 = QtGui.QLabel(self.tab_7)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_8.addWidget(self.label_42, 1, 0, 1, 1)
        self.pierRowCount = QtGui.QSpinBox(self.tab_7)
        self.pierRowCount.setMaximum(99999)
        self.pierRowCount.setObjectName(_fromUtf8("pierRowCount"))
        self.gridLayout_8.addWidget(self.pierRowCount, 1, 1, 1, 1)
        self.pierTable = QtGui.QTableWidget(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pierTable.setFont(font)
        self.pierTable.setColumnCount(1)
        self.pierTable.setObjectName(_fromUtf8("pierTable"))
        self.pierTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pierTable.setHorizontalHeaderItem(0, item)
        self.gridLayout_8.addWidget(self.pierTable, 0, 0, 1, 2)
        self.gridLayout_8.setColumnStretch(0, 10)
        self.gridLayout_8.setColumnStretch(1, 2)
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.bridgeTables.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.bridgeProperties.addLayout(self.bridgeTables)
        self.bridgeProperties.setStretch(1, 5)
        self.bridgeEditor_Layout.addLayout(self.bridgeProperties)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_for_plot_2 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_plot_2.sizePolicy().hasHeightForWidth())
        self.frame_for_plot_2.setSizePolicy(sizePolicy)
        self.frame_for_plot_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_for_plot_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_plot_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_plot_2.setObjectName(_fromUtf8("frame_for_plot_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_for_plot_2)
        self.verticalLayout_10.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pbUpdate = QtGui.QPushButton(self.frame_for_plot_2)
        self.pbUpdate.setObjectName(_fromUtf8("pbUpdate"))
        self.gridLayout_5.addWidget(self.pbUpdate, 0, 0, 1, 1)
        self.cbShowLegend_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbShowLegend_2.setObjectName(_fromUtf8("cbShowLegend_2"))
        self.gridLayout_5.addWidget(self.cbShowLegend_2, 0, 1, 1, 1)
        self.cbLegendUL_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendUL_2.setObjectName(_fromUtf8("cbLegendUL_2"))
        self.gridLayout_5.addWidget(self.cbLegendUL_2, 0, 2, 1, 1)
        self.cbLegendUR_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendUR_2.setObjectName(_fromUtf8("cbLegendUR_2"))
        self.gridLayout_5.addWidget(self.cbLegendUR_2, 0, 3, 1, 1)
        self.cbLegendLL_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendLL_2.setObjectName(_fromUtf8("cbLegendLL_2"))
        self.gridLayout_5.addWidget(self.cbLegendLL_2, 0, 4, 1, 1)
        self.cbLegendLR_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendLR_2.setObjectName(_fromUtf8("cbLegendLR_2"))
        self.gridLayout_5.addWidget(self.cbLegendLR_2, 0, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.gridLayout_3.addWidget(self.frame_for_plot_2, 0, 0, 1, 1)
        self.bridgeEditor_Layout.addLayout(self.gridLayout_3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_for_toolbar = QtGui.QFrame(self.tab)
        self.frame_for_toolbar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_toolbar.setObjectName(_fromUtf8("frame_for_toolbar"))
        self.gridLayout_7.addWidget(self.frame_for_toolbar, 0, 0, 1, 1)
        self.statusLabel = QtGui.QLabel(self.tab)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout_7.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 10)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.bridgeEditor_Layout.addLayout(self.gridLayout_7)
        self.bridgeEditor_Layout.setStretch(0, 7)
        self.bridgeEditor_Layout.setStretch(1, 15)
        self.bridgeEditor_Layout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.bridgeEditor_Layout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 645, 595))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 16, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 13, 0, 1, 1)
        self.layer1Block = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer1Block.setObjectName(_fromUtf8("layer1Block"))
        self.gridLayout_4.addWidget(self.layer1Block, 6, 1, 1, 1)
        self.pbCreateLayer = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbCreateLayer.setObjectName(_fromUtf8("pbCreateLayer"))
        self.gridLayout_4.addWidget(self.pbCreateLayer, 20, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.pbUpdateLayer = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbUpdateLayer.setObjectName(_fromUtf8("pbUpdateLayer"))
        self.gridLayout_4.addWidget(self.pbUpdateLayer, 21, 0, 1, 2)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 15, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 4, 0, 1, 1)
        self.dz = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.dz.setObjectName(_fromUtf8("dz"))
        self.gridLayout_4.addWidget(self.dz, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 10, 0, 1, 1)
        self.layer1Flc = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer1Flc.setObjectName(_fromUtf8("layer1Flc"))
        self.gridLayout_4.addWidget(self.layer1Flc, 7, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 8, 0, 1, 1)
        self.layer3Flc = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer3Flc.setObjectName(_fromUtf8("layer3Flc"))
        self.gridLayout_4.addWidget(self.layer3Flc, 13, 1, 1, 1)
        self.layer2Block = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer2Block.setObjectName(_fromUtf8("layer2Block"))
        self.gridLayout_4.addWidget(self.layer2Block, 9, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 12, 0, 1, 1)
        self.shapeWidth = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.shapeWidth.setObjectName(_fromUtf8("shapeWidth"))
        self.gridLayout_4.addWidget(self.shapeWidth, 3, 1, 1, 1)
        self.pbIncrementLayer = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbIncrementLayer.setObjectName(_fromUtf8("pbIncrementLayer"))
        self.gridLayout_4.addWidget(self.pbIncrementLayer, 22, 0, 1, 2)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 7, 0, 1, 1)
        self.layer3Depth = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer3Depth.setObjectName(_fromUtf8("layer3Depth"))
        self.gridLayout_4.addWidget(self.layer3Depth, 11, 1, 1, 1)
        self.shapeOptions = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.shapeOptions.setObjectName(_fromUtf8("shapeOptions"))
        self.gridLayout_4.addWidget(self.shapeOptions, 4, 1, 1, 1)
        self.invert = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.invert.setObjectName(_fromUtf8("invert"))
        self.gridLayout_4.addWidget(self.invert, 1, 1, 1, 1)
        self.pbUpdateAttributes = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbUpdateAttributes.setObjectName(_fromUtf8("pbUpdateAttributes"))
        self.gridLayout_4.addWidget(self.pbUpdateAttributes, 0, 0, 1, 1)
        self.layer3Block = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer3Block.setObjectName(_fromUtf8("layer3Block"))
        self.gridLayout_4.addWidget(self.layer3Block, 12, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 9, 0, 1, 1)
        self.layer2Depth = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer2Depth.setObjectName(_fromUtf8("layer2Depth"))
        self.gridLayout_4.addWidget(self.layer2Depth, 8, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_4.addWidget(self.label_37, 11, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_4.addWidget(self.label_35, 5, 2, 1, 1)
        self.layer1Obv = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer1Obv.setObjectName(_fromUtf8("layer1Obv"))
        self.gridLayout_4.addWidget(self.layer1Obv, 5, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 7, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_4.addWidget(self.label_36, 8, 2, 1, 1)
        self.comment = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.comment.setObjectName(_fromUtf8("comment"))
        self.gridLayout_4.addWidget(self.comment, 14, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_4.addWidget(self.label_38, 14, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_44.setText(_fromUtf8(""))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_4.addWidget(self.label_44, 1, 2, 1, 1)
        self.layer2Flc = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.layer2Flc.setObjectName(_fromUtf8("layer2Flc"))
        self.gridLayout_4.addWidget(self.layer2Flc, 10, 1, 1, 1)
        self.runId = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.runId.setObjectName(_fromUtf8("runId"))
        self.gridLayout_4.addWidget(self.runId, 19, 0, 1, 2)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 18, 0, 1, 2)
        self.pbBrowse = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbBrowse.setObjectName(_fromUtf8("pbBrowse"))
        self.gridLayout_4.addWidget(self.pbBrowse, 16, 1, 1, 1)
        self.emptydir = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.emptydir.setObjectName(_fromUtf8("emptydir"))
        self.gridLayout_4.addWidget(self.emptydir, 17, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 698, 622))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/bridge_piers_AustRoads2018.PNG")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 391))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statusLog = QtGui.QListWidget(self.gridLayoutWidget)
        self.statusLog.setObjectName(_fromUtf8("statusLog"))
        self.gridLayout.addWidget(self.statusLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        tuflowqgis_BridgeEditor.setWidget(self.dockWidgetContents)

        self.retranslateUi(tuflowqgis_BridgeEditor)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_BridgeEditor)
        tuflowqgis_BridgeEditor.setTabOrder(self.tabWidget, self.bridgeName)
        tuflowqgis_BridgeEditor.setTabOrder(self.bridgeName, self.pbSaveFile)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbSaveFile, self.demComboBox)
        tuflowqgis_BridgeEditor.setTabOrder(self.demComboBox, self.pbDrawXsection)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbDrawXsection, self.pbUseMapWindowSel)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUseMapWindowSel, self.pbUpdateDeckData)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUpdateDeckData, self.deckElevationBottom)
        tuflowqgis_BridgeEditor.setTabOrder(self.deckElevationBottom, self.deckThickness)
        tuflowqgis_BridgeEditor.setTabOrder(self.deckThickness, self.handRailDepth)
        tuflowqgis_BridgeEditor.setTabOrder(self.handRailDepth, self.handRailFlc)
        tuflowqgis_BridgeEditor.setTabOrder(self.handRailFlc, self.handRailBlockage)
        tuflowqgis_BridgeEditor.setTabOrder(self.handRailBlockage, self.pbUpdatePierData)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUpdatePierData, self.pierNo)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierNo, self.pierWidth)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierWidth, self.pierWidthLeft)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierWidthLeft, self.pierGap)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierGap, self.pierShape)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierShape, self.zLineWidth)
        tuflowqgis_BridgeEditor.setTabOrder(self.zLineWidth, self.rbDrowned)
        tuflowqgis_BridgeEditor.setTabOrder(self.rbDrowned, self.rbUnderPressure)
        tuflowqgis_BridgeEditor.setTabOrder(self.rbUnderPressure, self.tabWidget_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.tabWidget_2, self.pierTable)
        tuflowqgis_BridgeEditor.setTabOrder(self.pierTable, self.pbUpdate)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUpdate, self.cbShowLegend_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.cbShowLegend_2, self.cbLegendUL_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.cbLegendUL_2, self.cbLegendUR_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.cbLegendUR_2, self.cbLegendLL_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.cbLegendLL_2, self.cbLegendLR_2)
        tuflowqgis_BridgeEditor.setTabOrder(self.cbLegendLR_2, self.deckTable)
        tuflowqgis_BridgeEditor.setTabOrder(self.deckTable, self.xSectionTable)
        tuflowqgis_BridgeEditor.setTabOrder(self.xSectionTable, self.layer1Block)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer1Block, self.emptydir)
        tuflowqgis_BridgeEditor.setTabOrder(self.emptydir, self.invert)
        tuflowqgis_BridgeEditor.setTabOrder(self.invert, self.layer1Obv)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer1Obv, self.shapeWidth)
        tuflowqgis_BridgeEditor.setTabOrder(self.shapeWidth, self.layer3Flc)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer3Flc, self.layer2Flc)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer2Flc, self.layer3Block)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer3Block, self.layer1Flc)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer1Flc, self.shapeOptions)
        tuflowqgis_BridgeEditor.setTabOrder(self.shapeOptions, self.dz)
        tuflowqgis_BridgeEditor.setTabOrder(self.dz, self.layer3Depth)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer3Depth, self.pbCreateLayer)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbCreateLayer, self.layer2Block)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer2Block, self.layer2Depth)
        tuflowqgis_BridgeEditor.setTabOrder(self.layer2Depth, self.pbUpdateAttributes)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUpdateAttributes, self.pbUpdateLayer)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbUpdateLayer, self.pbIncrementLayer)
        tuflowqgis_BridgeEditor.setTabOrder(self.pbIncrementLayer, self.statusLog)

    def retranslateUi(self, tuflowqgis_BridgeEditor):
        tuflowqgis_BridgeEditor.setWindowTitle(_translate("tuflowqgis_BridgeEditor", "Bridge Editor", None))
        self.label_5.setText(_translate("tuflowqgis_BridgeEditor", "DEM", None))
        self.label_10.setText(_translate("tuflowqgis_BridgeEditor", "Deck Thickness (m)", None))
        self.label_2.setText(_translate("tuflowqgis_BridgeEditor", "Zsh Line Width (m)", None))
        self.label.setText(_translate("tuflowqgis_BridgeEditor", "Z Shape Properties", None))
        self.label_6.setText(_translate("tuflowqgis_BridgeEditor", "Hand Rail Height (m)", None))
        self.label_8.setText(_translate("tuflowqgis_BridgeEditor", "Number of Piers", None))
        self.label_12.setText(_translate("tuflowqgis_BridgeEditor", "Pier Shape (see pier type tab)", None))
        self.pierShape.setItemText(0, _translate("tuflowqgis_BridgeEditor", "1", None))
        self.pierShape.setItemText(1, _translate("tuflowqgis_BridgeEditor", "2", None))
        self.pierShape.setItemText(2, _translate("tuflowqgis_BridgeEditor", "3", None))
        self.pierShape.setItemText(3, _translate("tuflowqgis_BridgeEditor", "4", None))
        self.pierShape.setItemText(4, _translate("tuflowqgis_BridgeEditor", "5", None))
        self.pierShape.setItemText(5, _translate("tuflowqgis_BridgeEditor", "6", None))
        self.pierShape.setItemText(6, _translate("tuflowqgis_BridgeEditor", "7", None))
        self.pierShape.setItemText(7, _translate("tuflowqgis_BridgeEditor", "8", None))
        self.label_9.setText(_translate("tuflowqgis_BridgeEditor", "Pier Thickness (m)", None))
        self.label_11.setText(_translate("tuflowqgis_BridgeEditor", "Deck", None))
        self.label_7.setText(_translate("tuflowqgis_BridgeEditor", "Piers", None))
        self.label_33.setText(_translate("tuflowqgis_BridgeEditor", "Hand Rail FLC", None))
        self.pbUseMapWindowSel.setText(_translate("tuflowqgis_BridgeEditor", "Existing Layer", None))
        self.label_32.setText(_translate("tuflowqgis_BridgeEditor", "Bridge Name (Optional)", None))
        self.label_16.setText(_translate("tuflowqgis_BridgeEditor", "Hand Rail Blockage", None))
        self.rbDrowned.setText(_translate("tuflowqgis_BridgeEditor", "Drowned", None))
        self.label_17.setText(_translate("tuflowqgis_BridgeEditor", "Flow at Deck", None))
        self.pbUpdateDeckData.setText(_translate("tuflowqgis_BridgeEditor", "Update Deck Data", None))
        self.label_13.setText(_translate("tuflowqgis_BridgeEditor", "Deck Elevation (Bottom) m RL", None))
        self.pbDrawXsection.setText(_translate("tuflowqgis_BridgeEditor", "Draw XSection", None))
        self.pbSaveFile.setText(_translate("tuflowqgis_BridgeEditor", "Save", None))
        self.rbUnderPressure.setText(_translate("tuflowqgis_BridgeEditor", "Under Pressure", None))
        self.pbUpdatePierData.setText(_translate("tuflowqgis_BridgeEditor", "Update Pier Data", None))
        self.label_34.setText(_translate("tuflowqgis_BridgeEditor", "Gap between Piers (m)", None))
        self.label_14.setText(_translate("tuflowqgis_BridgeEditor", "Width From Left (First Pier) (m)", None))
        self.enforceInTerrain.setText(_translate("tuflowqgis_BridgeEditor", "Enforce Cross Section in Zpts", None))
        self.pbClearXsection.setText(_translate("tuflowqgis_BridgeEditor", "Clear XSection", None))
        self.label_40.setText(_translate("tuflowqgis_BridgeEditor", "Row Count", None))
        item = self.xSectionTable.horizontalHeaderItem(0)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Offset", None))
        item = self.xSectionTable.horizontalHeaderItem(1)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Elevation", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("tuflowqgis_BridgeEditor", "XSection", None))
        self.label_41.setText(_translate("tuflowqgis_BridgeEditor", "Row Count", None))
        item = self.deckTable.horizontalHeaderItem(0)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Offset", None))
        item = self.deckTable.horizontalHeaderItem(1)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Elevation", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("tuflowqgis_BridgeEditor", "Deck Bottom", None))
        self.label_42.setText(_translate("tuflowqgis_BridgeEditor", "Row Count", None))
        item = self.pierTable.horizontalHeaderItem(0)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Offset", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("tuflowqgis_BridgeEditor", "Piers (CL)", None))
        self.pbUpdate.setText(_translate("tuflowqgis_BridgeEditor", "UPDATE PLOT", None))
        self.cbShowLegend_2.setText(_translate("tuflowqgis_BridgeEditor", "Legend", None))
        self.cbLegendUL_2.setText(_translate("tuflowqgis_BridgeEditor", "UL", None))
        self.cbLegendUR_2.setText(_translate("tuflowqgis_BridgeEditor", "UR", None))
        self.cbLegendLL_2.setText(_translate("tuflowqgis_BridgeEditor", "LL", None))
        self.cbLegendLR_2.setText(_translate("tuflowqgis_BridgeEditor", "LR", None))
        self.statusLabel.setText(_translate("tuflowqgis_BridgeEditor", "Status: Successful", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tuflowqgis_BridgeEditor", "Geometry", None))
        self.label_30.setText(_translate("tuflowqgis_BridgeEditor", "Empty Directory", None))
        self.label_4.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 FLC", None))
        self.pbCreateLayer.setText(_translate("tuflowqgis_BridgeEditor", "Auto Create 2d_lfcsh layer", None))
        self.label_3.setText(_translate("tuflowqgis_BridgeEditor", "Invert", None))
        self.pbUpdateLayer.setText(_translate("tuflowqgis_BridgeEditor", "Update Existing 2d_lfcsh layer with new bridge / attributes", None))
        self.label_25.setText(_translate("tuflowqgis_BridgeEditor", "Shape Options", None))
        self.label_28.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 FLC", None))
        self.label_19.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 Depth", None))
        self.label_24.setText(_translate("tuflowqgis_BridgeEditor", "Shape Width", None))
        self.label_27.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 % Blockage", None))
        self.pbIncrementLayer.setText(_translate("tuflowqgis_BridgeEditor", "Increment and Update Existing 2d_lfcsh layer", None))
        self.label_20.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 FLC", None))
        self.pbUpdateAttributes.setText(_translate("tuflowqgis_BridgeEditor", "Update", None))
        self.label_23.setText(_translate("tuflowqgis_BridgeEditor", "dZ", None))
        self.label_18.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 % Blockage", None))
        self.label_22.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 Obvert", None))
        self.label_26.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 Depth", None))
        self.label_31.setText(_translate("tuflowqgis_BridgeEditor", "Based on Hydraulics of Bridge Waterways (FHWA, 1978)", None))
        self.label_38.setText(_translate("tuflowqgis_BridgeEditor", "Comment", None))
        self.label_21.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 % Blockage", None))
        self.label_43.setText(_translate("tuflowqgis_BridgeEditor", "Run ID", None))
        self.pbBrowse.setText(_translate("tuflowqgis_BridgeEditor", "Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tuflowqgis_BridgeEditor", "Output", None))
        self.label_39.setText(_translate("tuflowqgis_BridgeEditor", "AustRoads 2018 - Incremental Backwater Coefficient for Piers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("tuflowqgis_BridgeEditor", "Pier Arrangement Types", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("tuflowqgis_BridgeEditor", "Status Log", None))

import bridge_piers_AustRoads2018_rc
