# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuflowqgis_1d_res.ui'
#
# Created: Tue Jan 14 10:29:15 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tuflowqgis_1d_res(object):
    def setupUi(self, tuflowqgis_1d_res):
        tuflowqgis_1d_res.setObjectName(_fromUtf8("tuflowqgis_1d_res"))
        tuflowqgis_1d_res.resize(734, 533)
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridlayout = QtGui.QGridLayout(self.tab_1)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label1 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.verticalLayout.addWidget(self.label1)
        self.ResList = QtGui.QListWidget(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResList.sizePolicy().hasHeightForWidth())
        self.ResList.setSizePolicy(sizePolicy)
        self.ResList.setMaximumSize(QtCore.QSize(300, 150))
        self.ResList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ResList.setObjectName(_fromUtf8("ResList"))
        self.verticalLayout.addWidget(self.ResList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.AddRes = QtGui.QPushButton(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddRes.sizePolicy().hasHeightForWidth())
        self.AddRes.setSizePolicy(sizePolicy)
        self.AddRes.setMinimumSize(QtCore.QSize(10, 20))
        self.AddRes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.AddRes.setObjectName(_fromUtf8("AddRes"))
        self.horizontalLayout.addWidget(self.AddRes)
        self.CloseRes = QtGui.QPushButton(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseRes.sizePolicy().hasHeightForWidth())
        self.CloseRes.setSizePolicy(sizePolicy)
        self.CloseRes.setMinimumSize(QtCore.QSize(10, 20))
        self.CloseRes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CloseRes.setAutoRepeat(False)
        self.CloseRes.setAutoDefault(False)
        self.CloseRes.setDefault(False)
        self.CloseRes.setFlat(False)
        self.CloseRes.setObjectName(_fromUtf8("CloseRes"))
        self.horizontalLayout.addWidget(self.CloseRes)
        self.pbAnimateLP = QtGui.QPushButton(self.tab_1)
        self.pbAnimateLP.setObjectName(_fromUtf8("pbAnimateLP"))
        self.horizontalLayout.addWidget(self.pbAnimateLP)
        self.cbShowLegend = QtGui.QCheckBox(self.tab_1)
        self.cbShowLegend.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbShowLegend.setObjectName(_fromUtf8("cbShowLegend"))
        self.horizontalLayout.addWidget(self.cbShowLegend)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label2 = QtGui.QLabel(self.tab_1)
        self.label2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.verticalLayout.addWidget(self.label2)
        self.sourcelayer = QtGui.QComboBox(self.tab_1)
        self.sourcelayer.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sourcelayer.setObjectName(_fromUtf8("sourcelayer"))
        self.verticalLayout.addWidget(self.sourcelayer)
        self.label3 = QtGui.QLabel(self.tab_1)
        self.label3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.verticalLayout.addWidget(self.label3)
        self.locationDrop = QtGui.QComboBox(self.tab_1)
        self.locationDrop.setMaximumSize(QtCore.QSize(300, 16777215))
        self.locationDrop.setObjectName(_fromUtf8("locationDrop"))
        self.verticalLayout.addWidget(self.locationDrop)
        self.label4 = QtGui.QLabel(self.tab_1)
        self.label4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.verticalLayout.addWidget(self.label4)
        self.ResTypeList = QtGui.QListWidget(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResTypeList.sizePolicy().hasHeightForWidth())
        self.ResTypeList.setSizePolicy(sizePolicy)
        self.ResTypeList.setMinimumSize(QtCore.QSize(10, 10))
        self.ResTypeList.setMaximumSize(QtCore.QSize(300, 150))
        self.ResTypeList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ResTypeList.setObjectName(_fromUtf8("ResTypeList"))
        self.verticalLayout.addWidget(self.ResTypeList)
        self.label5 = QtGui.QLabel(self.tab_1)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.verticalLayout.addWidget(self.label5)
        self.IDList = QtGui.QListWidget(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDList.sizePolicy().hasHeightForWidth())
        self.IDList.setSizePolicy(sizePolicy)
        self.IDList.setMinimumSize(QtCore.QSize(10, 0))
        self.IDList.setMaximumSize(QtCore.QSize(300, 16777215))
        self.IDList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.IDList.setObjectName(_fromUtf8("IDList"))
        self.verticalLayout.addWidget(self.IDList)
        self.label6 = QtGui.QLabel(self.tab_1)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.verticalLayout.addWidget(self.label6)
        self.listTime = QtGui.QListWidget(self.tab_1)
        self.listTime.setMinimumSize(QtCore.QSize(10, 0))
        self.listTime.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listTime.setObjectName(_fromUtf8("listTime"))
        self.verticalLayout.addWidget(self.listTime)
        self._2.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_for_plot = QtGui.QFrame(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_plot.sizePolicy().hasHeightForWidth())
        self.frame_for_plot.setSizePolicy(sizePolicy)
        self.frame_for_plot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_plot.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_plot.setObjectName(_fromUtf8("frame_for_plot"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_for_plot)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout.addWidget(self.frame_for_plot, 0, 0, 1, 1)
        self._2.addLayout(self.gridLayout)
        self.gridlayout.addLayout(self._2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        tuflowqgis_1d_res.setWidget(self.dockWidgetContents)

        self.retranslateUi(tuflowqgis_1d_res)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_1d_res)

    def retranslateUi(self, tuflowqgis_1d_res):
        tuflowqgis_1d_res.setWindowTitle(_translate("tuflowqgis_1d_res", "TUFLOW Results Viewer", None))
        self.label1.setText(_translate("tuflowqgis_1d_res", "Results Files", None))
        self.AddRes.setText(_translate("tuflowqgis_1d_res", "Add Results", None))
        self.CloseRes.setText(_translate("tuflowqgis_1d_res", "Close Results", None))
        self.pbAnimateLP.setText(_translate("tuflowqgis_1d_res", "Animate LP", None))
        self.cbShowLegend.setText(_translate("tuflowqgis_1d_res", "Show Legend", None))
        self.label2.setText(_translate("tuflowqgis_1d_res", "Source Layer to get ID\'s From", None))
        self.label3.setText(_translate("tuflowqgis_1d_res", "Location Type", None))
        self.label4.setText(_translate("tuflowqgis_1d_res", "Results Type", None))
        self.label5.setText(_translate("tuflowqgis_1d_res", "Selected Elements (display only)", None))
        self.label6.setText(_translate("tuflowqgis_1d_res", "Time (Long Profile Only)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("tuflowqgis_1d_res", "&Graph", None))

