# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuflowqgis_1d_xs.ui'
#
# Created: Fri May 08 12:43:29 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tuflowqgis_1d_xs(object):
    def setupUi(self, tuflowqgis_1d_xs):
        tuflowqgis_1d_xs.setObjectName(_fromUtf8("tuflowqgis_1d_xs"))
        tuflowqgis_1d_xs.resize(962, 557)
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridlayout = QtGui.QGridLayout(self.tab_1)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_for_plot = QtGui.QFrame(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_plot.sizePolicy().hasHeightForWidth())
        self.frame_for_plot.setSizePolicy(sizePolicy)
        self.frame_for_plot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_plot.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_plot.setObjectName(_fromUtf8("frame_for_plot"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_for_plot)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout.addWidget(self.frame_for_plot, 0, 0, 1, 1)
        self._2.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label1 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.verticalLayout.addWidget(self.label1)
        self.lvXSID = QtGui.QListWidget(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvXSID.sizePolicy().hasHeightForWidth())
        self.lvXSID.setSizePolicy(sizePolicy)
        self.lvXSID.setMinimumSize(QtCore.QSize(10, 10))
        self.lvXSID.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lvXSID.setObjectName(_fromUtf8("lvXSID"))
        self.verticalLayout.addWidget(self.lvXSID)
        self.cbRoughness = QtGui.QCheckBox(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbRoughness.sizePolicy().hasHeightForWidth())
        self.cbRoughness.setSizePolicy(sizePolicy)
        self.cbRoughness.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbRoughness.setObjectName(_fromUtf8("cbRoughness"))
        self.verticalLayout.addWidget(self.cbRoughness)
        self.pbClearSelection = QtGui.QPushButton(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClearSelection.sizePolicy().hasHeightForWidth())
        self.pbClearSelection.setSizePolicy(sizePolicy)
        self.pbClearSelection.setMinimumSize(QtCore.QSize(10, 20))
        self.pbClearSelection.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pbClearSelection.setAutoRepeatDelay(300)
        self.pbClearSelection.setObjectName(_fromUtf8("pbClearSelection"))
        self.verticalLayout.addWidget(self.pbClearSelection)
        self.pbLoadAll = QtGui.QPushButton(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLoadAll.sizePolicy().hasHeightForWidth())
        self.pbLoadAll.setSizePolicy(sizePolicy)
        self.pbLoadAll.setMinimumSize(QtCore.QSize(10, 20))
        self.pbLoadAll.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pbLoadAll.setAutoRepeat(False)
        self.pbLoadAll.setAutoDefault(False)
        self.pbLoadAll.setDefault(False)
        self.pbLoadAll.setFlat(False)
        self.pbLoadAll.setObjectName(_fromUtf8("pbLoadAll"))
        self.verticalLayout.addWidget(self.pbLoadAll)
        self.cbDeactivate = QtGui.QCheckBox(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDeactivate.sizePolicy().hasHeightForWidth())
        self.cbDeactivate.setSizePolicy(sizePolicy)
        self.cbDeactivate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbDeactivate.setObjectName(_fromUtf8("cbDeactivate"))
        self.verticalLayout.addWidget(self.cbDeactivate)
        self.label2 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setMinimumSize(QtCore.QSize(10, 10))
        self.label2.setMaximumSize(QtCore.QSize(200, 20))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.verticalLayout.addWidget(self.label2)
        self.lwStatus = QtGui.QListWidget(self.tab_1)
        self.lwStatus.setMinimumSize(QtCore.QSize(10, 10))
        self.lwStatus.setMaximumSize(QtCore.QSize(200, 200))
        self.lwStatus.setObjectName(_fromUtf8("lwStatus"))
        self.verticalLayout.addWidget(self.lwStatus)
        self.pbClearStatus = QtGui.QPushButton(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClearStatus.sizePolicy().hasHeightForWidth())
        self.pbClearStatus.setSizePolicy(sizePolicy)
        self.pbClearStatus.setMinimumSize(QtCore.QSize(10, 0))
        self.pbClearStatus.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pbClearStatus.setObjectName(_fromUtf8("pbClearStatus"))
        self.verticalLayout.addWidget(self.pbClearStatus)
        self._2.addLayout(self.verticalLayout)
        self.gridlayout.addLayout(self._2, 1, 0, 1, 1)
        self.cbShowLegend = QtGui.QCheckBox(self.tab_1)
        self.cbShowLegend.setObjectName(_fromUtf8("cbShowLegend"))
        self.gridlayout.addWidget(self.cbShowLegend, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.frame_for_toolbar = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_toolbar.sizePolicy().hasHeightForWidth())
        self.frame_for_toolbar.setSizePolicy(sizePolicy)
        self.frame_for_toolbar.setMinimumSize(QtCore.QSize(300, 40))
        self.frame_for_toolbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_for_toolbar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_toolbar.setObjectName(_fromUtf8("frame_for_toolbar"))
        self.verticalLayout_3.addWidget(self.frame_for_toolbar)
        tuflowqgis_1d_xs.setWidget(self.dockWidgetContents)

        self.retranslateUi(tuflowqgis_1d_xs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_1d_xs)

    def retranslateUi(self, tuflowqgis_1d_xs):
        tuflowqgis_1d_xs.setWindowTitle(_translate("tuflowqgis_1d_xs", "TUFLOW 1D Section Viewer", None))
        self.label1.setText(_translate("tuflowqgis_1d_xs", "Cross Sections Selected", None))
        self.cbRoughness.setText(_translate("tuflowqgis_1d_xs", "Display Roughness", None))
        self.pbClearSelection.setText(_translate("tuflowqgis_1d_xs", "Clear Selection", None))
        self.pbLoadAll.setText(_translate("tuflowqgis_1d_xs", "Load All", None))
        self.cbDeactivate.setText(_translate("tuflowqgis_1d_xs", "Deactivate", None))
        self.label2.setText(_translate("tuflowqgis_1d_xs", "Status", None))
        self.pbClearStatus.setText(_translate("tuflowqgis_1d_xs", "Clear Status", None))
        self.cbShowLegend.setText(_translate("tuflowqgis_1d_xs", "Show Legend", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("tuflowqgis_1d_xs", "&Graph", None))

